- setup.py
- tests/sparseml/tensorflow_v1/optim/test_analyzer_module.py
- tests/sparseml/tensorflow_v1/optim/test_mask_creator_pruning.py
- tests/sparseml/tensorflow_v1/optim/test_mask_pruning.py
Some of our tensorflow_v1 sparsity mask tests use randomly initialized tensors for testing. This can cause errors on the unlikely (but not impossible) chance that the randomly initialized tensor has a 0 in it as well as other situations.  We've seen this happen less than 5 times over the last 6 months, but it's happened twice in the last week now, so am nipping this in the bud.  @kevinaer suggested looking into flaky tests when this first occured.
Adding the flaky decorator, has pytest rerun the flaky test once (can be set to other values) if it fails.  This should be greatly decrease the chance that one of these tests will fail due to a 0 popping up in the test tensor.
https://pypi.org/project/flaky/
even though the decorator is called through pytest, I've checked that flaky must be …
> add decorator for flaky tf sparsity tests

- docs/source/recipes.md
- src/sparseml/optim/modifier.py
- tests/sparseml/pytorch/optim/test_modifier.py
This change will enable SparseML to parse multiple lists of modifiers (groups) from a recipe.  The resulting structure will look like this:
```
...
- !SetLearningRateModifier
...
- !GMPruningModifier
...
- !GMPruningModifier
...
- !GMPruningModifier
...
quantization_modifiers:
...
- !SetWeightDecayModifier
...
```
All modifiers will be parsed into a single `Modifier` list at run time.  Not adding any filtering in the lists to see if they are actually of modifiers, so the user will be able to see any errors if the recipe is incorrect.
> enable modifier groups in SparseML recipes

- Makefile
- setup.py
- src/sparseml/tensorflow_v1/utils/variable.py
this PR introduces a Makefile argument and modifies `setup.py` so nightly packages can be built with
```
make build BUILD_ARGS=nightly
```
`dist` directory contents after building:
```
sparseml_nightly-0.1.0.20210204-py3-none-any.whl  sparseml-nightly-0.1.0.20210204.tar.gz
```
> make build argument for nightly builds

- src/sparseml/pytorch/optim/quantization/helpers.py
this fixes bugs in Yolo V3 QAT where quant/dequant observers were placed in incorrect parts within the model graph
> match types explicitly in torch qat quant observer wrappers

- scripts/pytorch_vision.py
enable simple, single command reproduction/transfer learning for pruned/quantized models. i.e.
```
python scripts/pytorch_vision.py train \
--recipe-path zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned_quant-moderate?recipe_type=transfer_learn \
--checkpoint-path zoo \
--model-kwargs '{"ignore_error_tensors": ["classifier.fc.weight", "classifier.fc.bias"]}' \
--dataset imagenette \
--dataset-path /PATH/TO/IMAGENETTE  \
--train-batch-size 32 --test-batch-size 64 \
--loader-num-workers 8 \
--optim Adam \
--optim-args '{}' \
--model-tag resnet50-imagenette-pruned_quant-transfer_learned
```
> load checkpoint file based on sparsezoo recipe in pytorch_vision script

- src/sparseml/pytorch/optim/quantization/quantize_qat_export.py
this functionality was built in, but overwritten. useful for QAT ONNX export flows
> load qat onnx models for conversion from file path

- examples/pytorch_sparse_quantized_transfer_learning/README.md
- notebooks/README.md
the purpose of this document is to provide a blog-like landing page that gives a quick primer and motivation for sparse-quantized transfer learning and how to quickly get started using it with SparseML
> blog style readme for torch sparse-quant TL notebook

- src/sparseml/pytorch/utils/module.py
This is a forgotten fix for `ModuleTester` class. The description is the same as for #135 .
> Fix incorrect loss scaling in DDP setup

- src/sparseml/pytorch/utils/module.py
Memory leak seems to be related to the way how tqdm is wrapping data_loader.
More info at: https://github.com/tqdm/tqdm/issues/746
This PR fixes https://github.com/neuralmagic/sparseml/issues/152
> Fix memory leak when using debug-steps

- scripts/pytorch_vision.py
Without this flag the `InceptionCrossEntropyLossWrapper` would be the default loss in "train mode", even if the `arch_key` doesn't have "inception" keyword.
> Fix missing flag for training loss

- integrations/transformers/run_distill_qa.py
- integrations/transformers/run_qa.py
This PR fixes https://github.com/neuralmagic/sparseml/issues/200
(sorry for bundling auto-corrected whitespaces)
> Fix steps_per_epoch calculation

- src/sparseml/pytorch/optim/mask_creator_pruning.py
This PR should fix: https://github.com/neuralmagic/sparseml/issues/429 by creating a local random instance with a fixed seed.
> Use local random generator with fixed seed

- src/sparseml/pytorch/optim/modifier_quantization.py
- tests/sparseml/pytorch/optim/test_modifier_quantization.py
update to `QuantizationModifier` to fix bug where if a `Linear` or `Conv2d` layer was directly referenced as a target submodule, it would not be converted to a QAT module.  Improved the quantization test suite to include deeper testing for various submodule targets
quick python example of quantizing a BERT model with a submodule target that is a `Linear`
```python
from transformers import AutoModelForQuestionAnswering
from sparseml.pytorch.optim import QuantizationModifier
model = AutoModelForQuestionAnswering.from_pretrained("bert-base-uncased")
QuantizationModifier(submodules=["bert.embeddings", "bert.encoder", "qa_outputs"]).apply(model)
print(model.qa_outputs)
```
> fix QuantizationModifier for Conv/Linear target submodules

- src/sparseml/pytorch/utils/quantization/quantize_qat_export.py
- src/sparseml/transformers/__init__.py
did my best to reuse code, unfortunately there's some annoying but large enough differences in the pattern matching
> ONNX QAT -> Quant conversion for Gemm nodes w/o QAT activations

- src/sparseml/pytorch/models/classification/resnet.py
- src/sparseml/pytorch/optim/modifier_quantization.py
- src/sparseml/pytorch/optim/optimizer.py
- tests/sparseml/pytorch/models/classification/test_resnet.py
- tests/sparseml/pytorch/optim/test_modifier_quantization.py
- tests/sparseml/pytorch/utils/quantization/test_helpers.py
Adds: A generic calibratiion dataloader and a calibration forward function, for calibrating weights after training, (Post Training Quantization)
```python
import torch
from sparseml.pytorch.models import resnet50
from sparseml.pytorch.optim import QuantizationModifier
def random_dataloader(n=5):
"""
A random generator
"""
for _ in range(n):
print(f"Trying to yield batch {_}")
yield [torch.rand(32, 3, 224, 224)], {}
model = resnet50(pretrained=True)
modifier = QuantizationModifier(start_epoch=0)
modifier.apply(
module=model,
calibration_dataloader=random_dataloader(),
)
print(model(torch.rand(1, 3, 224, 224)))
print(model)
```
Can also pass in a Calibration function along with dataloader
```python
import torch
from sparseml.pytorch.models import resnet50
from sparseml.pytorch.optim import …
```
> Add: Generic calibration dataloader + forward function

- src/sparseml/pytorch/optim/modifier_quantization.py
- src/sparseml/pytorch/utils/helpers.py
- src/sparseml/pytorch/utils/quantization/helpers.py
- tests/sparseml/pytorch/optim/test_modifier_quantization.py
```python
import torch
from sparseml.pytorch.models import resnet50
from sparseml.pytorch.optim import QuantizationModifier
model = resnet50(pretrained=True)
modifier = QuantizationModifier(start_epoch=0, activation_bits=4)
modifier.apply(
module=model,
)
print(model(torch.rand(1, 3, 224, 224)))
for param in model.parameters():
print(param.data.min(), param.data.max())
```
> Activation Bits Support + qconfig kwargs for QuantizationModifier

- src/sparseml/pytorch/sparsification/pruning/mask_creator.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_acdc.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_magnitude.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
- tests/sparseml/pytorch/sparsification/pruning/test_mask_creator.py
- tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_magnitude.py
- tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_mfac.py
* rename "block" mask creator to "block4"
* reintroduce formerly removed `[x,y]` block mask creator/notation
* helper function for creating basic mask creators
* checked through existing zoo and example recipes to confirm none are affected
> mask creator refactor

- src/sparseml/optim/helpers.py
- tests/sparseml/optim/test_helpers.py
When a manager calls a `from_yaml()` function to construct itself...
...it can take `recipe_variables`  argument. It allows overwriting chosen variables in the recipe. While this function was working correctly with standard recipes, now it also parses staged recipes. The overwriting happens in a greedy way i.e. the code looks at every possible variable in the raw recipe (at every level). If it finds a key that corresponds to the entry it`recipe_variables`: do overwrite.
> Make staged recipes be properly overwritten by `recipe_variables` argument.

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_acdc.py
When applying a checkpoint recipe containing ACDCPruningModifier to a model, the modifier's `get_applied_sparsity_for_epoch` method receives `epoch=float('inf')`. This breaks the modifier (`cannot convert float infinity to integer`).
This diff is my best and quickest way how to mitigate this problem, but I am open for suggestions.
> ACDC: Passing `epoch = float('inf)` when applying recipe to a model.

- README.md
Refreshed the `Tutorials` section in the root readme. Picture below.
> added tutorials to root readme split by domain

- src/sparseml/pytorch/sparsification/distillation/modifier_distillation.py
Implements https://github.com/neuralmagic/sparseml/issues/693
> Avoid numerically unstable log

- src/sparseml/pytorch/models/classification/resnet.py
PR to revert changes made to the definition of resnet models to state prior to quantization refactor. Changes made during quantization refactor are kept as comments for future. Checked that pushed quantized models can load correctly.
> Revert rn residual quant

- src/sparseml/pytorch/image_classification/lr_analysis.py
The goal of this PR is to make `SparseML-PyTorch` lr_sensitivity analysis integration (for image classification) more maintainable by removing dependency on `LRArguments` class. The idea is to have a single source of truth for all command line arguments. This also integrates click with the `lr_analysis` script as per standards.
The following commands have been tested locally to ensure these changes do not break existing flows:
```bash
sparseml.image_classification.lr_analysis \
--arch-key resnet50 --dataset imagenette --dataset-path data --batch-size 32
```
Output from above command:
```
LR Sensitivity
LR		Loss
1.0000E-09		2.3267
1.1000E-09		2.3192
1.2100E-09		2.3315
1.3310E-09		2.3203
1.4641E-09		2.3139
1.6105E-09		2.3020
1.7716E-09		2.3223
1.9487E-09		2.3168
2.1436E-09		2.3170 …
```
> Click refactor for SparseML-PyTorch `lr-analysis` integration

- src/sparseml/pytorch/image_classification/export.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
The goal of this PR is to make `SparseML-PyTorch` export integration (for image classification) more maintainable by removing dependency on `ExportArgs` class. The idea is to have a single source of truth for all command line arguments. This also integrates `click` with the export script as per standards.
The following commands have been tested locally to ensure these changes do not break existing flows
```bash
sparseml.image_classification.export \
--dataset imagenette \ 
--dataset-path ~/data \
--checkpoint-path ~/models/checkpoint-best.pth
```
> Click refactor for SparseML PyTorch `export` integration

- src/sparseml/pytorch/utils/logger.py
Scalar logs with `level=None` were getting written to file. This fix ensures that they remain at the debug level unless explicitly set otherwise
> Fix: default python log calls to debug level

- src/sparseml/pytorch/sparsification/quantization/helpers.py
changes from #604 were lost at some point, likely in a merge resolution
> re-add fix symmetric zero points for unit8 quantization (#604)

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
Fixes https://github.com/neuralmagic/sparseml/issues/759 by allowing to collect gradients only when:
1. standard gradual pruning run is invoked (identified as the case with `steps_per_epoch > 1`) but not during the `initialize` call
2. one-shot run identified as the case with `steps_per_epoch = 1` and `epoch = inf` (according to the way how one-shot is called via `.apply()`https://github.com/neuralmagic/sparseml/blob/a6477f900b55afd555734fe6cf784e0137d815a5/src/sparseml/pytorch/sparsification/modifier.py#L154
> Guard against grad collecting during init

- src/sparseml/pytorch/object_detection/train.py
The goal of this PR is to add support for exporting sample inputs and outputs for SparseML's YOLOv5 integration
To this end, A new CLI arg `--num-export-samples` has been added, the functionality has been tested locally using the following command:
```bash
sparseml.object_detection.train \
--weights " " \
--data coco128.yaml \
--epochs 5 --cfg models_v5.0/yolov5s.yaml \
--recipe zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer_learn \
--one-shot \
--num-export-samples 10
```
Relevant Output:
```bash
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /XXXXXX/projects/sparseml/src/sparseml/pytorch/object_detection/runs/train/exp46
Starting training for 5 epochs...
Skipped training due to one-shot: True
One shot checkpoint …
```
> `YOLOv5` Export Sample inputs/outputs

- src/sparseml/transformers/sparsification/trainer.py
Fixes https://github.com/neuralmagic/sparseml/issues/817 by averaging losses before loggers are called.
It's guarded with `n_gpu > 1` to avoid synchronizing processes in DDP runs.
> Average losses before logging is called

- src/sparseml/keras/optim/modifier.py
- src/sparseml/optim/modifier.py
- src/sparseml/pytorch/sparsification/modifier.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_layer.py
- src/sparseml/tensorflow_v1/optim/modifier.py
Under the current `end_comparator` the end epoch of `LayerPruningModifier` must be greater than the start epoch. This would make a schedule like `start_epoch=2.0, end_epoch=-1` invalid which is a bug, since we should be able to start at an arbitrary epoch (`start_epoch=2.0`) and run indefinitely (`end_epoch=-1.0`)
`end_comparator` specs: 
https://github.com/neuralmagic/sparseml/blob/29119f73596fbea01a0b82133696305995a5b72c/src/sparseml/optim/modifier.py#L630
https://github.com/neuralmagic/sparseml/blob/29119f73596fbea01a0b82133696305995a5b72c/src/sparseml/optim/modifier.py#L631
> set end_comparator of LayerPruningModifier to -1

- src/sparseml/yolov5/data/Argoverse.yaml
- src/sparseml/yolov5/data/GlobalWheat2020.yaml
- src/sparseml/yolov5/data/Objects365.yaml
- src/sparseml/yolov5/data/SKU-110K.yaml
- src/sparseml/yolov5/data/VOC.yaml
- src/sparseml/yolov5/data/VisDrone.yaml
- src/sparseml/yolov5/data/coco.yaml
- src/sparseml/yolov5/data/xView.yaml
Update paths for data download in .yaml data files
> [Yolov5] Update in yaml dataset scripts

- src/sparseml/yolov5/data/Argoverse.yaml
- src/sparseml/yolov5/data/GlobalWheat2020.yaml
- src/sparseml/yolov5/data/Objects365.yaml
- src/sparseml/yolov5/data/SKU-110K.yaml
- src/sparseml/yolov5/data/VOC.yaml
- src/sparseml/yolov5/data/VisDrone.yaml
- src/sparseml/yolov5/data/coco.yaml
- src/sparseml/yolov5/data/xView.yaml
This PR reverts the path changes to the yaml dataset script, as the datasets will now be maintained in `./datasets` relative to the run directory, rather than relative to the `sparseml/yolov5` directory.
> Revert "[Yolov5] Update in yaml dataset scripts (#869)"

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_constant.py
`global_sparsity` is unused in ConstantPruningModifier so I had to explicitly make it non-serializable in this specific class.
Fixes https://github.com/neuralmagic/sparseml/issues/916
> Make global_sparsity prop serializable

- .MAINTAINERS
- .github/workflows/assign-review.yaml
Adds a `.MAINTAINERS` file with list of the active repo maintainers.  Uncommented maintainers will be considered active for random PR review selection by the `assign-review` GHA workflow.
The workflow currently includes:
1. on PR open - assigns the PR opener as the assignee on the PR
2. on ready to review (PR not in draft mode and 'wip' not in PR title) - adds 1 random maintainer-reviewer as the PR reviewer
> add .MAINTAINERS file and auto review assignment GHA workflow 

- src/sparseml/onnx/utils/graph_optimizer.py
- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
- src/sparseml/version.py
- Fix ONNX export for BERT models (removes quantization from identity branch of FFN block)
- Bumps version number up to 1.0.1
> Cherry-pick ONNX export update into release 1.0

- MANIFEST.in
- setup.py
- src/sparseml/yolact/COCO.sh
- src/sparseml/yolact/COCO_test.sh
- src/sparseml/yolact/__init__.py
- src/sparseml/yolact/scripts.py
This PR adds command line callables for yolact integration (On top of yolact-autoinstall)
Tests: Each of the scripts/callables were invoked with a `--help` option, to check auto installation of yolact wheel, along with invocation of correct scripts
Setup:
1. `git clone git@github.com:neuralmagic/sparseml.git`
2. `git checkout yolact-cli`
3. `pip install -e "./[torchvision]"`
```bash
❯ sparseml.yolact.download                                                                                                                                                                                                                          17:42:54
Downloading MSCOCO train images ...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
3 …
```
> Add 4  command line callables for yolact

- src/sparseml/yolov5/scripts.py
This PR adds the options of calling into the yolov5 integration via function, in addition to the cli support that exists right now.
Testing:
Manually ran `commit` cadence yolov5 tests on local machine.
> Add support for directly calling yolov5 hooks

- tests/integrations/base_tester.py
- tests/integrations/image_classification/test_image_classification.py
- tests/integrations/transformers/test_transformers.py
- tests/integrations/yolov5/test_yolov5.py
This PR wraps the integrations tests in a flaky decorator to avoid transient issues from failing checks. e.g. connection issues.
> Add flaky decorator to integration tests

- docker/Dockerfile
the affected patch in the dockerfile is only relevant to the 11.4 container which causes file not found issues on the 10.2 build. this PR makes the patch optional pending the existence of the files
**test_plan**
build passes locally (second rm command gets a no such file error previously)
> make sparseml Docker fix conditional

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
Pytorch caching doesn't seem to work consistently across different versions, so let's make sure we clear it explicitly before and after the pruning step.
> Clear cache before and after the OBS pruning step

- src/sparseml/onnx/benchmark/info.py
- tests/sparseml/onnx/benchmark/test_info.py
previously failing due to an API change
**test_plan:**
unblocks unit tests locally
> use correct zoo download dir param in onnx tests

- src/sparseml/pytorch/optim/mask_creator_pruning.py
- src/sparseml/pytorch/sparsification/distillation/modifier_distillation.py
- src/sparseml/pytorch/sparsification/pruning/mask_creator.py
Progress on upgrades to torch 1.12. Main pr is #964.
Testing was done by running unit tests in python 3.10 and torch 1.12.
> Using torch.linalg.vector_norm over norm

- setup.py
* Freeze setuptools at 59.5.0
To address issue discussed in https://github.com/pytorch/pytorch/issues/69894#issuecomment-1080635462
* setuptools<=59.5.0
> Freeze setuptools at 59.5.0 (#982)

- src/sparseml/pytorch/image_classification/train.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
default saved epoch for `one_shot` in the IC flows is `-1` due to `Trainer` initialization. This will cause issues on model load since the checkpoint recipe will be initialized to epoch `-1`, not applying any of the optimizations. This PR removes saving the epoch for one shot models so the entire one shot recipe will be applied on checkpoint load.
**test_plan:**
@anmarques to verify
> don't save epoch on IC one_shot checkpoints

- integrations/huggingface-transformers/tutorials/sparsifying_bert_using_recipes.md
This PR add a missing `\` in sparsifying bert tutorial
> Fix typo in bert tutorial

- src/sparseml/pytorch/sparsification/quantization/helpers.py
- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
Cherry-pick changes added to support custom quantizable modules (e.g., GELU).
> Feature custom qat module

- integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md
This PR removes the old unsupported pathway to create your own baseline Yolact model from a `darknet53.pth` backbone. Instead users are recommended to leverage and use yolact models(including baseline) from sparsezoo. The docs have been updated accordingly
> Yolact doc updates

- integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md
Yolact docs were updated erroneously (and this pathway was removed), now that `starting from a darknet53` pathway is supported again, the changes were reverted and commands were updated accordingly
Blocked on: [PR #47 on neuralmagic/yolact](https://github.com/neuralmagic/yolact/pull/47)
> Yolact doc revert n updates

- setup.py
Because click~=8.0.0 is explicitly not allowed by wandb, this PR allows minor version updates to click.
Tested by testing with dev dependencies (black) and the following command
sparseml.image_classification.pr_sensitivity
--arch-key ssd300_resnet50 --dataset coco
--dataset-path ~/datasets/coco-detection
> Relax click dependency (#1024)

- src/sparseml/pytorch/image_classification/utils/trainer.py
prior to this fix, IC trainer would recognize any checkpoint starting with "zoo" as a stub, this causes issues if a local path starts with zoo. this PR fixes the issue by matching to the full zoo prefix "zoo:"
> [image classification] bug fix - use full zoo stub prefix to determine zoo checkpoint

- .github/workflows/test-check.yaml
Github workflows will now default to python 3.10 and torch 1.12
Test plan: unit tests
> Moving github workflows to python 3.10 & adding backwards compat steps

- src/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py
collections.Mapping no longer exists in python 3.10
> Using typing.Mapping instead of collections

- src/sparseml/onnx/utils/graph_editor.py
- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
The current method of keep_params causes a crash in torch 1.12, because initializers can be used by multiple nodes. Therefore removing an initializer is only safe if it is not used.
> No longer removing initializer if it is still in use in onnx graph

- src/sparseml/pytorch/utils/exporter.py
In torch 1.12, some of the initializers are used by multiple nodes. For this fix_batch_norm_names function, this was causing a bug where:
1. A node's input & initializer were updated by removing ".module"
2. Another node that also used that initializer was not updated because the check for `init_name not in name_to_inits` failed, so the node was skipped
This PR simplifies the logic of the above by changing initializer names and node input/output names separately.
> Simplifying and fixing fix_batch_norm_names

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
In torch 1.12, softmax gets a qconfig added to it by the quantization modifier. Thus it ends up with QDQ nodes after the softmax node in the onnx graph:
This PR adds Softmax to a to_exclude list in Quantization modifier so this does not occur.
Test plan: ran resnet50 export for quant & non-quant versions and verified that softmax no longer has QDQ nodes after it in 1.12
> Adding Softmax to_exclude in QuantizationModifier

- src/sparseml/pytorch/utils/helpers.py
All layers in GPT-style models are implemented as custom `Conv1D` layers (see https://github.com/huggingface/transformers/blob/c60dd98e87373e7f0f5af29f3d49411c2e81fb69/src/transformers/pytorch_utils.py#L92) and thus are missed when checking for instances of `nn.Linear` or `nn.ConvNd`
> Add matching for GPT layers

- src/sparseml/pytorch/utils/exporter.py
Reasoning: in torch 1.12 any shape operations *without* batch dimension as dynamic will be treated as a constant, and therefore constant folding operations will apply to them. For example in resnet there is a flatten operation towards the end of the graph.
In torch 1.12, without dynamic_axes="batch" set, you get this graph:
With dynamic_axes="batch set, you get this graph:
> Deprecating dynamic_axes and always setting it

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
This feature improves OBSPruningModifier by allowing to recompute inverse Hessian `num_recomputations` times when doing a pruning step. 
For example, in the standard pipeline we would ask OBSPruningModifier to prune a model to 50% and it would do so by estimating inverse Hessian once and then use it to prune weights. This recomputation feature enables doing the same pruning step but with multiple estimations of the inverse Hessian. For example, `num_recomputations=2` would estimate the inverse Hessian, prune `50%/num_recomputations = 25%` of weights, and then re-estimate it again (with newly pruned weights taken into consideration) and prune the remaining 25% to reach the pruning target of 50%.
This feature helps a lot in situations where a lot of weights are being removed in one pruning …
> Implement invHess recomputations for OBS

- src/sparseml/optim/modifier.py
Fixes https://github.com/neuralmagic/sparseml/issues/1032 by ensuring `start_epoch`/`end_epoch` are always floats.
> Ensure start_epoch and end_epoch are floats

- setup.py
- src/sparseml/pytorch/__init__.py
- src/sparseml/pytorch/utils/exporter.py
> Allowing torch 1.10 and 1.11, but raising error with quantized exports

- src/sparseml/transformers/export.py
- src/sparseml/transformers/masked_language_modeling.py
This PR represents the changes needed to support  sample inputs/outputs export with `sparseml.transformers.export_onnx` utility for `masked_language_modeling`
The main changes include:
(Note: This PR must be merged into #1115)
> Export refactor mlm

- src/sparseml/pytorch/datasets/classification/imagefolder.py
- tests/sparseml/pytorch/datasets/classification/test_imagefolder.py
Before this PR if anything from `sparseml.pytorch.datasets.classification` module was imported (w/o `torchvision` installed), an un-intuitive error message was thrown:
```python
from sparseml.pytorch.datasets.classification.imagefolder import ImageFolderDataset
File "/home/XXXXX/virtual_environments/sparseml3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-2-a247de027853>", line 1, in <module>
from sparseml.pytorch.datasets.classification.imagefolder import ImageFolderDataset
File "/home/XXXXX/projects/sparseml/src/sparseml/pytorch/datasets/__init__.py", line 22, in <module>
from .classification import *
File …
```
> Fix Error Message with `ImageFolderDataset`

- src/sparseml/pytorch/utils/exporter.py
- tests/sparseml/pytorch/utils/test_exporter.py
As of torch 1.12, the zero_point/scale params are all arrays with shape `(1,)`. This causes some crashes for yolov5 integration tests (but for some reason not other models).
This PR flattens all the zero_point/scale inits to shape `()` if they have shape `(1,)`
Testing plan: manual export of yolov5. I can probably add a simple unit test for this too
> Adding pass to flatten zero_point/scale params

- src/sparseml/pytorch/utils/exporter.py
in torch 1.9, some initializers into QuantizeLinear and DequantizeLinear are actually Constant nodes. This is currently handled by a pass in the convert qat stuff, but since flatten_qparams happens outside of that, the constant nodes haven't been merged in.
A simple change for now is to only change the inputs to Q/DQ if they are initializers. Previously this function would error they weren't initializers.
Test plan: manual testing of exporting yolov5 on torch1.9 and 1.12
> Only applying flatten qparams to initializers that exist

- README.md
When I click on the link, it leads to a 404. Now, it points to the right place
> Use correct URL for ONNX export

- src/sparseml/pytorch/recipe_template/cli.py
- src/sparseml/pytorch/recipe_template/main.py
- tests/sparseml/pytorch/recipe_template/test_main.py
Added a cli for recipe template, after rebasing last state on main
Now the recipe template function can be invoked via the command line using `sparsem.pytorch.recipe_template` utility
```bash
sparseml.pytorch.recipe_template --help
```
```bash
Usage: sparseml.pytorch.recipe_template [OPTIONS]
Utility to create a recipe template based on specified options
Example for using sparseml.recipe_template:
`sparseml.pytorch.recipe_template --pruning true --quantization true`
`sparseml.pytorch.recipe_template --quantization vnni --lr constant `
Options:
--version                       Show the version and exit.  [default: False]
--pruning [true|false|gmp|acdc|mfac|movement|constant]
Specify if recipe should include pruning
steps, can also take in the name of a
pruning algorithm  [default: false] …
```
> Add recipe template cli

- src/sparseml/pytorch/torchvision/train.py
- Only doing lr_scheduler initialization logic if manager.learning_rate_modifiers is None
- Moving loading lr_scheduler from checkpoint to initialization logic
Testing plan: Manual command line testing for now, will add unit tests later
> Not initializing lr_scheduler if manager.learning_rate_modifiers

- src/sparseml/pytorch/image_classification/export.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
- src/sparseml/pytorch/utils/model.py
- tests/sparseml/pytorch/image_classification/resnet_test_recipe.yaml
- tests/sparseml/pytorch/image_classification/test_export.py
This PR adds support to apply a recipe in `one-shot` manner while exporting Image classification models
Test plan: Automated test to start with a vanilla(non-quantized) `resnet50`, export checkpoint in one-shot manner with a quantization recipe and then check the onnx graph for quantized nodes
Note the failing test should pass after #1122 lands
> One shot export [Image classification]

- src/sparseml/optim/helpers.py
- src/sparseml/pytorch/recipe_template/main.py
- tests/sparseml/pytorch/recipe_template/test_main.py
This diff updates the existing recipe_template codebase according to newer defaults and also adds some additional variables, moreover this diff also allows the users to easy override certain control variables such as:
- `num_epochs`
- `init_lr`
- `final_lr`
- `sparsity`
These variables in turn trigger updates to certain other recipe variables
Note: An additional convenience function was also added in helpers to get recipe-variables from a recipe for easier testing (Maybe that function doesn't belong in this diff, happy to update if that's a blocker)
Test Criterion: Automated Tests
> Update defaults + additional variables for recipe_template 

- setup.py
- src/sparseml/optim/helpers.py
- src/sparseml/pytorch/recipe_template/main.py
- src/sparseml/recipe_template/__init__.py
- src/sparseml/recipe_template/utils.py
- tests/sparseml/pytorch/recipe_template/test_main.py
This PR represents the main feature branch for newer additions to `recipe_template`
TODOs:
> Recipe Template extra features

- src/sparseml/pytorch/torchvision/export_onnx.py
- src/sparseml/pytorch/torchvision/train.py
- src/sparseml/pytorch/utils/helpers.py
This is the base feature branch for torchvision image classification rewrite
TODOS:
Verification
Later:
Ran the following and verified that they both achieve similar top1 accuracy scores of > 90%
```bash
--recipe-path zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/pruned-conservative?recipe_type=original \
--pretrained True \
--dataset imagenette \
--dataset-path ~/.cache/nm_datasets/imagenette/imagenette-320/  \
--train-batch-size 128 --test-batch-size 128 \
--optim SGD \
--optim-args '{}' \
--model-tag resnet50-imagenette-pruned-conservative \
--save-dir ./training-runs/image_classification-pretrained \
--logs-dir ./training-runs/image_classification-pretrained
```
```bash
python …
```
> torchvision image classification

- src/sparseml/pytorch/torchvision/README.md
- src/sparseml/pytorch/torchvision/train.py
This changes `--recipe-path` to `--recipe` and checks if any arguments aren't recognized by click. If so it raises an error message about migrating to new script.
> Adding deprecation message to torchvision train

- src/sparseml/transformers/export.py
A bug was found, where transformers onnx export with a one shot recipe (with quantization) would fail cause model was in eval mode.
This PR patches that by applying one shot before setting model.eval(); the exports were verified manually to work after that
> [Bug-fix] one-shot recipe should be applied in train mode

- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
torch 1.12 exports some Q/DQ inputs as initializers now instead of constants - this causes a pass in the quantized graph conversion step to miss a conversion from INT8 to UINT8. this PR adds an explicit pass to convert any missed INT8 to UINT8 initializers. without this fix, models may fail on ORT and deepsparse compile due to a mismatch between INT8 and UINT8 inputs
**test_plan:**
@KSGulin has reproduced the error to verify fix and commandeer
need to verify compilation + accuracy
> [bug-fix] enforce all converted quantized ONNX initializers are same dtype

- src/sparseml/openpifpaf/README.md
- src/sparseml/openpifpaf/export_onnx.py
- src/sparseml/openpifpaf/train.py
The main differences from the builtin openpifpaf export script are:
1. Using our ModuleExporter
2. Adding dataset arguments to cli so the correct model structure is exported (builtin one assumes cocokp)
Test plan:
1. Ran export command with a checkpoint from training
2. Ran deepsparse.benchmark on the resulting .onnx file
> Adding export script for openpifpaf

- src/sparseml/pytorch/sparsification/quantization/__init__.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_quantize.py
a core feature of the QuantizationModifier refactor is the ability for users to have both more simple and more fine grained control over how quantization is applied at large and in small pieces of the model.  To support this, this PR introduces two simple pydantic models that can be used to define how a particular layer's inputs, weights, and outputs are quantized
intended use:
`QuantizationArgs` defines how quantization should be applied for a particular component via `num_bits`, `symmetric` and optional kwargs that map to pytorch quantization `Observer` args.
`QuantizationScheme` builds on `QuantizationArgs` to allow for args to be set separately for inputs, weights, and outputs. If any of these values are set to None, that particular component of the layer will not be quantized.
helper …
> [QuantizationModifier] pydantic classes for defining quantization schemes to generate QConfigs

- src/sparseml/transformers/export.py
- src/sparseml/transformers/sparsification/trainer.py
This PR adds support to generate fake sample inputs/outputs based on the model shape if no `data_args` are supplied
supplied in export script. Also fixes the issue #1179 
The test model was downloaded as follows:
```bash
sparsezoo.download \
"zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned95_obs_quant-none" \ 
--save-dir ~/qa_model
```
Before this PR:
```bash
sparseml.transformers.export_onnx --task qa \
--model_path /home/XXXX/qa_model/training \
--num_export_samples 20
```
An error was raised
```bash
(sparseml3.8) 🥃 sparseml sparseml.transformers.export_onnx --task qa --model_path /home/XXXX/qa_model/training --num_export_samples 20
File "/home/XXXX/virtual_environments/sparseml3.8/bin/sparseml.transformers.export_onnx", line 8, …
```
> Support to Generate Fake Sample/Inputs 

- src/sparseml/pytorch/sparsification/quantization/helpers.py
- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_helpers.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
Adds support for a basic quantization flow in the updated `QuantizationModifier`. as of this PR, we will still follow torch `propagate_qconfig` and default to quantizing the entire module
Importantly, sets up helper functions that follow the `QuantizationScheme` arguments
**test_plan:**
* yaml serialization test included
* lifecycle testing + assertions around proper QAT application
> [WIP][QuantizationModifier] base refactor flow - quantize entire module from QuantizationScheme

- src/sparseml/pytorch/utils/helpers.py
If you run the transfer learning command from here https://sparsezoo.neuralmagic.com/models/cv%2Fclassification%2Fresnet_v1-50%2Fpytorch%2Fsparseml%2Fimagenet%2Fpruned95-none, the model.ckpt.pth file is missing, so you will get a value error raised even though the model.pth file exists.
This PR just falls back to model.pth if model.ckpt.pth is missing.
Testing plan:
1. ran training command above to verify crash
2. ran same training command after fix to verify training started
> Falling back to model.pth if model.ckpt.pth is missing

- src/sparseml/transformers/export.py
- src/sparseml/transformers/sparsification/trainer.py
* Support to Generate Fake Sample/Inputs and outputs if no `--data_args` supplied in export script
* Address all review comments Simplify call to `_get_fake_inputs`
Save inputs/outputs to `sample-inputs`/`sample-outputs`
> [cherry-pick]Support to Generate Fake Sample/Inputs  (#1180)

- src/sparseml/pytorch/sparsification/quantization/__init__.py
- src/sparseml/pytorch/sparsification/quantization/constants.py
- src/sparseml/pytorch/sparsification/quantization/helpers.py
- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
- tests/sparseml/pytorch/sparsification/quantization/test_quantize.py
this PR adds the following functionality and improvements:
core:
* quantization modifier now fully controls propagation of schemes and qconfigs by having its own function for selecting which submodules get a quantization_scheme, then only adding qconfigs to submodules with schemes
* modifier now by default targets all (minus a hardcoded list of 'non' quantizable modules) leaf submodules for quantization
improvements:
* testing fixes
* testing includes check that observers are actually created
* quantization flow in modifier improved to just set schemes -> apply qat from schemes
**test_plan:**
unit tests included
> [QuantizationModifier] improved quantization flow - control of propagation with schemes and stronger testing

- src/sparseml/pytorch/sparsification/quantization/constants.py
- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
this PR adds `exclude_module_types` modifier param to the QuantizationModifier
after this change, all leaf and fused module types will be targeted for quantization by default, however class names included in the param will be ignored.
additional inclusions:
* updates `is_quantizable_module` to mark modules that have already been updated for quantization as quantizable (they will have qat helper modules for children)
* updates testing flow to now explicitly test for quantization in all target submodules and checks that it is not applied to non targets
**test_plan:**
unit tests updated to strictly test against modifier targets
> [QuantizationModifier] exclude_module_types implementation

- src/sparseml/transformers/sparsification/trainer.py
Removing `typing.Final` was added after Python 3.8 and causes QA tests to fail
> [Fix] Remove `typing.Final`

- src/sparseml/pytorch/torchvision/train.py
This fixes a couple things:
1. Renames checkpoint_recipe -> recipe to be consistent with old checkpoints
2. Optionally get epoch from checkpoint
3. Removes calls to apply_structure with checkpoint since ModelRegistry/load_model does that already
4. Makes `--recipe` optional 
ran this command successfully
```bash
sparseml.image_classification.train --test-only --dataset-path ../.cache/nm_datasets/imagenette/imagenette-160 --arch-key resnet50 --checkpoint-path zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/channel30_pruned90_quant-none
```
> Torchvision eval fixes

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
`module_type_schemes` allows a user to override quantization schemes by matching layer class names (ie `Linear`, `Conv2d`)
this replaces arguments in the existing quantization modifier that handle specific layer types (ie conv/linear activations, embeddings, etc)
**test_plan:**:
unit tests updated for:
* yaml serialization
* check the correct scheme is set when there is a module_type_schemes match
> [QuantizationModifier] module_type_schemes - override quantization scheme by layer type

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
- tests/sparseml/pytorch/sparsification/quantization/test_quantize.py
adds support for `deepsparse` and `tensorrt` as target hardware deployments by adding  `QuantizationScheme` aliases for them.
this was done instead of having an explicit target_harware argument to avoid requiring an extra argument. the aliases be set either as the default scheme and/or in the dict overrides
**test_plan**:
unit tests added/updated for:
* using target hardware with the modifier
* `QuantizationModifier.load` returns the correct scheme based on the alias
> [QuantizationModifier] target hardware support

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
- tests/sparseml/pytorch/sparsification/quantization/test_quantize.py
ports the model fuse function overrides from the legacy modifier
adds a `target_hardware` field to `QuantizationScheme` for tracking and serialization of platform dependent changes
**test_plan:**
* changes pass unit tests
* yaml tests updated
> [QuantizationModifier] override params for model fuse step

- Makefile
Our set of integration tests take ~10 minutes to run on GHA. This can add up to a significant amount of waiting time when bug hunting. This PR updates the integration test command to stop after the first error is encountered to be able to cycle on fixes faster
> Stop integration tests on first failure

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
adds support to log:
* number of fake quantize ops injected
* status of bn/observer freezing
* number of bits of each fake quantize op w/ name
**test_plan:**
manually verified:
quantization flow:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
from sparseml.pytorch.models import resnet18
from sparseml.pytorch.optim import ScheduledModifierManager
from sparseml.pytorch.sparsification import QuantizationModifier
from sparseml.pytorch.utils import PythonLogger, LoggerManager
model = resnet18()
manager = ScheduledModifierManager([QuantizationModifier(start_epoch=1.0)])
manager.initialize(model, epoch=0, loggers=([PythonLogger()]))
manager.update(model, None, 1.0, 1)
```
resulting log file:
```
python QuantizationModifier/num_fake_quantize_global [0 - 1670537974.3711507]: 0 …
```
> [QuantizationModifier] logging support

- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
This PR cleans up the UX with the following effects:
* `default_scheme` renamed to `scheme`
* `submodule_schemes` and `module_type_schemes` unified into `scheme_overrides`
* `exclude_module_types` renamed to `ignore`
* `ignore` also includes the ability to specify submodule names to skip
* all submodules will now be targeted unless included in `ignore` (previously, if `submodule_schemes` was set, then only those submodules would be targeted)
helper functions were migrated first with intermediate testing to ensure that existing functionality remained in-tact
**test_plan:**
* unit tests updated to test for new functionality
* existing unit tests pass
* yaml test updated
> [QuantizationModifier] UX refactor - submodule_overrides and ignore

- src/sparseml/pytorch/sparsification/modifier.py
- src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
strict by default adds a check that the all overrides and ignores given by the user are actually found in the module. meant to catch any config errors earlier rather than later but gives user the option to turn off
**test_plan:**
* yaml test updated
* existing tests now passing under strict (found and fixed one issue)
* test added to check for expected errors
> [QuantizationModifier] strict mode - raise if unmatched submodules or types

- src/sparseml/onnx/utils/helpers.py
This was causing long debug/test failures because it was printing the whole onnx model to stdout.
> [Exporter Refactor] Don't print onnx models on failure

- src/sparseml/exporters/transforms/remove_duplicate_qconv_weights.py
The grouping logic may compare weights of different sizes, so there was a warning before about this
> [Exporter Refactor] Fix duplicate qconv

- src/sparseml/exporters/transforms/conv_to_qlinearconv.py
- src/sparseml/exporters/transforms/gemm_to_qlinearmatmul.py
Old logic allowed QuantizeLinear OR DequantizeLinear as parent[0]. This moves logic to match that.
> [Exporter Refactor] Fixing matching logic of qlinear transforms

- src/sparseml/pytorch/recipe_template/main.py
- src/sparseml/pytorch/sparsification/quantization/quantize.py
- tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
this PR addresses three issues found in testing of the new `QuantizationModifier`:
1. addresses an break in recipe template tests
2. uses `FakeQuantizeBase` for inheritance comparisons where possible (introduced as default in later versions of torch)
3. torch 1.9 tests revealed that torch quantization will inject its own activation post process hooks into certain activations without any way to disable. this PR adds its own implementation of add observers that does not include this override. (fixes issues with quantization of `Sigmoid` and other activations)
4. previously, the new modifier still deferred to torch for quantization of output activations - this was a known hole as we try to quantize "everything" while torch mostly keeps to a white-list. as part of the activation fix in (3), …
> [QuantizationModifier] take ownership of add_observers_, unit test fixes

- src/sparseml/exporters/transforms/utils/matching.py
- tests/sparseml/exporters/transforms/utils/test_matching.py
See docstring and tests for example.
Test plan: unit tests & I used this in some of the passes (will be in separate PRs) and they all passed their unit tests
> [Exporter Refactor] Adding `any_of` for get_structural_matches and MatchResult to str

- src/sparseml/exporters/transforms/constants_to_initializers.py
- src/sparseml/exporters/transforms/delete_repeated_qdq.py
- src/sparseml/exporters/transforms/delete_trivial_onnx_adds.py
- src/sparseml/exporters/transforms/fold_conv_div_bn.py
- src/sparseml/exporters/transforms/fold_identity_initializers.py
- src/sparseml/exporters/transforms/fold_relu_quants.py
- src/sparseml/exporters/transforms/quantize_residuals.py
- src/sparseml/exporters/transforms/remove_duplicate_quantize_ops.py
- tests/sparseml/exporters/transforms/test_delete_trivial_onnx_adds.py
- tests/sparseml/exporters/transforms/test_fold_conv_div_bn.py
Depends on #1263 
This:
- Uses the delete_node_deferred from #1263
- Adds logging to all the passes
- Standardizes the docstring format
> [Exporter Refactor] Standardize non core transforms

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_magnitude.py
Fixes https://github.com/neuralmagic/sparseml/issues/1282 by passing the missed `inter_func` argument to super.
> Fix sparsity scheduler for GMP

- src/sparseml/onnx/utils/graph_optimizer.py
simple change to allow loaded onnx models to be passed directly to `fold_conv_bns`.
this is required for support in on-going ONNX one-shot work
**test_plan:**
manual with related test coverage in separate repo
> [onnx.utils] fold_conv_bns in-memory ModelProto support

- src/sparseml/transformers/__init__.py
Name of package was changed. Other places in the repo have already been updated
> Use scikit-learn instead of sklearn

- src/sparseml/pytorch/torchvision/train.py
- src/sparseml/pytorch/torchvision/utils.py
This enables tensorboard logging support. Here is a pic of all the metrics logged so far (in addition to the Manager ones):
> Adding LoggerManager to torchvision train script

- src/sparseml/pytorch/torchvision/train.py
Adds missing feature that the old training script had.
1. Ran command in readme
2. Ran command in readme + `--recipe-args '{"num_epochs": 5}'`
> Adding --recipe-args to torchvision train script

- src/sparseml/pytorch/torchvision/train.py
- src/sparseml/pytorch/torchvision/utils.py
* Adding LoggerManager to torchvision train script
* Quality
Co-authored-by: Alexandre Marques <alexandre@neuralmagic.com>
> [Cherry Pick] Adding LoggerManager to torchvision train script (#1299)

- src/sparseml/pytorch/sparsification/quantization/quantize.py
this PR fixes a small bug in the quantization modifier when accessing module `parameters` generator of a module that has no parameters.
issue scope is very small as this is an unlikely scenario, but came up in testing of a singular QATMatMul (non parameterized)
**test_plan:**
covered offline by NM QA team
> [QuantizationModifier][patch] default to CPU when module has no device

- src/sparseml/pytorch/sparsification/quantization/helpers.py
Currently only the following hooks are transferred during quantization fusing process:
1. the pre forward hooks for the first layer
2. the post forward hooks for the last layer
Notably, the following hooks are lost:
1. The post forward hooks in the first layer
2. The pre forward hooks in the last layer
3. Any hooks from any layer between first and last layer
This PR changes it so all pre/post hooks from every layer in the fused block is transferred to the new fused module.
Existing unit tests, and also this was tested for the #1272 PR
> Saving all hooks during quantization block fusing

- src/sparseml/pytorch/sparsification/distillation/__init__.py
- src/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py
- src/sparseml/pytorch/sparsification/distillation/modifier_per_layer.py
- tests/sparseml/pytorch/sparsification/distillation/test_per_layer_distillation.py
This PR represents the main branch for all layer-wise distillation work
> Layer-Wise Distillation

- src/sparseml/pytorch/sparsification/quantization/quantize.py
- src/sparseml/pytorch/torchvision/train.py
- Currently torchvision logs scalars with a step unit of epoch #. All other modifiers use batch # as unit for step, which causes charts not to be displayed in WANDB. This changes the step unit to match for modifiers.
- Fixing bug where using `--gradient-accum-steps` did not adjust `steps_per_epoch` passed to manager
- Also renaming `--print-freq` -> `--logging-steps` and properly using everywhere.
Tested this command:
```bash
sparseml.image_classification.train --checkpoint-path zoo:cv/classification/efficientnet_v2-s/pytorch/sparseml/imagenet/base-none --arch-key efficientnet_v2_s --output-dir efficientnet-tmp/ --recipe dense_finetune.yaml --dataset-path /home/corey/.cache/nm_datasets/imagenette/imagenette-160/ --batch-size 4 --gradient-accum-steps 4 --auto-augment imagenet …
```
> Changing log_scalar step unit to batch # instead of epoch

- src/sparseml/pytorch/torchvision/train.py
The goal of this PR is to add distillation support to our `pytorch/torchvision` integration
Test recipe:
`distillation.yaml`:
```yaml
num_epochs: &num_epochs 10
lr: &lr 0.008
start_epoch: 0.0
end_epoch: *num_epochs
- !SetLearningRateModifier
start_epoch: 0.0
learning_rate: *lr
- !DistillationModifier
start_epoch: 0.0
hardness: 0.5
temperature: 2.0
distill_output_keys: [0]
```
Test commands, (run manually):
```bash
sparseml.image_classification.train \ 
--recipe distillation.yaml --pretrained True --pretrained-dataset imagenette \
--arch-key resnet50 --dataset-path /home/rahul/datasets/imagenette/imagenette-160 \
--batch-size 128 --opt SGD --output-dir ./training-runs/image_classification-pretrained \
--distill-teacher self
```
```bash …
```
> Distillation support for torchvision script

- src/sparseml/pytorch/torchvision/export_onnx.py
Testing plan:
1. Ran command in readme after training
2. Same command, with `--one-shot zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none` added, and confirmed quantization stuff was run
> Adding --one-shot argument to torchvision export

- tests/sparseml/onnx/optim/test_sensitivity_ks.py
This is attempting to fix a bug in python 3.9 where the `test_one_shot_ks_perf_sensitivity` is failing.
Two notes:
1. I could not reproduce this failure locally
2. These test pass in python 3.7/3.8/3.10 jenkins pipelines.
**So the only failure is in jenkins pipeline on python 3.9.**
My current hypothesis is that the results returned by model analysis can have multiple values where the `x["index"]` is the same:
This *could* make the `sorted` call be inconsistently ordering the actual results.
Another piece of information supporting this hypothesis is the error messages of the 2 failures:
failure 1:
```
expected_layers = [{'averages': OrderedDict([(0.0, 3.500000000000001e-05), (0.4, 3.2000000000000005e-05), (0.8, 3.300000000000001e-05), ...'baseline_average': 7.089999999999999e-05, …
```
> Attempting to fix onnx tests

- src/sparseml/pytorch/torchvision/train.py
1. If args.recipe is a local file path, it will appear under the files section of wandb:
2. In the overview tab you can now view all command line parameters in the config table
> Adding config to wandb logger and calling LoggerManager.save(recipe)

- src/sparseml/pytorch/utils/model.py
A bug was recently found by @natuan, in which onnx exports for quantized image classification models were failing when the checkpoint epoch was -1
This PR fixes that, by setting epoch to `float("inf")`  when the checkpoint epoch is -1
Test:
```bash
sparseml.image_classification.export_onnx \
--arch-key efficientnet_v2_s \
--checkpoint-path /home/rahul/tuan-efficient/checkpoint.pth
--dataset-path /home/rahul/datasets/imagenette/imagenette-160 \
--save-dir /home/rahul/tuan-efficient/exported
```
This command was failing before but now produces the correct onnx with the following contents:
```bash
.
├── deployment
│   ├── config.json
│   └── model.onnx
├── efficientnet_v2_s_imagenette
├── efficientnet_v2_s_imagenette__01
├── efficientnet_v2_s_imagenette__02
├── …
```
> [BugFix] image-classifiication onnx export

- src/sparseml/pytorch/image_classification/utils/trainer.py
There is a GPU synchronisation error that occurs after an image classification training runs to completion in Kubeflow DDP 
"""
ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
what():  NCCL error: unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Fatal Python error: Aborted
"""
This PR fixes the GPU synchronisation error by making sure that the image classification validation (post training) that runs only on the rank 0 GPU uses the local (rank 0) copy of the …
> GPU Synchronisation bug

- src/sparseml/pytorch/torchvision/train.py
Fixes the bug `AttributeError: Can't pickle local object '_create_cache_output_hook.<locals>.forward_hook_fn'` with distillation.
This occurred because `args` are pickled in the checkpoint, and the whole distillation teacher model was being put into `args`. Moved it to a local variable instead.
Ran training for 1 epoch with recipe from asana ticket and verified save after fix.
> Removing distill_teacher model from args

- src/sparseml/pytorch/torchvision/train.py
This should not reverse, but just fix: https://github.com/neuralmagic/sparseml/pull/1338
> Fix referenced before assignment error

- src/sparseml/exporters/transforms/gemm_to_qlinearmatmul.py
When there is a Softmax after a MatMul, this pass improperly assumes the Q/Dq is for itself, rather than for the softmax.
Note that this is invalid!!
> Ignoring Gemm -> Q/Dq -> Softmax in GemmToQLinearMatMul transform

- src/sparseml/pytorch/torchvision/train.py
Feature request was for any arguments passed via `--recipe-args` to be reflected in saved file in wandb.
This PR does the following:
1. Always saves a file for recipe, regardless of if args.recipe is a zoo stub or actual file
2. Saves the original unmodified/unsubstituted recipe as `{args.output_dir}/original_recipe.yaml`
3. Saves final recipe with variables from `--recipe-args` and other variables substituted as `{args.output_dir}/final_recipe.yaml`
Example in wandb:
Tested with command from README with both no recipe-args and recipe-args specified.
> Saving both original and final recipes in torchvision train script

- src/sparseml/pytorch/torchvision/train.py
Commit c7cf6b610acc49d30c996a122a205499bf27f747, changed _create_model to return a tuple, however the distillation call to this function was not updated, leading to errors about invalid values for teachers.
Reproduction:
```
sparseml.image_classification.train --distill-teacher zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none --teacher-arch-key resnet-50 --recipe sparse-efficientnet.yaml --dataset-path ~/.cache/nm_datasets/imagenette/imagenette-320/ --arch-key resnet50
```
with recipe
```yaml
version: 1.1.0
num_epochs: 5
final_finetune_epochs: 0.1
qat_start_epoch: 0.0
init_lr: 2e-4
min_lr: 1e-8
weight_decay: 0.00001
qat_disable_observer_epoch: eval(num_epochs - final_finetune_epochs)
qat_freeze_bn_epoch: eval(num_epochs - final_finetune_epochs)
distill_gain: 1.0 …
```
> Fixing return argument of _create_model for distillation

- src/sparseml/pytorch/torchvision/train.py
[torch] introduced [label_smoothing] argument for [CrossEntropyLoss]
in version `1.10` and greater. Using this parameter in earlier versions  of 
[torch] leads to a `TypeError`
As of now in our torchvision training integration we do not make this 
distinction(rather we always use label_smoothing) which can cause errors with
lower versions of [torch]
For example on running the following command in an environment with torch 1.9
throws an error
**COMMAND**:
```python
--recipe "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/pruned-conservative?recipe_type=original" \
--checkpoint-path "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/pruned-conservative" \
--dataset-path /XXXX/datasets/imagenette-160
``` …
> Bugfix: use label smoothing only when torch version is >= 1.10

- src/sparseml/pytorch/torchvision/train.py
As of now, our [torchvision integration] has a bug, where during 
[Sparse Transfer Learning] the number of output classes can be
mismatched b/w `saved optimizer state_dict(from pretraining)` and the
`re-created optimizer(when starting finetuning)`
This leads to broken flows and errors whenever there is a mismatch in the 
number of output classes b/w upstream and downstream datasets
For example:
Sparse Transfer Learning a resnet50 model originally trained on [ImageNet] to 
[Imagenette]
**COMMAND**:
```bash
--recipe "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none?recipe_type=transfer-classification" \
--checkpoint-path "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none" \ …
```
> [BugFix][Torchvision] update optimizer state dict before transfer learning 

- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
Logic for converting signed to unsigned initializers was editing the initializer list inside a loop. Replaced by 2 stages: first create new initializers and the ones to remove, then edit the initializer list.
> Fix editing a list inside a loop

- research/optimal_BERT_surgeon_oBERT/README.md
- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
As suggested in the MLR meeting, this is updated and extended version of docs for the OBSPruningModifier which covers the most important notes needed to quickly start pruning new models with it. 
It contains FAQ section which provides memory and time complexity for the pruning step, some notes on finding the optimal set of hyper-params for any model, and some additional tricks for better results.
> Improve OBSPruningModifier docs

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
This PR adds better defaults for most users in the OBSPruningModifier:
- sets `fisher_block_size` to `1`, which has memory overhead as the standard magnitude pruning, but should in general provide better results
- sets `MEMORY_BOUNDED` env variable to `True` for memory-safe pytorch ops, which would usually break when sorting large tensors
> Add memory-safe defaults for OBS

- src/sparseml/pytorch/sparsification/pruning/scorer.py
Fixes https://github.com/neuralmagic/sparseml/issues/1349 by extending the default timeout from 30 mins to 2 hours, which should be enough to cover collecting a large number of gradients for most of the models we work with.
> Extend DDP collective ops timeout

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
Fixes https://github.com/neuralmagic/sparseml/issues/1347 by replacing `.view` calls with more robust `.reshape`.
> Use more robust reshape instead of view

- MANIFEST.in
- setup.py
- src/sparseml/pytorch/yolov8/__init__.py
- src/sparseml/pytorch/yolov8/default.yaml
- src/sparseml/pytorch/yolov8/train.py
- src/sparseml/pytorch/yolov8/trainers.py
Adds yolov8 training script to the repo.
```yaml
version: 1.1.0
start_epoch: 0
end_epoch: 15
- !GMPruningModifier
init_sparsity: 0.05
final_sparsity: 0.10
start_epoch: 5.0
end_epoch: 10.0
update_frequency: 1.0
params: ["model.0.conv.weight", "model.1.conv.weight"]
quantization_modifiers:
start_epoch: 11.0
freeze_bn_stats_epoch: 12.0
disable_quantization_observer_epoch: 13.0
ignore: ["Upsample", "Concat", "SiLU"]
```
There are two parts to this:
1. the DFL final layer in the yolo models are detached (they do not require grads). Therefore, the pruner must ignore them as this currently crashes (see potential fix in #1329).
2. Due to ultralytics adding special attributes to top layer modules of the model, we …
> [Feature Branch] Yolov8

- setup.py
* adds `torch_all` extra dependency which includes torch{audio,text,vision}
* removes `tensorboard` as a torch dependency since it is an optional install for torch logging and may cause version conflicts for users with existing dependencies
* moves the tensorboard deps to dev deps to unblock GHA testing
**test_plan:**
@rahul-tuli verified a fresh environment with a few intentionally adversarial preinstalled dependencies (newer tensorflow version, older flask version, older click version) was able to install a fresh build of `sparseml[torch_all]` and kick off an IC training run
> install extra option for torch_all

- setup.py
strict click dependency has caused issues with users who's environments pin click to less than version 8. this PR allows for enablement of click<8.0 by allowing the latest non 8.0 version only. The maximum version was also lifted as the previous restriction was to avoid installing 8.0.0, a version that had reported issues working with wandb.
*test_plan:**
Click is used only by our main entrypoint CLIs which will be in scope for manual/automated QA testing in the 1.5 release as well as any integration tests
> relax click dependency

- src/sparseml/pytorch/torchvision/train.py
This PR adds support for DataParallel in sparseml's torchvision integration, if no devices are specified, all devices are used by default, else devices can be specified as "cuda:0,1,2,3"
The bug w.r.t multi-gpu environments occurred because the device info wasn't propagated correctly after wrapping the model in DataParallel
The bug has been fixed and the following command was run in a multi-gpu setup to verify all GPU's were picked up; manually verified GPU usage
```
--recipe "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none?recipe_type=transfer-classification" --checkpoint-path "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none" --arch-key resnet50 --dataset-path …
```
> `DataParallel` support for `torchvision`

- src/sparseml/pytorch/utils/logger.py
More verbose error message instructing the user to install wandb. Fix for https://app.asana.com/0/1201735099598270/1203877616112261/f
```bash
File "/home/ubuntu/damian/sparseml/src/sparseml/pytorch/utils/logger.py", line 41, in <module>
import wandb
ModuleNotFoundError: No module named 'wandb'
The above exception was the direct cause of the following exception:
File "/home/ubuntu/damian/sparseml/src/sparseml/transformers/text_classification.py", line 55, in <module>
from sparseml.pytorch.utils.distributed import record
File "/home/ubuntu/damian/sparseml/src/sparseml/pytorch/__init__.py", line 51, in <module>
from .framework import detect_framework, framework_info, is_supported
File …
```
> [Fix] Add more verbose`wandb` import error

- setup.py
- src/sparseml/pytorch/yolov8/trainers.py
- src/sparseml/pytorch/yolov8/val.py
- src/sparseml/pytorch/yolov8/validators.py
Adds support for validating quantized models by adding sparseml.ultralytics.val entry point.
```sparseml.ultralytics.val --model https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt```
Outputs:
```bash
Found https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt locally at yolov8n.pt
Ultralytics YOLOv8.0.11 🚀 Python-3.9.5 torch-1.12.1+cu113 CUDA:0 (NVIDIA RTX A4000, 16117MiB)
val: Scanning /home/corey/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:01<00:00,  4.59it/s]
all        128        929       0.64      0.537      0.605      0.446
```
```sparseml.ultralytics.train --model …
```
> Adding `sparseml.ultralytics.val` script

- Makefile
- status/integration_status.py
- status/status_template.status.yaml
Ports status page and table from #1290 into `FeatureStatusPage` and `FeatureStatusTable` schemas.  Includes script harness for generating markdown status pages from yaml configs, aggregated status page, and template. Aggregated page and template written to `status/`, individual pages written next to their yaml configs nested in `src/`
the template yaml file is auto generated from the schemas by running `status/integration_status.py`
**test_plan:**
manually check generated `status_template.status.yaml`
> [integration-standardization] status table and page schemas + sweep script + template

- src/sparseml/yolov8/__init__.py
Tested by installing newer version of yolov8 and running sparseml.ultralytics.train/export/val --help and verified there was an error.
Then install 8.0.30 and verified no error
> Adding version guard to yolov8

- src/sparseml/yolov8/utils/export_samples.py
Fix for: https://app.asana.com/0/1203126676641557/1204007135425947
Reason: Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession.
> [Fix] Explicitly set the providers parameter when instantiating InferenceSession

- src/sparseml/transformers/token_classification.py
Fix for: https://app.asana.com/0/1203126676641557/1204066771103852/f
Testing:
Rerunning the procedure described here: https://colab.research.google.com/drive/1WuWJMYY-_S-JP711bLYSRxBbcb66X1ft
Now, however, I see convergence:
```bash
... lost the upper part of the stack trace
{'eval_loss': 1.1685093641281128, 'eval_precision': 0.9192755805659032, 'eval_recall': 0.9153037267938524, 'eval_f1': 0.9172853541594583, 'eval_accuracy': 0.9135547681165064, 'eval_runtime': 45.5854, 'eval_samples_per_second': 71.295, 'eval_steps_per_second': 0.57, 'epoch': 10.0}
{'eval_loss': 1.1096463203430176, 'eval_precision': 0.9248782427194115, 'eval_recall': 0.9179079448379269, 'eval_f1': 0.9213799112801014, 'eval_accuracy': 0.9186947548771466, 'eval_runtime': 20.9074, 'eval_samples_per_second': 155.447, …
```
> [Fix] Fix divergence between student and teacher label mapping

- Makefile
- src/sparseml/openpifpaf/openpifpaf.status.md
- src/sparseml/openpifpaf/openpifpaf.status.yaml
- src/sparseml/pytorch/image_classification/nm_image_classification.status.md
- src/sparseml/pytorch/image_classification/nm_image_classification.status.yaml
- src/sparseml/pytorch/torchvision/torchvision.status.md
- src/sparseml/pytorch/torchvision/torchvision.status.yaml
- src/sparseml/transformers/transformers.status.md
- src/sparseml/transformers/transformers.status.yaml
- src/sparseml/yolov5/yolov5.status.md
- src/sparseml/yolov5/yolov5.status.yaml
- status/README.md
- status/STATUS.MD
- status/integration_status.py
- status/status_template.status.yaml
Support for creating and maintaining integration and repo level feature status tables using tooling added by https://github.com/neuralmagic/sparsezoo/pull/255
Contributors will maintain `.status.yaml` files in `src/` at the integration directory level and run `status/integration_status.py` to generate/update the markdown status tables from them
see auto generated markdown files to see end result
**tasks:**
**test_plan:**
Manual inspection of auto generated files
> Integration Standardization Tables

- src/sparseml/transformers/token_classification.py
Fix for: https://app.asana.com/0/1204070232568744/1204101088568500/f
Testing:
Rerunning the procedure described here and ensuring convergence: https://colab.research.google.com/drive/1WuWJMYY-_S-JP711bLYSRxBbcb66X1ft
Rerunning the following example and ensuring there isn't a crash:
```
sparseml.transformers.train.token_classification \
--model_name_or_path zoo:nlp/masked_language_modeling/obert-base/pytorch/huggingface/wikipedia_bookcorpus/pruned90-none \
--recipe zoo:nlp/token_classification/obert-base/pytorch/huggingface/conll2003/pruned90_quant-none \
--distill_teacher zoo:nlp/token_classification/obert-base/pytorch/huggingface/conll2003/base-none \
--dataset_name conll2003 \
--output_dir sparse_bert-token_classification_conll2003 \
--per_device_train_batch_size 32 …
```
> [Fix] label_list not being set for NLP token classification training if distillation teacher and student labels do not match

- src/sparseml/transformers/token_classification.py
* [Fix] Fix label_list not being set for NLP token classification training if distillation teacher and student labels do not match
* Added two fixes: omitting the labels/indices matching for student/teacher if teacher is a string; prioritizing teacher labels to student labels if teacher labels are string and student's int
* revert previous int label patch - allow int labels to let given dataset be the source of truth
* only override label_list when teacher and student labels sets are equal
---------
> [Fix] label_list not being set for NLP token classification training if distillation teacher and student labels do not match (#1414)

- src/sparseml/yolov8/export.py
- src/sparseml/yolov8/trainers.py
```bash
sparseml.ultralytics.export --model yolov8.pt --one-shot recipe.yaml --save-one-shot-torch True
```
Result
```bash
....
Source: 'sparseml' detected; Exporting model from SparseML checkpoint...
Detected one-shot recipe: hehe.yaml. Applying it to the model to be exported...
Saving one-shot torch model to DetectionModel.pt...
...
```
Resulting `export` folder
.
├── deployment
│   ├── config.json
│   ├── DetectionModel.onnx
│   ├── recipe.yaml
│   ├── sample_inputs
│   │   ├── inp-0000.npz
│   │   ├── inp-0001.npz
│   │   ├── inp-0002.npz
│   │   ├── inp-0003.npz
│   │   ├── inp-0004.npz
...
│   ├── sample_outputs_onnxruntime
│   │   ├── out-0000.npz
│   │   ├── out-0001.npz
│   │   ├── out-0002.npz
│   │   ├── out-0003.npz
│   │   ├── out-0004.npz
...
│   └── sample_outputs_torch
│   …
> [YOLOv8] Add flag to save pt models with one-shot applied during export

- src/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py
Expected  Behaviour:
During distillation if the teacher and student outputs differ in shapes an 
appropriate error message should be displayed and the running program must exit
Current Status:
During distillation if the teacher and student outputs differ in shapes
no warning is displayed, this eventually causes an error down the line, 
which is not very intuitive and does not describe what went wrong.
This PR fixes that.
Command with mis-matching teacher/student:
```bash
sparseml.transformers.train.token_classification \
--model_name_or_path zoo:nlp/masked_language_modeling/obert-base/pytorch/huggingface/wikipedia_bookcorpus/pruned90-none \
--recipe zoo:nlp/token_classification/obert-base/pytorch/huggingface/conll2003/pruned90_quant-none \
--distill_teacher …
```
> Better Error Message for distillation

- src/sparseml/yolov8/utils/export_samples.py
Make onnxruntime optional, allows invoking  --help command without error
Before this PR:
```bash
(venv) 🥃 sparseml sparseml.ultralytics.train --help
File "/home/rahul/venv/bin/sparseml.ultralytics.train", line 5, in <module>
from sparseml.yolov8.train import main
File "/home/rahul/venv/lib/python3.8/site-packages/sparseml/yolov8/train.py", line 16, in <module>
from sparseml.yolov8.trainers import SparseYOLO
File "/home/rahul/venv/lib/python3.8/site-packages/sparseml/yolov8/trainers.py", line 34, in <module>
from sparseml.yolov8.utils.export_samples import export_sample_inputs_outputs
File "/home/rahul/venv/lib/python3.8/site-packages/sparseml/yolov8/utils/__init__.py", line 15, in <module>
from .export_samples import *
File …
```
> [BugFix] Make onnxruntime optional for `sparseml.ultralytics.train --help`

- src/sparseml/pytorch/torchvision/train.py
tensorboard is now an optional dependency and the logger should only be instantiated during torchvision training if it is present. this patch catches the error and raises a warning
**test_plan:**
manually verified for example command:
```bash
sparseml.image_classification.train     --recipe "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/pruned-conservative?recipe_type=original"     --dataset-path /home/data/imagenette/imagenette-320     --pretrained True     --arch-key resnet50     --batch-size 128     --workers 8     --output-dir sparsification_example/resnet50-imagenette-pruned     --save-best-after 8
Not using distributed mode
```
warnings before training:
```bash
sparseml/src/sparseml/pytorch/torchvision/train.py:585: UserWarning: Unable to import tensorboard for …
```
> [torchvision IC] catch import error for instantiation of optional tensorboard logger

- src/sparseml/yolov8/validators.py
This doesn't fix the validation differences, but I think we should be doing this regardless.
Reasoning:
Currently, the validator will always use the ema model `trainer.ema.ema`, even if ema is disabled. This means when we disable it for sparsifying/quantizing, we aren't validating with the actual model.
We could wrap it in an `if trainer.ema.enabled` guard to optionally still use ema for validation, but this seemed simpler to understand/maintain.
> Always validating model instead of ema

- src/sparseml/yolov8/validators.py
This reverts commit f81312ce56f84945f6412f169cb2c6363684fa70.
reverting #1445 as pointed out by @natuan EMA model when available will yield higher accuracy and is preferred by the base integration
> Revert "Always validating model instead of ema (#1445)"

- src/sparseml/onnx/utils/helpers.py
simple fix to support setting str tensor shapes to the `dim_param` one of attribute of dim in tensor shape.
supports a YOLOv5 patch
> [ONNX] support for setting/getting string onnx tensor shapes

- src/sparseml/pytorch/utils/log_sparsification_info.py
- src/sparseml/pytorch/utils/sparsification_info/configs.py
- src/sparseml/pytorch/utils/sparsification_info/helpers.py
- src/sparseml/pytorch/utils/sparsification_info/module_sparsification_info.py
- tests/sparseml/pytorch/utils/test_sparsification_info/__init__.py
- tests/sparseml/pytorch/utils/test_sparsification_info/test_configs.py
```python
ZOO_STUB = "zoo:cv/classification/resnet_v1-18/pytorch/sparseml/imagenet/pruned-conservative"
QUANT_RECIPE = """
!QuantizationModifier
start_epoch: 0.0
scheme:
input_activations:
num_bits: 8
symmetric: False
weights:
num_bits: 8
symmetric: True
scheme_overrides:
feature_extractor: "default"
classifier:
input_activations:
num_bits: 8
symmetric: False
weights: null
Conv2d:
input_activations:
num_bits: 8
symmetric: True
ignore: ["ReLU", "input"]
disable_quantization_observer_epoch: 2.0
freeze_bn_stats_epoch: 3.0
model_fuse_fn_name: 'fuse_module'
strict: True"""
model = ModelRegistry.create(
key="resnet18",
pretrained_path=ZOO_STUB,
)
manager = ScheduledModifierManager.from_yaml(QUANT_RECIPE)
manager.apply(model)
info = ModuleSparsificationInfo.from_module(model)
param_names = …
```
> [ModuleSparsificationInfo] Proposal of the main logic

- src/sparseml/pytorch/sparsification/training/__init__.py
- src/sparseml/pytorch/sparsification/training/modifier_logging.py
- src/sparseml/pytorch/utils/log_sparsification_info.py
- src/sparseml/pytorch/utils/sparsification_info/__init__.py
- src/sparseml/pytorch/utils/sparsification_info/configs.py
- src/sparseml/pytorch/utils/sparsification_info/helpers.py
- src/sparseml/pytorch/utils/sparsification_info/module_sparsification_info.py
- tests/sparseml/pytorch/sparsification/training/test_modifier_logging.py
- tests/sparseml/pytorch/utils/test_sparsification_info/__init__.py
- tests/sparseml/pytorch/utils/test_sparsification_info/test_configs.py
Adds `SparsificationLoggingModifier`. It can be used in the sparsification recipe to periodically log the information about the sparsification properties of the model (e.g. level of pruning, the precision of parameters, etc).
```bash
sparseml.image_classification.train --dataset imagenette --arch_key mobilenet --recipe-path recipe.yaml --dataset_path . --train_batch_size 64  --test_batch_size 64
```
where `recipe.yaml` is:
```yaml
version: 1.1.0
start_epoch: 0
end_epoch: 4.0
- !SparsificationLoggingModifier
start_epoch: 0.0
end_epoch: 4.0
update_frequency: 2
```
Results in:
```bash
Logging all SparseML modifier-level logs to sparse_logs/28-03-2023_10.31.51.log
python Test/__loss__ Summary [-1 - 1679999514.1273096]: 2.29128360748291
...
python …
```
> SparsificationLoggingModifier implementation

- src/sparseml/pytorch/torchvision/train.py
Replaces inference_mode by no_grad. It prevents setting observer attributes in inference mode, which can't be changed during training afterwards.
Testing plan:
Completed a QAT run on ResNet50 model: https://wandb.ai/neuralmagic/alexandre_debug/workspace?workspace=user-neuralmagic
> Fix for QAT on new IC flow

- src/sparseml/pytorch/sparsification/quantization/legacy_modifier_quantization.py
Remove "module." added by DDP when identifying the submodules for quantization.
Testing plan:
Reproduced the quantization piece of this model:
https://sparsezoo.neuralmagic.com/models/cv%2Fclassification%2Fresnet_v1-50%2Fpytorch%2Fsparseml%2Fimagenet%2Fpruned95_quant-none
Before the fix the quantization was failing
> Fix for legacy quantization modifier w/ DDP

- src/sparseml/yolov8/modules.py
Copy i, f, and type attributes from original layer. These attributes are inserted in the modules when parsing through the model definition and helps keep track of the dependency between layers. W/o that information the model crashes after the layer substitution.
Test: was able to successfully evaluate the model after the fox
> Fix layer substitution for YOLOv8 QAT

- src/sparseml/yolov8/default.yaml
- src/sparseml/yolov8/export.py
- src/sparseml/yolov8/train.py
- src/sparseml/yolov8/val.py
Adds optional `--datasets-dir` flag to train/export/val. If this is specified it overwrites the datsets_dir stored in `~/.config/Ultralytics/settings.yaml`.
Ran `sparseml.ultralytics.train --datasets-dir ~/datasets ...` and confirmed the new datasets directory was in home, and the settings file had changed.
> Adding `--datasets-dir` to yolov8 entrypoints

- src/sparseml/pytorch/utils/helpers.py
- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/helpers.py
- src/sparseml/yolov8/validators.py
The PR enables segmentation evaluation for yolov8 models, which currently fails. It implements a function that extends `detach` to PyTorch expected types ie. list or tuples.
Testing:
- Evaluation works for both detection and segmentation models obtained form either SparseML or ultraltyics
> Fixing yolov8-seg validation

- src/sparseml/yolov8/export.py
- src/sparseml/yolov8/train.py
- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/helpers.py
- src/sparseml/yolov8/val.py
This PR: #1513 was not tested rigorously and was failing for all the pathways. This PR fixes this.
Testing:
- tested validation pathway
- tested export pathway (generating samples and using the data for calculating gradients at one-shot)
- tested training pathway
> [YOLOv8] Fix support for `--dataset_dir` argument

- src/sparseml/yolov8/validators.py
The pycocotools pathway for model validation expects a "Path" object for the data['path'] entry. When the user provides a complete path to a yaml file (or when --dataset-path is provided) this entry remains a string, which leads to an error when doing the pycocotools evaluation.
This is a failure on ultralytics side, but we can fix in the integration since we override the validator class.
Testing plan: The fix allowed me to use "dataset-path" as below:
sparseml.ultralytics.val \
--model zoo:cv/detection/yolov8-n/pytorch/ultralytics/coco/base-none \
--data coco.yaml \
--dataset-path /home/alexandre/datasets/coco
(dataset-path is implemented by 1. copying ultralytics' coco.yaml to the local path, 2. overwriting the dataset path in the yaml file, 3. replacing the data argument with the …
> Fix YOLOv8 validation when custom dataset yaml is provided

- DEVELOPING.md
- docs/source/installation.md
This PR updates old references of python3.6 -> python3.7
> Update: missed instances of python3.6 -> 3.7

- src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
Simple fixes for ONNX export of MobileBERT.
Before the fix, a MatMul in the Embedding section of MobileBERT was not being converted to MatMulInteger, even though the inputs are quantized.
In short, a DequantizeLinear node used as part of the embedding quantization must be propagated down a few Slice and Concat nodes such that it can sit next to the MatMul node. This allows the proper pattern matching to convert that MatMul to MatMulInteger.
This behavior was already present in the onnx export logic, but there is a data type check on the embedding weights and it expected uint8. However, the weights were defined as int8 (conversion to uint8 happens at a later step). This PR adds logic to support int8, and also accounts for non-zero zero-point.
**Testing plan:**
Did the onnx export for the …
> Fix ONNX export for MobileBERT

- src/sparseml/transformers/text_classification.py
This PR fixes a pathway for creating transformers datasets without a need for a model that was missed by #1544
**Test Plan**
Tested locally with the stub `zoo:nlp/text_classification/distilbert-none/pytorch/huggingface/mnli/base-none`
> [Bug-fix] Text classifiation config

- src/sparseml/pytorch/torchvision/train.py
The existing IC flow normalizes the input images using the RGB mean and std values from ImageNet (as is common in many IC flows).
This PR adds arguments that allow the user to override the default values for RGB mean and std. The PR is driven by EficientNetV2-L, which uses different values for the RGB mean and std, but it is a desirable feature in general.
**Testing plan:**
1. Evaluated EfficientNetV2-L overriding RGB mean and std and verified accuracy
```
--checkpoint-path zoo:cv/classification/efficientnet_v2-l/pytorch/sparseml/imagenet/base-none \
--test-only \
--arch-key efficientnet_v2_l \
--dataset-path ~/datasets/imagenet_calib \
--rgb-mean 0.5 0.5 0.5 \
--rgb-std 0.5 0.5 0.5 \
--val-crop-size 480 \
--val-resize-size 480 \
--interpolation …
```
> Add arguments to set RGB mean std for IC

- setup.py
as written, only 0.14.0 would be allowed
> [cherry-pick] allow patch versions of torchvision 0.14 beyond .0 (#1556)

- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/val.py
Loading pretrained yolov8 models from sparsezoo stubs fails for sparseML checkpoints. This PR fixes this issue.
Testing Plan:
Running yolov8 training commands with models from sparsezoo.
> Fix loading Yolov8 sparsezoo models

- src/sparseml/transformers/export.py
- src/sparseml/transformers/utils/model.py
Minimal ONNX export path for LLMs through `sparseml.transformers`.
Testing plan:
- Successfully exported CodeGen, OPT and Bloom on sequence len 1 and 128
- Bloom has been detected to be a large model (larger than protobuf size) and exported accordingly
- Visually expected the resulting ONNX models, they look correct.
> Enable export paths for LLMs [CodeGen, OPT, Bloom]

- .github/workflows/Integrations-post-merge-check.yaml
Cherry Pick: `7c2800982df8ba09f62d1637db63db11b42be9b0`
This Cherry pick was originally missed and was causing post merge integration tests to fail on RC
> [Cherry pick] dependency installation

- src/sparseml/yolov8/trainers.py
This PR fixes a bug in our current yolov8 training flow.
The bug reveals itself when `sparseml.ultralytics.train` utility is invoked without a `recipe`
```bash
(sparsezoo) 🥃 sparseml (main) 💍 sparseml.ultralytics.train --epochs 1
/home/rahul/.venvs/sparsezoo/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Status code 429 from http://ipinfo.io/96.89.198.177/json: ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
Status code 429 from http://ipinfo.io/96.89.198.177/json: ERROR - 429 Client Error: Too Many Requests for url: …
```
> Add trainer to yolov8 validator when calling w/o recipe

- src/sparseml/yolov8/trainers.py
> [Cherry Pick]Add trainer to validator when calling w/o recipe

- src/sparseml/keras/__init__.py
- src/sparseml/tensorflow_v1/__init__.py
- src/sparseml/utils/helpers.py
keras and tensorflow_v1 are no longer tested/supported for future releases. adds a deprecation message on import of these submodules
> add deprecation warnings for keras and tfv1 support

- src/sparseml/pytorch/sparsification/quantization/quantize.py
Removes "module." from submodule names inserted by DDP.
**Test plan:**
Re-quantized the pruned 80% RN50 model with the following quantization modifier:
```
start_epoch: eval(quant_start_epoch)
disable_quantization_observer_epoch: eval(quant_disable_observer_epoch)
freeze_bn_stats_epoch: eval(quant_freeze_bn_epoch)
ignore: ['Softmax', 'classifier']
```
Before this PR the quantization modifier failed to match the "classifier" module name because under DDP this module was renamed as module.classifier
> Fix for quantization modifier w/ DDP

- DEVELOPING.md
- README.md
- docs/source/installation.md
- setup.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
Python 3.7  reaches it's EOL in ~2 weeks https://endoflife.date/python
This PR deprecated our support for the same
> Deprecate Py37

- DEVELOPING.md
Add note for running torch tests
> Update Developing Markdown

- setup.py
- src/sparseml/pytorch/base.py
- Updated max version of `torch` to be 2.0, updated `torchvision` max to be `0.15.1`
- Updated max `torchaudio` to be `2.0.1`
- Tested and passed all `pytorch` tests 
- Tested updated package versions in training using `sparseml.image_classification.train`. Used the `ImageNette` dataset and `ResNet-50` model from SparseZoo
```
num_epochs: 3.0
init_lr: 0.0005
quantization_epochs: 1.0
start_epoch: 0.0
end_epoch: eval(num_epochs)
- !LearningRateFunctionModifier
final_lr: 0.0
init_lr: eval(init_lr)
lr_func: cosine
start_epoch: 0.0
end_epoch: eval(num_epochs)
sparse_transfer_learning_modifiers:
- !ConstantPruningModifier
start_epoch: 0.0
params: __ALL_PRUNABLE__
sparse_quantized_transfer_learning_modifiers:
start_epoch: …
```
> Update sparseml to support torch 2.0

- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/export_samples.py
* Added call to function that skips the quantization of the input if the model is quantized
* Removed bare exception
* Move input data type conversion upstream so it is properly saved and used as input to ort
* Style and quality fixes
---------
> [cherry-pick 1.5] Convert input for quantized YOLOv8 (#1521)

- src/sparseml/pytorch/__init__.py
- If the detected version of the torch installation is 2.0.x, set `torch.compile` to show a warning 
- Tested locally by running the following code:
```
import sparseml.pytorch.models.classification.resnet as resnet
import torch 
model = resnet.resnet18()
compiled_model = torch.compile(model, fullgraph=True)
print("Compiled Model", type(compiled_model))
print(compiled_model)
```
This returns  a warning before running `torch.compile` on the given model, when run on the command line with sparseml installed:
```
/home/dsikka/sparseml/src/sparseml/pytorch/__init__.py:33: UserWarning: torch.compile is not supported by sparseml for torch 2.0.x
warnings.warn("torch.compile is not supported by sparseml for torch 2.0.x")
Compiled Model <class 'torch._dynamo.eval_frame.OptimizedModule'> …
```
> [torch 2.0] Set `torch.compile` to raise a warning

- setup.py
- src/sparseml/version.py
this fixes a bug in the latest NM 1.5 supported transformers datasets that is incompatible with pandas 2.0. Specifically, a removed kwarg is passed to pandas on `datasets.load_dataset`.
Future releases will support later datasets versions.
> [1.5.2] restrict pandas to <2.0

- src/sparseml/yolov8/trainers.py
Small change to load models initially into CPUs. The model is transferred to GPU if needed later. Without this change the model failed to load on CPU-only systems.
**Test plan:** 
1. I made sure that I could load the model in CPU-only machines and export to onnx, which motivated this fix.
2. In a GPU system I evaluated a dense model (zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/base-none) and made sure GPUs were used as expected
3. In a GPU system I evaluated a sparse model (zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/pruned50_quant-none) and made sure GPUs were used as expected
4. In a GPU system I ran a training command for a sparse model (zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/pruned50_quant-none) and made sure GPUs were used as expected
5. In a GPU system I …
> Fix loading of YOLOv8 sparse models on CPUs

- README.md
- integrations/clip/README.md
- integrations/clip/clip_models.py
- integrations/clip/clip_onnx_export.py
- setup.py
- src/sparseml/pytorch/base.py
- The current onnx export functionality using OpenClip requires torch nightly and opset = 14
- This PR provides an example of how to use sparseml's onnx export functionality to export the visual and text branches of the CLIP model, using [OpenClip](https://github.com/mlfoundations/open_clip)
- OpenClip wraps everything in a `torch.nn.Module` object for the visual branch (ie everything required for the forward pass) but does not do this for the text branch. For the sake of completeness, the `TextModel` class was added (see `clip_models.py`) which wraps the appropriate steps needed in the forward pass. This is then exported 
- Furthermore, for captioning, OpenClip provides thee CoCa models, which requires an additional text-decoder and also uses a separate interface compared to the other …
> [CLIP]: Sparseml onnx export pathways for open_clip models

- setup.py
- src/sparseml/benchmark/info.py
This PR is a first step towards deprecating `sparseml.benchmark` utility which is fairly old and will be deprecated/refactored or removed in a future version
For now, this removes the public pathway `sparseml.benchmark`
Additionally raises a deprecation warning if the script is invoked directly
The actual utility wasn't removed as of yet, cause the helpers in this namespace might be required by `sparsify`
> [BugFix] Hide `sparseml.benchmark`

- setup.py
Updates support to latest numpy
Needed to support deepsparse numpy version upgrade from https://github.com/neuralmagic/deepsparse/pull/1094
The deepsparse change was made to support a ragged sequence being created in question answering pipeline during `spans_extra_info` computation; landing this diff along with   https://github.com/neuralmagic/sparsezoo/pull/332 also fixes a few google colab errors we were seeing before.
> Upgrade numpy to 1.21.6

- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/export_samples.py
Before this PR the ONNX for YOLOv8 would include 3 intermediate outputs. This creates performance issues for the engine. This PR fixes this behavior such that the ONNX will only have the final detection output.
The fix is based on this line of code from the original export script from ultralytics: https://github.com/ultralytics/ultralytics/blob/64f247d6923e28108792cbeea16343606d8cd844/ultralytics/yolo/engine/exporter.py#L180
In short, the Segment and Detection heads have an internal parameter "export" that is set to False by default. When this parameter is False, the heads will output the intermediate values, when it's set to True they output only the final results. The fix simply switches this parameter to True in the export flow.
> YOLOv8 ONNX export fix

- src/sparseml/yolov8/trainers.py
- There was a bug when running the following command:
`sparseml.ultralytics.export_onnx --model model.pt --export-samples 20` where the samples could not be exported.
- This is because, the export function pulls in the yaml path saved in the checkpointed model, which is local to wherever this mode was trained. To fix this, check if the yaml path (stored in `args[data]`) exists. If it does not, just use the default config provided when exporting the data samples.
Furthermore, there was one more check:
```
if args["dataset_path"] is not None:
args["data"] = data_from_dataset_path(
args["data"], args["dataset_path"]
)
```
- Here, if the user provides the `dataset_path` when running `sparseml.ultralytics.export_onnx`, the function `data_from_dataset_path` will attempt to pull the yaml from …
> [Bug Fix] `yolov8` export sample fix

- src/sparseml/pytorch/datasets/registry.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
enables example registry datasets to be downloaded automatically if a local imagefolder of the same name is not found
**testing:**
verified the following previously failing sparsify command now automatically downloads the example dataset and runs
```
sparsify.run sparse-transfer --use-case image-classification --data imagenette
```
> [Sparsify.alpha][Image Classification] use registry dataset is possible when local path to dataset is not available

- src/sparseml/pytorch/datasets/registry.py
- src/sparseml/pytorch/image_classification/utils/helpers.py
-> Remove property from classmethod as it's not supported beyond python 3.9-3.11
Test Command:
```bash
sparsify.run sparse-transfer --use-case image_classification --data imagenette --optim-level 0.5
```
With python3.8, before this PR:
ERROR:
```bash
Failures:
[1]:
time      : 2023-07-07_20:52:56
host      : quad-mle-1
rank      : 1 (local_rank: 1)
exitcode  : 1 (pid: 1351007)
error_file: /tmp/torchelastic_fimqz_6i/none_vfy4yr00/attempt_0/1/error.json
traceback : Traceback (most recent call last):
File "/home/rahul/projects/sparseml/src/sparseml/pytorch/image_classification/utils/helpers.py", line 271, in get_dataset_and_dataloader
dataset = DatasetRegistry.create(
File "/home/rahul/projects/sparseml/src/sparseml/pytorch/datasets/registry.py", line 58, in create
return …
```
> [Bug] Fix dataset alias support

- .github/workflows/Integrations-post-merge-check.yaml
- .github/workflows/integrations-check.yaml
- .github/workflows/test-check.yaml
This PR removes protobuf upgrade step from workflow file causing integration test failures
The `protobuf` version should be dictated by the `setup.py` file
> Remove protobuf upgrade step from GHA

- src/sparseml/transformers/question_answering.py
fixes a bug with custom datasets for `sparseml.transformers.question_answering` where custom JSONL files without a top level `"data"` field wrapping each line
This catches specifically a JSONDecodeError and tries the fallback if so.
**test_plan:**
Reproduced a failing sparsify command and verifies this fixes it:
```
sparsify.run sparse-transfer --use-case question-answering --data local_squad --optim-level 50
```
> [question answering] Fallback to loading JSONL files without `data` prefix

- src/sparseml/exporters/transforms/kv_cache/cache_keys_and_values.py
- src/sparseml/exporters/transforms/kv_cache/configs.py
KV Cache injection support for a BLOOM model
A sample script to inject KV Cache (create `model_kvcache.onnx` from `model.onnx` (model exported from `sparseml.transformers.export`)
```python
import click
import os
import onnx
from sparseml.exporters.kv_cache_injector import KeyValueCacheInjector
@click.command()
@click.option('--input-file', help='Path to the input ONNX model file')
@click.option('--output-file', help='Output path for the modified model')
def modify_model(input_file, output_file):
model = onnx.load(input_file, load_external_data=False)
model = KeyValueCacheInjector(model_path=os.path.dirname(input_file)).apply(model)
onnx.save(model, output_file)
print(f"Modified model saved to: {output_file}")
if __name__ == '__main__':
modify_model()
```
```bash
python …
```
> [KV Cache] BLOOM support

- tests/sparseml/conftest.py
This is a very similar fix to [deepsparse PR 1117](https://github.com/neuralmagic/deepsparse/pull/1117). `check_for_created_files()` is intended to insure large extraneous files(i.e from LLMs) aren't left in the root directory when running tests. This test case was failing due to `__pycache__` files. These files are small so it should be fine that they are created. To fix the test I filtered out the `__pycache__` directories files from the added files check.
Run `make clean` then `make test`
```
E       AssertionError: 18 files created in current working directory during pytest run. Created files: {'/home/sadkins/sparseml/src/sparseml/deepsparse/sparsification/__pycache__/info.cpython-38.pyc', 
'/home/sadkins/sparseml/src/sparseml/tensorflow_v1/framework/__pycache__/__init__.cpython-38.pyc …
```
> Fix Create Files Unit Test

- src/sparseml/pytorch/datasets/classification/cifar.py
CIFAR10 and 100 currently break from data registry instatiations due to not having image_size supported, to unblock, this PR adds image_size as a kwarg and warns that it is not supported if specified
**test_plan**
test that CIFAR out of the box can be kicked off using sparsify:
```
sparsify.run sparse-transfer --use-case image-classification --data cifar10
```
> [CIFAR] pass through required image_size arg and warn that it is not used

- src/sparseml/transformers/utils/model.py
Empty dict raises an exception when exporting quantized MPT models because when `state_dict = {}`, the HF loading pipeline will try to initialize the model by calling `_init_weights` for each module. However, for MPT models, this function is not defined and will therefore raise an exception.
@bfineran  on a side note, I am not really sure what this function is supposed to do. According to the code it will return either `None` (for pruned model) or `{}` (for quantized model), but never the actual loaded `state_dict` as mentioned in the docstring. We might want to rethink whether we need to refactor the function and its usage, or at least to update the docstring because at the moment they don't match.
> Fix onnx export for quantized MPT models

- setup.py
This is required when loading custom code for MosaicML MPT models.
> [Required for MPT models] Add einops to support MPT models

- src/sparseml/pytorch/sparsification/quantization/quantize.py
MPT models appear as HF models wrapped additionally for Composer library compatibility which results in `model.` prefix (instead of the classic `module.`) At the moment this causes errors during export of quantized models as some modules are missed during matching of names. This PR fixes it.
> Fix onnx export for quantized MPT models 2

- pyproject.toml
- tests/sparseml/conftest.py
1. Adding `tmp_path_retention_policy = "none"` to `pyproject.toml` so that pytest deletes its temp files after every session, freeing up disk space. 
2. Because pytest takes care of deleting its own files, we can exclude them from the file size check in `conftest.py`
run `make test TARGETS=transformers`
`check_for_created_files()` fails with error:
```
Failed: failed on teardown with "AssertionError: 2506.184633255005 megabytes of temp files created
in temp directory during pytest run. 
```
tests pass without errors
> Fix Temp File Size Unit Test

- setup.py
- src/sparseml/yolov8/__init__.py
- src/sparseml/yolov8/default.yaml
- src/sparseml/yolov8/train.py
- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/export_samples.py
- src/sparseml/yolov8/val.py
- src/sparseml/yolov8/validators.py
- Update sparseml to use `ultralytics` == 8.0.124. 
- Also update some of the workflows which did not work currently (such as exporting segmentation models with samples)
- Training, Validation, and Export workflows were tested for a dense network and while applying a recipe during training
- Recipe applied during training:
```
version: 1.1.0
start_epoch: 0
end_epoch: 15
- !GMPruningModifier
init_sparsity: 0.05
final_sparsity: 0.10
start_epoch: 5.0
end_epoch: 10.0
update_frequency: 1.0
params: ["model.0.conv.weight", "model.1.conv.weight"]
quantization_modifiers:
start_epoch: 11.0
freeze_bn_stats_epoch: 12.0
disable_quantization_observer_epoch: 13.0
ignore: ["Upsample", "Concat", "SiLU"]
```
GPU + Recipe …
> [YOLOV8] `ultralytics` Update

- src/sparseml/exporters/transforms/kv_cache/cache_keys_and_values.py
- src/sparseml/onnx/utils/graph_editor.py
Fixes the KV Cache logic for quantized text generation models.
In a nutshell, the `QuantizeLinear` nodes that were created in the process of quantization were messing up our pattern-matching rules for finding `Key Matmul `and `Value Matmul`. Additionally the `QuantizeLinear` nodes are by default inserted into a graph in such a way, that they break the topology of the graph with the  kv cache support.
This fix:
- updates the pattern matching for finding `Key Matmul` and `Value MatMul` to be robust against the presence of `QuantizeLinear` nodes
- moves the `QuantizeLinear` nodes to their appropriate place in the onnx graph.
Note: For manual testing it is required to use this branch: https://github.com/neuralmagic/deepsparse/pull/1123. It provides the appropriate support for quantized kv …
> [Fix] Fix the KV Cache insertion logic for quantized OPT

- src/sparseml/pytorch/sparsification/quantization/quantize.py
This reverts commit e8ff0f6bd5ed4fcb8d281f30462462b0125b4ddf.
These commit breaks our current YOLOv8 flows (After #1680 ); reverting them for now, a fix will be put in later for MPT models
> Revert "Fix onnx export for quantized MPT models 2 (#1647)"

- src/sparseml/yolov8/trainers.py
Certain calls for `_modify_arch_for_quantization` still referred to the class specific implementation which was removed in #1498. The PR fixes the functional calls for all call references.
Test:
a. python -m torch.distributed.run --no_python --nproc_per_node 2 sparseml.ultralytics.train   --recipe ~/recipes/yolov8/test_yolov8n_recipe.yaml  --model zoo:cv/detection/yolov8-n/pytorch/ultralytics/coco/pruned48_quant-none   --data VOC.yaml   --batch 4
b. python -m torch.distributed.run --no_python --nproc_per_node 2 sparseml.ultralytics.train   --recipe ~/recipes/yolov8/test_yolov8n_recipe.yaml  --model runs/detect/train/weights/last.pt  --data VOC.yaml   --batch 4 --resume
> YOLOV8 Fix modify arch for quantization call

- setup.py
- src/sparseml/yolov8/__init__.py
- src/sparseml/yolov8/default.yaml
- src/sparseml/yolov8/train.py
- src/sparseml/yolov8/trainers.py
- src/sparseml/yolov8/utils/export_samples.py
- src/sparseml/yolov8/val.py
- src/sparseml/yolov8/validators.py
Merge on-hold pending deepsparse support
- Update sparseml to use `ultralytics` == 8.0.124. 
- Also update some of the workflows which did not work currently (such as exporting segmentation models with samples)
- Training, Validation, and Export workflows were tested for a dense network and while applying a recipe during training
- Recipe applied during training:
```
version: 1.1.0
start_epoch: 0
end_epoch: 15
- !GMPruningModifier
init_sparsity: 0.05
final_sparsity: 0.10
start_epoch: 5.0
end_epoch: 10.0
update_frequency: 1.0
params: ["model.0.conv.weight", "model.1.conv.weight"]
quantization_modifiers:
start_epoch: 11.0
freeze_bn_stats_epoch: 12.0
disable_quantization_observer_epoch: 13.0
ignore: …
```
> [YOLOV8] Update version

- src/sparseml/exporters/onnx_to_deepsparse.py
- src/sparseml/pytorch/utils/exporter.py
`ONNXToDeepsparse` was implemented to replace `quantize_torch_qat_export` however the migration was not completed due to not enough testing taken place. Now that sparsify one_shot has been verified using `ONNXToDeepsparse`, this PR completes the migration
> update sparseml.pytorch export_onnx to use ONNXToDeepsparse

- src/sparseml/pytorch/sparsification/quantization/quantization_scheme.py
extra comma after string close is read as tuple since line break is made with parenthesis
> [bugfix][QuantizationScheme] fix string that is read in tuple

- src/sparseml/exporters/transforms/kv_cache/transforms_base.py
- src/sparseml/onnx/utils/graph_editor.py
utility function that deletes all node branches in an ONNX graph that do not lead to a model output
necessary for the latest LLM graph transformations as rewiring the graphs to take positions and causal masks directly leaves the graphs with orphaned node branches
**example_usage:**
```python
import onnx
from sparseml.onnx.utils import ONNXGraph
model = onnx.load(PATH_TO_MODEL)
graph = ONNXGraph(model)
graph.delete_orphaned_node_branches()
```
**test_plan:**
@dbogunowicz to test with LLMs story. will verify that extraneous nodes are deleted and model correctness remains
> [ONNXGraph] delete_orphaned_node_branches utility function

- src/sparseml/transformers/export.py
fixes internally reported issue where output directories were unable to be created for transformers onnx export
specifically, this commit https://github.com/neuralmagic/sparseml/commit/b52a13da852051bfd7d100652c57929b4c5ffdde tries to access the parent directory of a model which does not work for relative paths
this PR unwraps any file inputs to the script to their absolute path to unblock this and future workflows
**test_plan:**
reproduced issue with local file path and confirmed fix resolves:
```
sparseml.transformers.export_onnx --sequence_length 128 --task text_generation --model_path  opt-350m
```
> support relative paths in sparseml.tarnsformers.export_onnx

- src/sparseml/pytorch/sparsification/quantization/helpers.py
Tied embeddings are usually implemented in a way that they subclass `torch.nn.Embedding` and then implement the custom parts to handle using of the same matrix for embeddings and for the LM head. This PR enables detecting these modules during quantization as their type is not `Embedding`, but rather something custom defined by the LLM implementation. However, they are all subclasses of `torch.nn.Embedding` which we can utilize to detect them.
Before this PR, quantization modifier couldn't find tied embeddings modules as their type is not `torch.nn.Embedding`.
> Enable quantization of tied embeddings

- .github/workflows/test-check.yaml
- src/sparseml/transformers/sparsification/trainer.py
- src/sparseml/version.py
During 1.5.1 upgrade of transformers the needed changes on sparseml side were not cherrypicked to release/1.5 branch; this PR is a minimal version of those changes needed for latest sparseml ~1.5 wheels to work with latest nm-transformers ~1.5 wheels.
The original problem commit that was missed: https://github.com/neuralmagic/sparseml/commit/4ec5133ca14501f265d98c97be2e9cd44825583b
Test command:
```bash
#!/usr/bin/env bash
set -euf -o pipefail
export SPARSEZOO_TEST_MODE="true"
export NM_BIND_THREADS_TO_CORES=1
export NM_DISABLE_ANALYTICS=1
sparseml.transformers.train.text_classification \
--output_dir sparse_quantized_bert-text_classification_sst2 \
--model_name_or_path "zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none" \
--task_name sst2 --max_seq_length …
```
> [Cherry Pick 1.5.4] Fix Index error with nm-transformers 1.5.1 upgrade

- integrations/clip/README.md
- integrations/clip/clip_models.py
- integrations/clip/clip_onnx_export.py
**NOTE**: We need torch nightly for clip onnx exports. This is currently through README instructions (under `integrations/clip`) as there seems to be no easy way to list torch-nightly in `setup.py`
Update clip instructions, dependencies, and export pathways while making sure clip works end-to-end (sparseml export, deepsparse pipeline inference)
> [CLIP] Update clip dependencies, README.md, export pathways

- src/sparseml/exporters/transforms/kv_cache/transforms_llama.py
For the quantized models, the Slice nodes that need to be updated have input values stored as initializers, while for the dense models, they're stored as constants. This PR updates to check for both.
> [LLAMA] update pattern to consider initializers

- src/sparseml/recipe_template/README.md
This PR adds some more documentation around `sparseml.recipe_template`
> Add recipe template doc

- README.md
- integrations/ultralytics-yolov5/tutorials/sparse-transfer-learning.md
Short PR to fix broken links in the readme and yolo tutorials, this should fix the previously failing markdown-link-check
> Update Failed README Links

- tests/integrations/helpers.py
- tests/sparseml/onnx/utils/test_graph_optimizer.py
- tests/sparseml/pytorch/test_torch_to_onnx_exporter.py
latest version of ORT has a hard requirement for providers to be set. this PR updates any inference session that does not have it set 
**test_plan:**
QA Team + GHA
> explicitly set ORT providers on all InferenceSession creations

- tests/sparseml/pytorch/models/detection/test_ssd_resnet.py
These models are deprecated and no longer on SparseZoo as of V2, so we can skip this failing test
> Deprecate SSD Resnet Tests

- src/sparseml/exporters/onnx_to_deepsparse.py
- src/sparseml/pytorch/utils/exporter.py
Similar implementation as with QLinearConv
> Deprecate the use of QLinearMatMul in favor of MatMultInteger

- src/sparseml/exporters/transforms/onnx_transform.py
- tests/sparseml/exporters/transforms/test_conv_to_convinteger_add_cast_mul.py
- tests/sparseml/exporters/transforms/test_conv_to_qlinearconv.py
- tests/sparseml/exporters/transforms/test_delete_repeated_qdq.py
- tests/sparseml/exporters/transforms/test_flatten_qparams.py
- tests/sparseml/exporters/transforms/test_fold_relu_quants.py
- tests/sparseml/exporters/transforms/test_gemm_to_matmulinteger_add_cast_mul.py
- tests/sparseml/exporters/transforms/test_gemm_to_qlinearmatmul.py
- tests/sparseml/exporters/transforms/test_matmul_add_to_matmulinteger_add_cast_mul.py
- tests/sparseml/exporters/transforms/test_matmul_to_qlinearmatmul.py
- tests/sparseml/exporters/transforms/test_propagate_embedding_quantization.py
- tests/sparseml/exporters/transforms/test_remove_duplicate_qconv_weights.py
- tests/sparseml/exporters/transforms/test_remove_duplicate_quantize_ops.py
adds a pass in the base `ONNXTransform` cleanup steps to run `ONNXGraph.delete_orphaned_node_branches` which is an important additional cleanup step.  This removes unwanted nodes from remaining in the graph after a transform which could lead to issues at inference time.  This function should be safe to run against all transforms and only adds minimal overhead (`O(nodes^2)`) if any orphaned nodes are found
should fix issues in KVCache injected MPT models which seem to consistently get shipped with orphaned nodes remaining
**test_plan:**
verified locally that this unblocked running a pipeline with `zoo:nlg/text_generation/mpt-7b/pytorch/huggingface/mpt_chat/base-none`
future testing should pull down a model with no data files and test injection against it
> [ONNXTransform] always delete orphaned node branches after running an onnx transform

- src/sparseml/transformers/__init__.py
This would fail if the attribute wasn't present rather than warn
```
File "sparseml/src/sparseml/transformers/__init__.py", line 43, in _check_transformers_install
if not _transformers.NM_INTEGRATED:
File "lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1177, in __getattr__
raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute NM_INTEGRATED
```
> Update transformers/__init__.py to warn about nm_transformers

- src/sparseml/core/modifier/modifier.py
This PR fixes a bug where Modifier Updates were not applied if the modifier starts at epoch 0;
This was due to an if condition in `Modifiier should_start(..)` method, the condition was checking for Falsy values rather than `None`. As 0 is a Falsy value, `should_start` was always returning False (Wrongly)
Current PR addresses that by enforcing a stricter check
Test, verified manually: can be tested with any Valid recipe from the new framework and setting modifier start to 0
Example recipe:
```yaml
test_stage:
ConstantPruningModifier:
start: 0
end: 2
targets: ['re:.*weight']
leave_enabled: True
```
> [BugFix] Modifiers not started if start is set to 0

- src/sparseml/modifiers/pruning/constant/pytorch.py
The mask calculation in the constant pruning modifier was inverted, this one character PR fixes it!
Constant pruning modifier is tested in this branch: https://github.com/neuralmagic/sparseml/tree/modifier-refactor-constant-pruning-bug
Run `python bug_constant_pruning` to confirm constant pruning modifier is working as intended
> Fix Constant Pruning Modifier

- src/sparseml/core/data/base.py
- src/sparseml/core/data/pytorch.py
- src/sparseml/core/event.py
- src/sparseml/core/factory.py
- src/sparseml/core/framework.py
- src/sparseml/core/framework_object.py
- src/sparseml/core/lifecycle/event.py
- src/sparseml/core/model/base.py
- src/sparseml/core/model/pytorch.py
- src/sparseml/core/modifier/base.py
- src/sparseml/core/modifier/modifier.py
- src/sparseml/core/modifier/stage.py
- src/sparseml/core/optimizer/base.py
- src/sparseml/core/optimizer/pytorch.py
- src/sparseml/core/recipe/args.py
- src/sparseml/core/recipe/base.py
- src/sparseml/core/recipe/container.py
- src/sparseml/core/recipe/modifier.py
- src/sparseml/core/recipe/recipe.py
- src/sparseml/core/recipe/stage.py
- src/sparseml/core/session.py
- src/sparseml/core/state.py
This PR will add documentation to the newly added classes/methods for the Modifier Refactor Push:
Files to document:
> [Documentation] Add documentation and basic `doctests` to `sparseml/core`

- src/sparseml/core/recipe/modifier.py
- src/sparseml/core/recipe/recipe.py
This PR fixes a bug in Recipe classes .dict() method, needed to support serialization
Before:
```python
>>> recipe_str = '''
... test_stage:
...     pruning_modifiers:
...         ConstantPruningModifier:
...             start: 0.0
...             end: 2.0
...             targets: ['re:.*weight']
... '''
>>> recipe = Recipe.create_instance(recipe_str)
>>> recipe.dict()
...
KeyError: 'group'
```
```python
>>> recipe_str = '''
... test_stage:
...     pruning_modifiers:
...         ConstantPruningModifier:
...             start: 0.0
...             end: 2.0
...             targets: ['re:.*weight']
... '''
>>> recipe = Recipe.create_instance(recipe_str)
>>> recipe_dict = recipe.dict()
>>> stage = recipe_dict["stages"]["test"]
>>> pruning_mods = …
```
> [Bugfix] .dict() method on Recipe

- .github/workflows/test-check.yaml
- DEVELOPING.md
- README.md
- docs/source/installation.md
- setup.py
- src/sparseml/core/lifecycle/session.py
This PR updates out max supported Python version to `~3.11`
Testing: ran `make test TARGETS=torch` locally, will report results when complete
Tests Pass with fixes:
```bash
$ make test TARGETS=torch                                                                                                            (add-python3.11-support|✚1…1⚑2)
Running python tests
SPARSEZOO_TEST_MODE="true" pytest tests "" --ignore tests/sparseml/deepsparse --ignore tests/sparseml/transformers --ignore tests/sparseml/keras --ignore tests/sparseml/onnx --ignore tests/sparseml/pytorch --ignore tests/sparseml/pytorch/models --ignore tests/sparseml/pytorch/datasets --ignore tests/sparseml/tensorflow_v1 --ignore tests/sparseml/tensorflow_v1/models --ignore tests/sparseml/tensorflow_v1/datasets --ignore …
```
> [Feature] Support `Python3.11`

- src/sparseml/transformers/export.py
> [sparseml.transformers.export_onnx] add --opset flag

- src/sparseml/modifiers/obcq/utils/helpers.py
- src/sparseml/transformers/data/base_llm.py
Replacing `torch.concatenate` calls with `torch.cat`, they are the same function but `concatenate` is an alias that doesn't exist in earlier versions of pytorch.
```
File "src/sparseml/transformers/sparsification/obcq/obcq.py", line 167, in <module>
one_shot(
File "src/sparseml/transformers/sparsification/obcq/obcq.py", line 89, in one_shot
dataset = TransformersDataset.load_from_registry(
File "/home/michael/sml/lib/python3.8/site-packages/sparsezoo/utils/registry.py", line 120, in load_from_registry
return constructor(**constructor_kwargs)
File "/home/michael/code/sparseml/src/sparseml/transformers/data/open_platypus.py", line 68, in __init__
self.create_dataloader(processed_data)
File "/home/michael/code/sparseml/src/sparseml/transformers/data/base_llm …
```
> Fix Concatenate Compatibility

- src/sparseml/pytorch/torchvision/train.py
The DDP fix implemented in this [PR](https://github.com/neuralmagic/sparseml/pull/1698) uses an older interface to pass the local rank for DDP that only works w/ torch.distributed.run.
This PR replaces this by passing the local rank via an environment variable, which is supported by both torch.distributed.run and the newer torchrun interfaces.
> Enable IC runs w/ torchrun

- src/sparseml/core/lifecycle/session.py
- src/sparseml/core/state.py
- tests/sparseml/conftest.py
When session was reset; the state.data attribute wasn't being reset properly; this led to the following unexpected failure; (which only reveals itself if `tests/sparseml/core/test_state.py` was executed before `tests/sparseml/pytorch/modifiers/quantization/test_pytorch.py`) 
[here](https://github.com/neuralmagic/sparseml/actions/runs/6619351713/job/17979711097?pr=1752#step:8:2243)
This PR fixes this issue, by also resetting `state.data` when `active_session.reset()` is called
Additionally this PR also introduces a auto-use fixure; that resets the active session before and after every test_function call
Steps to reproduce bug:
```bash
pytest tests/sparseml/core/test_state.py tests/sparseml/pytorch/modifiers/quantization/test_pytorch.py -s
```
Results in:
```bash
-- Docs: …
```
> [BugFix] Fix session reset

- src/sparseml/modifiers/obcq/utils/layer_compressor.py
If quantization was set to True in the SparseGPTModifier, only quantized layers would be compressed by the algorithm. This fix cleans up the code quite a bit by using the existing `get_prunable_layers` utility function to search for both quantized and unquantized prunable layers. Now if a layer is ignored by the QuantizationModifier the SparseGPTModifier will still prune it.
Example Recipe:
```
test_stage:
QuantizationModifier:
ignore:
- LlamaRotaryEmbedding
- LlamaRMSNorm
- SiLUActivation
- model.layers.1.mlp.down_proj
- model.layers.5.mlp.down_proj
post_oneshot_calibration: True
scheme_overrides:
Embedding:
input_activations: null
weights:
num_bits: 8
symmetric: False
sparsity: 0.5
sequential_update: False
quantize: True
percdamp: 0.01 …
```
> [Bug Fix] Fix pruning for partially quantized models

- setup.py
This error was originally reported for deepsparse, but affects sparseml as well. Asana ticket: [NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported. (from datasets)](https://app.asana.com/0/1203126676641557/1205796604651399/f) 
The latest `fsspec` release(2023.10.0) caused a breaking change with the datasets library. Upgrading our datasets version fixes the issue. Alternatively, we can downgrade `fsspec`
> Update datasets to 2.14.6 for fsspec compatibility

- src/sparseml/exporters/transforms/kv_cache/configs.py
```
git clone https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha
sparseml.transformers.export_onnx --model_path ./zephyr-7b-alpha --task text-generation --sequence_length 512 --trust_remote_code
cp deployment/model.onnx deployment/model-orig.onnx
python ~/onnx_kv_inject.py --input-file deployment/model-orig.onnx --output-file deployment/model.onnx
```
```
>>> from deepsparse import TextGeneration
>>> model = TextGeneration(model="deployment")
>>> out = model("Once upon a time,", max_new_tokens=100)
>>> out.generations[0].text
'there was a young woman named Lily. She was a kind and gentle soul, with a heart full of love and compassion. Lily had always been fascinated by the natural world, and she spent most of her free time exploring the forests and fields around her home.\n\nOne day, as …
```
> Add kvcache config for Mistral

- src/sparseml/pytorch/torchvision/train.py
Before this PR, DDP was applied when model was first created, before recipe is applied. This creates problems when the recipe specifies parameter names, since DDP will wrap the model and alter the parameter names.
**Test plan:**
The following command was used as test case (it fails w/o the PR)
```
torchrun --nproc_per_node 4 --no_python \
--recipe zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned90_quant-none \
--amp \
--dataset-path /network/datasets/imagenet \
--batch-size 256 \
--output-dir resnet50-imagenet-pruned90_quant-none
```
> Only apply DDP after manager is applied and weights are loaded

- src/sparseml/transformers/sparsification/obcq/obcq.py
- src/sparseml/transformers/utils/model.py
Adds mistral support for the obcq script using the latest [nm-transformers](https://github.com/neuralmagic/transformers). This diff experiments with loading with the simple AutoModel interface and finding the model arch name from the config file's `model_type`
Here is a sample recipe I used for zephyr-beta
```yaml
test_stage:
QuantizationModifier:
ignore:
- MistralRotaryEmbedding
- MistralRMSNorm
- SiLUActivation
- model.layers.1.mlp.down_proj
- model.layers.31.mlp.down_proj
- model.layers.30.mlp.down_proj
- model.layers.30.mlp.gate_proj
- model.layers.30.mlp.up_proj
post_oneshot_calibration: True
scheme_overrides:
Embedding:
input_activations: null
weights:
num_bits: 8
symmetric: False
sparsity: 0.5
sequential_update: False
quantize: …
```
> Add mistral to obcq

- src/sparseml/transformers/finetune/data/__init__.py
- src/sparseml/transformers/finetune/data/base.py
- src/sparseml/transformers/finetune/data/c4.py
- src/sparseml/transformers/finetune/data/data_args.py
- src/sparseml/transformers/finetune/data/helpers.py
- src/sparseml/transformers/finetune/data/open_platypus.py
- src/sparseml/transformers/finetune/data/wikitext.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/finetune/trainer.py
- test_trainer.py
Adding support for C4 and Open Platypus and ability to specify additional kwargs to `datasets.load_dataset`. Also added support for custom dataset splits. For instance, Open Platypus only has a `train` split defined, but now new splits can be created like this:
```
data_args.splits = {
"train": "train[:90%]",
"test": "train[90%:]"
}
```
Custom splits and additional kwargs for C4 can be tested with. Also tested with Open Platypus
```
python test_trainer.py
```
* refactor OBCQ script to use this  same dataset registry (maybe in separate PR)
> Additional Datasets for Finetuning

- src/sparseml/transformers/data/__init__.py
- src/sparseml/transformers/data/gsm8k.py
- src/sparseml/transformers/sparsification/obcq/obcq.py
With this PR, we enable to running OBCQ on GSM8K dataset.
Testing:
```python obcq.py models/Llama-2-7b-hf/ gsm8k --recipe example_llama.yaml```
runs perfectly.
> Adding GSM8K support for OBCQ

- src/sparseml/modifiers/utils/__init__.py
Fixing test error:
`ModuleNotFoundError: No module named 'sparseml.modifiers.utils'`
> [Bug Fix] Add missing module __init__.py

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/transformers/sparsification/obcq/example.yaml
- src/sparseml/transformers/sparsification/obcq/example_llama.yaml
- tests/sparseml/pytorch/modifiers/obcq/test_pytorch.py
Before this PR OBCQ recipes needed prunen/prunem to be specified individually. This PR makes a UX change such that now, a `mask_structure` of the form `N:M` can be defined; the where both N, M are integers (similar to prunen and prunem)
Test command:
```bash
python3 src/sparseml/transformers/sparsification/obcq/obcq.py faceb
ook/opt-350m c4 --recipe src/sparseml/transformers/sparsification/obcq/example.yaml --eval wikitext2 
```
Output:
```bash
.
.
.
2023-10-31 07:03:54 sparseml.modifiers.quantization.pytorch INFO     Running quantization calibration using calibration_dataloader
2023-10-31 07:04:02 sparseml.modifiers.obcq.utils.helpers INFO     Evaluating perplexity...
2023-10-31 07:04:03 sparseml.modifiers.obcq.utils.helpers INFO     tensor(34.7602, device='cuda:0')
2023-10-31 07:04:05 …
```
> [OBCQ][Recipe UX change] Prunen-prunem-to-mask-structure

- tests/sparseml/transformers/__init__.py
- tests/sparseml/transformers/obcq/__init__.py
A few test folders, did not have __init__.py files; this causes problems with pytest during test collection. Adding those files fixes collection issues. This PR does that.
> Add missing init files in tests

- src/sparseml/transformers/sparsification/obcq/obcq.py
From @eldarkurtic 's early experiments on the small GSM8k dataset, just increasing num samples can provide up to 8 points accuracy improvement over 128. `nsamples=2048` gave the best results but 512 got most of the way there, so I consider this a safe default
> Increase obcq nsamples to 512

- src/sparseml/modifiers/obcq/pytorch.py
This PR removes changes made to the model config when finalizing the OBCQ modifier. Specifically, we change use_cache when running SparseGPT, but we don't want this change to be permanent. If we do make this change permanent, the use_cache is saved in the compressed checkpoint and inference may become slower.
> Remove changes to model config at finalization

- src/sparseml/transformers/sparsification/obcq/__init__.py
Python build command ignores packaging `sparseml.transformers.sparsification.obcq` in wheel due to missing init files in transformers/obcq folder. That causes a `ModuleNotFoundError`; this bug oly reveals itself when installing from the wheel, and actually passes when doing an `--editable` install
Fix includes: Adding missing init file in the respective folder
Steps to reproduce:
```bash
pip3 install --default-timeout=200 --index-url http://10.10.60.107:8080/ --trusted-host 10.10.60.107 "sparseml-nightly[torchvision, transformers]"
```
```python
>>> from sparseml.transformers.sparsification.obcq.obcq import one_shot
/home/domenic/testing/testfail-1019/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML") …
```
> [Bugfix] ModuleNotFoundError when importing `one_shot` from`obcq`

- src/sparseml/exporters/transforms/kv_cache/configs.py
A polished version of @mgoin 's PR: https://github.com/neuralmagic/sparseml/pull/1731
As discussed internally, until we potentially figure out the new UI for the KV Cache Injection, we should have an appropriate pathway to handle GQA models.
```python
from huggingface_hub import snapshot_download
import os
from src.sparseml.exporters.kv_cache_injector import KeyValueCacheInjector
import onnx
import onnxruntime
import numpy as np
from deepsparse.transformers.utils.helpers import create_causal_mask
directory = snapshot_download("mgoin/TinyLlama-1.1B-step-50K-105b-ONNX")
model = onnx.load(os.path.join(directory, "model-orig.onnx"), load_external_data=False)
model = KeyValueCacheInjector(model_path=directory).apply(model)
onnx.save(model, os.path.join(directory, "model.onnx"))
input_ids = …
```
> [KV Cache Injection] Pathway to handle GQA models

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/helpers.py
- src/sparseml/transformers/sparsification/obcq/example.yaml
- src/sparseml/transformers/sparsification/obcq/example_llama.yaml
- src/sparseml/transformers/sparsification/obcq/utils/helpers.py
- tests/sparseml/transformers/obcq/test_tiny.yaml
This PR removes target_ids param from OBCQ modifier; now this param is not needed and will be inferred automatically
Test plan: Run obcq on both llama, and opt-1.3b; and assert we do not drop in perplexity
Expected perplexity: 
-  opt - b/w 18-20
-  llama - b/w 7-8
Test commands:
```bash
python3 src/sparseml/transformers/sparsification/obcq/obcq.py faceb
ook/opt-1.3b c4 --recipe src/sparseml/transformers/sparsification/obcq/example.yaml --eval wikitext2 
```
Output: (Truncated)
```bash
2023-10-31 10:55:11 sparseml.modifiers.obcq.utils.helpers INFO     Perplexity: 18.037699
```
```bash
python src/sparseml/transformers/sparsification/obcq/obcq.py /home/rahul/llama/training open_platypus --recipe src/sparseml/transformers/sparsification/obcq/example_llama.yaml --eval wikitext2
```
Output: …
> [OBCQ Recipe UX Change] Remove target_ids

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/helpers.py
- src/sparseml/transformers/sparsification/obcq/utils/helpers.py
`target_ids` was deprecated in a previous PR #1804 ; in hindsight it would be nicer to make it optional to allow easier transition for users(credits to @anmarques). This PR does that. With this change older recipes (with target_ids specified) would also work and log a warning saying this param is deprecated and would be removed completely in a future release. 
The same test was run as in #1804 and same results were observed
> [OBCQ][UX update] Make target ids optional

- src/sparseml/transformers/export.py
- src/sparseml/transformers/sparsification/obcq/export.py
```
sparseml.transformers.export_onnx --model_path ./TinyLlama-1.1B-Chat-v0.3 --task text-generation --trust_remote_code 
2023-11-13 18:56:23 sparseml.transformers.export INFO     Attempting onnx export for model at /home/mgoin/models/TinyLlama-1.1B-Chat-v0.3 for task text-generation
2023-11-13 18:56:23 sparseml.transformers.export INFO     Using default sequence length of 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```
Unfortunately I think it is very important to export LLMs with the largest sequence length possible.
For instance I was exporting llama models with a sequence length of 512 for convenience
`sparseml.transformers.export_onnx --model_path ./llama2.c-stories15M --task text-generation …
> Change Transformers export default sequence length to max_position_embeddings

- src/sparseml/core/state.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/layer_compressor.py
- src/sparseml/modifiers/quantization/pytorch.py
- tests/sparseml/core/test_state.py
- tests/sparseml/transformers/obcq/test_obcq.py
- tests/sparseml/transformers/obcq/test_tiny.yaml
- tests/sparseml/transformers/obcq/test_tiny2.yaml
Previously, the OBCQ script would move the entire input model to the GPU during initialization. This PR removes this and instead loads the model layer by layer. 
CAVEAT: This fix is only for the SparseGPTModifier. For the  quantization and smoothquant modifiers, the model is still fully loaded onto the device in order to run calibration. Do we want to add additional options to run calibration on the CPU (would also need to fix the fp16 issues) while keeping OBCQ on the GPU, or update the quantization modifiers themselves to be able to run layer by layer (probably more work)?
test_recipe.yaml
```
test_stage:
sparsity: 0.5
sequential_update: True
quantize: False
percdamp: 0.01
mask_structure: "0:0"
targets: [
"re:model.layers.\\d*$"
] …
```
> [Bug Fix] Reducing Memory Requirements for Sequential OBCQ

- src/sparseml/modifiers/pruning/constant/pytorch.py
- src/sparseml/modifiers/pruning/utils/pytorch/layer_mask.py
- src/sparseml/transformers/finetune/callbacks.py
- src/sparseml/transformers/finetune/session_mixin.py
- src/sparseml/transformers/finetune/text_generation.py
- tests/sparseml/pytorch/modifiers/pruning/constant/test_pytorch.py
in the current layer masking implementation, parameters are stored at initialization and references to them are used to apply masks on modifier update
in FSDP mode, it seems that masking on top of these references does update these parameter references, but these parameters no longer have an effect on the FSDP module. 
this fix just implements the simple flow @dsikka used in the sparsify MVP to apply the masks over a reference to the current FSDP module at update time. (ie instead of applying masks on the saved references to the layers, the masks are applied directly over fresh references from the model)
handing off to @Satrat
**confirmation of fix**
test command:
`accelerate launch --config_file fsdp_config.yaml test_trainer.py`
snippet of output with sparsity log (previously 0.0 for all …
> [draft] proposed fix for incorrect mask application in FSDP

- src/sparseml/modifiers/obcq/utils/sparsegpt.py
- src/sparseml/transformers/sparsification/obcq/obcq.py
- src/sparseml/transformers/sparsification/obcq/utils/helpers.py
- tests/sparseml/transformers/obcq/test_obcq.py
`tests.sparseml.transformers.obcq.test_obcq` was failing on Jenkins due to CUDA not being available, this PR updates the OBCQ script to fall back to CPU if CUDA is unavailable. The model used in this test is very small, so it still runs quickly enough on CPU.
Also fixes a small bug in the perplexity calculations in the OBCQ script caused by the recent `target_ids` change
```
export CUDA_VISIBLE_DEVICES=[]
pytest tests/sparseml/transformers/obcq/test_obcq.py
```
Output:
```
WARNING    sparseml.transformers.sparsification.obcq.obcq:obcq.py:156 Requested cuda:0 but CUDA is not available, falling back to CPU
.....
tests/sparseml/transformers/obcq/test_obcq.py::test_obcq_tinystories[tests/sparseml/transformers/obcq/test_tiny.yaml] PASSED …
```
> [OBCQ Bug Fix] Fallback to CPU if no CUDA

- src/sparseml/modifiers/smoothquant/pytorch.py
Fix for a bug that caused smoothquant the run on the CPU, the device was not being passed to the calibration function properly
> Pass Device to SmoothQuant

- tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_topkast.py
This one test fails a lot because of the randomly initialized matrices. So some ways to ease this:
- greater fault tolerance in computations
- make nan = nan
- mark test as flaky
Tested this a bunch locally, seems to consistently pass now.
> fix flaky topkast test

- tests/sparseml/transformers/utils/test_helpers.py
In the recent SparseZoo changes we have altered the behavior of `Model.download()`. Now it only downloads the `deployment.tar`, but does not unzip it. So we have to manually call the `.unzip()` method to get the expected result.
> [Fix] Failing `test_save_zoo_directory` tests

- src/sparseml/exporters/transforms/flatten_qparams.py
the assertion removed in this PR is not needed since if the qparam is not (1,) we don't need to flatten it. this can lead to unwanted assertions if/when the export format changes
> [transforms] change flattenqparams assertion to check

- src/sparseml/exporters/transforms/flatten_qparams.py
the assertion removed in this PR is not needed since if the qparam is not (1,) we don't need to flatten it. this can lead to unwanted assertions if/when the export format changes
> [cherry-pick][transforms] change flattenqparams assertion to check (#1850)

- src/sparseml/pytorch/utils/exporter.py
- src/sparseml/transformers/export.py
> [Cherry Pick] Two recent small diffs for transformers export

- tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_topkast.py
Fix flaky Top-Kast test by imposing numerical stability.
> Fix flaky Top-KAST test by imposing numerical stability (smaller lr, fewer epochs of training)

- tests/sparseml/transformers/obcq/test_obcq.py
A previous PR removed the llama-specific loading function, replacing it with an AutoModel load. This PR updates a unit test to reflect the change
> OBCQ Test Fix

- integrations/huggingface-transformers/finetuning/example_fsdp_config.yaml
- src/sparseml/modifiers/distillation/output/pytorch.py
- src/sparseml/modifiers/distillation/utils/pytorch/kd_wrapper.py
- src/sparseml/transformers/finetune/session_mixin.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/finetune/trainer.py
This PR contains a few bug fixes for finetuning, mostly related to checkpoints
* Adding logic to `kd_wrapper.py` to determine if `named_modules` should return the full module or just the student. This varys based on when it is called (see comments)
* Expand the `SessionMixIn.save_model` function to export the resulting model as a single bin, this allows it to be reloaded outside of FSDP. 
* Cleaning up checkpoint logic to use the input recipe if we're resuming from a checkpoint
* Only update the loss if a modifier returns a non-None loss value (the previous distillation merge had broken non-distillation loss calculation)
Tested saving and reloading checkpoints works with and without FSDP
Resuming an FSDP checkpoint outside of FSDP still doesn't work out of the box. You need to treat the …
> Misc Finetuning Checkpointing Fixes

- src/sparseml/transformers/sparsification/obcq/obcq.py
Previously the OBCQ script would return with an error if one of the supported/tested model types wasn't found in the name of the `--model_path` argument. 
With this PR, instead of erroring out we just return a warning to the user and attempt to load the model with `AutoModelForCausalLM` anway.
```
src/sparseml/transformers/sparsification/obcq/obcq.py model_path=sahil2801/replit-code-instruct-glaive open_platypus --recipe tests/sparseml/transformers/obcq/test_tiny.yaml --save True
```
The model successfully loads with a warning. One-Shot does fail for this model, will address that in another PR since its MPT-specific
Asana ticket: https://app.asana.com/0/1205229323407165/1206141086244198/f
> [One Shot] Default to AutoModel loading in OBCQ script

- src/sparseml/transformers/sparsification/trainer.py
- src/sparseml/transformers/utils/helpers.py
importing from `sparseml.pytorch.model_load.helpers` was causing a circular import when launching one-shot, this moves the default recipe definition to avoid the issue
> Fix Circular Import in Old Trainer

- src/sparseml/transformers/sparsification/obcq/obcq.py
A bug was found in obcq.py script where if sequence_length was not supplied, it would cause a TypeError down the line during datset loading.
The bug was potentially introduced in #1872
This PR brings back `model.seqlen` from #1872 and falls back to using that if `sequence_length` is not set:
Test command:
```bash
python src/sparseml/transformers/sparsification/obcq/obcq.py /home/rahul/llama/training c4 --recipe src/sparseml/transformers/sparsification/obcq/example_llama.yaml --eval wikitext2 --nsamples 128 --precision full
```
Error:
```bash
2023-12-13 10:30:23 __main__     INFO     Running one_shot on device cuda:0
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 …
```
> [BugFix] `TypeError` with OBCQ

- src/sparseml/core/recipe/recipe.py
The error message when loading a recipe file that doesn't exist is unclear. Adding some logging to indicate the input is being parsed as a string if a valid path isn't found
> Clarify Recipe Load Logs

- src/sparseml/modifiers/pruning/utils/pytorch/layer_mask.py
Bug:
Magnitude Pruning fails with the following message
```bash
Logging all SparseML modifier-level logs to sparse_logs/18-12-2023_14.52.42.log
2023-12-18 14:52:42 sparseml.core.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/18-12-2023_14.52.42.log
2023-12-18 14:52:42 sparseml.core.recipe.recipe INFO     Loading recipe from file /home/rahul/projects/sparseml/local/recipe.yaml
File "/home/rahul/projects/sparseml/local/e2e.py", line 101, in <module>
session.event(event_type=EventType.OPTIM_POST_STEP)
File "/home/rahul/projects/sparseml/src/sparseml/core/session.py", line 261, in event
mod_data = self._lifecycle.event(
^^^^^^^^^^^^^^^^^^^^^^
File "/home/rahul/projects/sparseml/src/sparseml/core/lifecycle/session.py", line 146, in …
```
> [BugFix] magnitude pruning fail

- .gitignore
> [Add] log dirs to gitignore

- docker/Dockerfile
The dockerfile failed to build because python3-venv does not work well with multiple python versions; using virtualenv fixes this by explicitly specifying the python version; `using -m also helps`
This should not have any implications on the final image size
Creating and activating a virtual env has also been moved into it's own `RUN` command
> [BugFix] Move to use virtualenv over venv

- src/sparseml/pytorch/model_load/helpers.py
- src/sparseml/transformers/finetune/data/data_args.py
- src/sparseml/transformers/finetune/data/data_helpers.py
- src/sparseml/transformers/finetune/model_args.py
- src/sparseml/transformers/finetune/runner.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/finetune/training_args.py
- src/sparseml/transformers/sparsification/obcq/obcq.py
This PR sets up the finetuning script to be able to launch a one-shot flow. The change log for alternating finetuning was starting to pile up, so wanted to open this as a preliminary PR before adding in the alternating logic.
* Add oneshot path to `text_generation.py` (originally the finetuning script)
* Added `StageRunner` class for managing the different flows (train, eval, oneshot), rather than doing everything inside the entrypoint `text_generation.py` script
* Moved a bunch of helper functions that are now shared between `text_generation.py` and `obcq.py` (Eventually we can probably get rid of the OBCQ script)
test_oneshot_recipe.yaml
```
test_stage:
sparsity: 0.5
sequential_update: False
quantize: False
percdamp: 0.01
prunen: 0 …
```
> Enable One-Shot Launch from Finetuning Script

- src/sparseml/export/export.py
- src/sparseml/integration_helper_functions.py
- src/sparseml/pytorch/model_load/helpers.py
- src/sparseml/pytorch/utils/helpers.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/integration_helper_functions.py
- src/sparseml/transformers/sparsification/obcq/obcq.py
- src/sparseml/transformers/sparsification/trainer.py
- src/sparseml/transformers/utils/__init__.py
- src/sparseml/transformers/utils/helpers.py
- src/sparseml/transformers/utils/initializers.py
- src/sparseml/transformers/utils/load_task_model.py
- src/sparseml/transformers/utils/sparse_model.py
- tests/sparseml/export/transformers/test_generative_transformers.py
- tests/sparseml/transformers/obcq/test_obcq.py
- tests/sparseml/transformers/utils/test_initializers.py
The main functionality introduced by this PR enables loading and applying the recipe in the new format to the `text-generation` models. 
The notable changes are:
`src/sparseml/export/export.py` -> allowing the user to provide recipe explicitely to the exporter. If the recipe is not provided, but the `recipe.yaml` is located side-by-side with the model, there will be an attempt to load it automatically
`src/sparseml/pytorch/model_load/helpers.py` -> moving the `log_model_load` out of the `transformers.SparseModel`, otherwise we would get nasty import dependencies. Plus, it just make sense for it to be more general function.
`src/sparseml/transformers/integration_helper_functions.py` -> simplifying the `create_model` function and adapting it to the new changes …
> [Export Refactor][Transformers] Enable loading SparseModels

- src/sparseml/core/logger/utils/frequency_manager.py
- tests/sparseml/core/logger/utils/test_frequency_manager.py
This PR adds `frequency_type` ("epoch", "step", "batch") and `mode` ("exact", "on_change") to frequency manager:
```
The frequency type attribute controls what the frequency manager is tracking, e.g. if the frequency type
is "epoch", then the frequency manager will track the number of epochs that
have passed since the last log, if the frequency type is "step", then the
frequency manager will track the number of optimizer steps
```
```
The logging mode to use, either "on_change" or "exact",
"on_change" will log when the model has been updated since the last log,
"exact" will log at the given frequency regardless of model updates.
```
The frequency manager, now also keeps track of the last step when model 
was updated. Whenever updated the it is the responsibility of users to 
call …
> [Logger Framework][Add] mode and frequency type to FrequencyManager

- src/sparseml/export/export.py
- src/sparseml/export/export_data.py
- src/sparseml/export/validators.py
- src/sparseml/pytorch/image_classification/integration_helper_functions.py
- src/sparseml/pytorch/torch_to_onnx_exporter.py
- src/sparseml/pytorch/utils/helpers.py
- src/sparseml/transformers/integration_helper_functions.py
- src/sparseml/transformers/utils/load_task_dataset.py
- src/sparseml/transformers/utils/sparse_model.py
- tests/sparseml/export/image_classification/test_image_classification.py
- tests/sparseml/export/transformers/test_generative_transformers.py
- tests/sparseml/export/transformers/test_transformers.py
From now on, whenever we export the `text-generation` model, we are also able to load the appropriate dataset.
This is achieved by integrating @Satrat latest registry for LLM dataloaders into the transformers export.
```python
export(
source_path=source_path,
target_path=target_path,
task='text-generation',
num_export_samples=4,
**dict(
data_args=dict(
dataset_name="wikitext", dataset_config_name="wikitext-2-raw-v1"
)
),
)
```
```bash
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 52.54it/s]
...
2024-01-04 18:00:59 sparseml.export.export INFO     Exporting 4 samples...
4it [00:02,  1.61it/s]
2024-01-04 18:01:01 sparseml.export.export_data INFO     Exporting sample-inputs to /tmp/pytest-of-damian/pytest-0/test_export_samples_roneneldan0/target...
2024-01-04 18:01:01 …
```
> [Export][Transformers] Enable loading `text-generation` datasets

- src/sparseml/core/recipe/container.py
- src/sparseml/core/session.py
- src/sparseml/transformers/finetune/README.md
- src/sparseml/transformers/finetune/runner.py
- src/sparseml/transformers/finetune/session_mixin.py
- tests/sparseml/core/test_session.py
Previously the finetuning script would error out if no recipe was provided, because the event callbacks had no modifiers to trigger. This PR logs a warning if the user doesn't provide a recipe, but allows finetuning to run by skipping all lifecycle event callbacks if no recipe exists. Also fixing a small bug related to the "splits" argument parsing.
Asana ticket: https://app.asana.com/0/1203126676641557/1206292400209195/f 
This example script launches finetuning without a recipe:
```
from sparseml.transformers.finetune.text_generation import run_general
model = "Xenova/llama2.c-stories15M"
dataset_name = "open_platypus"
concatenate_data = False
do_train = True
do_eval = False
output_dir = "./output_finetune"
num_train_epochs=2
overwrite_output_dir = True
splits = "train"
run_general( …
```
> Allow Finetuning without a recipe

- src/sparseml/transformers/finetune/README.md
- src/sparseml/transformers/finetune/data/__init__.py
- src/sparseml/transformers/finetune/data/evolcodealpaca.py
- src/sparseml/transformers/finetune/data/gsm8k.py
- src/sparseml/transformers/finetune/data/ptb.py
- src/sparseml/transformers/finetune/data/ultrachat_200k.py
- tests/sparseml/transformers/finetune/data/test_dataset_loading.py
Adding 4 new datasets to the `TextGenerationDataset` registry: gsm8k, ptb, ultrachat_200k, evolcodealpaca. These datasets can now be used for finetuning.
Added a unit test for each dataset load
Note that evolcodealpaca seems to be broken on the hugging face side, this command fails, so I've skipped the test for now
```
from datasets import load_dataset
dataset = load_dataset("theblackcat102/evol-codealpaca-v1")
```
**Note:** In a future PR, I will deprecate the one-shot specific `TransformersDataset`, so both finetuning and oneshot use the same registry
> Expand Finetuning Dataset Registry to Match One-Shot

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/pruning/wanda/base.py
- src/sparseml/modifiers/pruning/wanda/pytorch.py
- src/sparseml/modifiers/utils/layer_compressor.py
Adding back the `sequential_update` flag to `SparseGPTModifier` and `WandaModifier`. Previously this flag affected whether or not we calibrate modules within a transformers block sequentially. Regardless of this flag we would always perform OBCQ sequentially across different transformer blocks.
In the updated FSDP compatible implementation, transformers blocks are calibrated in parallel with no option for sequential calibration. The new `sequential_update` flag affects whether transformer blocks are processed sequentially, modules within blocks are always calibrated in parallel. Note that running sequential updates requires a lot more computation, as the whole model forward pass it run `num_calibration_samples` times for each transformer block
> FSDP Compatible, Sequential SparseGPT

- src/sparseml/modifiers/utils/pytorch_helpers.py
Adding a progress bar to calibration forward pass, with the 7b models and a large calibration dataset it takes awhile to run
```
2024-01-11 14:51:53 sparseml.modifiers.pruning.wanda.pytorch INFO     Running SparseGPTModifier calibration with 1024 samples...
```
```
2024-01-11 14:51:53 sparseml.modifiers.pruning.wanda.pytorch INFO     Running SparseGPTModifier calibration with 1024 samples...
42%|██████████████████████████████████████████████▌                                                                | 430/1024 [07:20<10:08,  1.02s/it]
```
> One Shot Progress Bar

- src/sparseml/core/helpers.py
- src/sparseml/core/logger/logger.py
- src/sparseml/core/logger/utils/frequency_manager.py
- src/sparseml/pytorch/sparsification/modifier.py
This PR updates `LoggerManager` to use `FrequencyManager`
Few properties like `log_frequency` was moved
Add wrapper functions `model_updated` and `log_written` to `LoggerManager`
Based off of #1930
> [Use] frequency manager in logger

- src/sparseml/core/logger/logger.py
This PR updates the log format if step is `None`
giving us cleaner output
```python
def check_none_step():
logger_manager = LoggerManager()
logger_manager.system.info("info log", "Hello World!")
```
Output:
```bash
$ python local/scripts/dummy.py                                                                                                                               (remove-none-step|✚1⚑8)
Logging all SparseML modifier-level logs to sparse_logs/02-01-2024_09.39.49.log
2024-01-02 09:39:49 sparseml.core.logger.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/02-01-2024_09.39.49.log
python info log: Hello World!
```
Before, a `None` step was also logged
> [Fix] log format when step is `None`

- src/sparseml/core/logger/logger.py
- src/sparseml/core/logger/utils/frequency_manager.py
- src/sparseml/pytorch/utils/logger.py
- tests/sparseml/pytorch/utils/test_logger.py
Move(s) 
- string logging functions to SystemLoggingWrapper 
- metric logging functions to `MetricLoggingWrapper`
Test Code:
```python
def local_():
l = LoggerManager()
l.system.debug("debug log", "Hello World!")
l.system.warning("warn log", "Hello World!")
l.system.critical("crtitical log", "Hello World!")
l.system.info("info log", "Hello World!")
l.metric.log_hyperparams({"lr": 0.1, "batch_size": 32})
l.metric.log_scalar("loss", 0.1)
l.metric.log_scalars("losses", {"train": 0.1, "val": 0.2})
if __name__ == "__main__":
local_()
```
Output:
```
Logging all SparseML modifier-level logs to sparse_logs/02-01-2024_09.00.47.log
python debug log [None - 1704204047.9992712]: Hello World!
python warn log step None: Hello World!
python crtitical log step …
```
> [Add] Wrap System and Metric Logging into it's own classes

- src/sparseml/core/logger/logger.py
- src/sparseml/core/logger/utils/frequency_manager.py
- src/sparseml/core/modifier/stage.py
- src/sparseml/pytorch/utils/logger.py
- tests/sparseml/pytorch/utils/test_logger.py
This PR adds session based logs for the new framework
Output without this PR:
```bash
python local/e2e.py 
Logging all SparseML modifier-level logs to sparse_logs/19-12-2023_11.42.28.log
2023-12-19 11:42:28 sparseml.core.logger.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/19-12-2023_11.42.28.log
2023-12-19 11:42:29 sparseml.core.recipe.recipe INFO     Loading recipe from file /home/rahul/projects/sparseml/local/recipe.yaml
Epoch: 1 Loss: 0.8391762484203685 Accuracy: 0.6673114119922631
```
Output with this PR:
```bash
python local/e2e.py 
Logging all SparseML modifier-level logs to sparse_logs/19-12-2023_11.43.18.log
2023-12-19 11:43:18 sparseml.core.logger.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/19-12-2023_11.43.18.log
2023-12-19 …
```
> [Logger Refactor] Session based Logs

- src/sparseml/core/logger/logger.py
This PR adds a log method  with similar signature to https://github.com/pytorch/pytorch/blob/92998693a9455af6259cae468265f01cfff8810e/torch/utils/tensorboard/writer.py#L353 to our `LoggerManager`
Test:
```python
#local.py
from logging import INFO
def check_tb_type_logging_functions():
logger_manager = LoggerManager()
logger_manager.metric.add_scalar(value="Hello World!", level=INFO)
logger_manager.metric.add_scalars(values={1: "Hello World!"}, level=INFO, tag="my_scalar")
if __name__ == "__main__":
check_tb_type_logging_functions()
```
Output:
```bash
$ python local.py                                                                                                         (add-tb-like-logging-function|✚1…2⚑7)
2024-01-02 09:09:47 …
```
> [Logger Refactor] Add tb summary writer like functions

- src/sparseml/core/logger/logger.py
This PR adds a log method  with similar signature to https://github.com/wandb/wandb/blob/722f9737ce1a77b8970fef275047e8a0f4a1a68e/wandb/sdk/wandb_run.py#L1622 to our `LoggerManager`
Test:
```python
from logging import INFO
def check_wandb_type_logging_functions():
logger_manager = LoggerManager()
logger_manager.metric.log(data="Hello World!", level=INFO)
if __name__ == "__main__":
check_wandb_type_logging_functions()
```
Output:
```bash
$ python local/scripts/dummy.py                                                                                                                (add-wandb-like-logging-function|✚1⚑8)
Logging all SparseML modifier-level logs to sparse_logs/02-01-2024_09.16.29.log
2024-01-02 09:16:29 sparseml.core.logger.logger INFO …
```
> [Logger refactor] match wandb signature

- src/sparseml/yolov8/trainers.py
fixes issue at api level due to args not being set properly
see #1516 for fix at CLI level
> [cherry-pick][yolov8][fix] 'DetectionModel' object has no attribute 'args' (#1958)

- src/sparseml/transformers/finetune/data/base.py
- src/sparseml/transformers/finetune/data/data_args.py
- src/sparseml/transformers/finetune/data/data_helpers.py
- src/sparseml/transformers/finetune/data/evolcodealpaca.py
- src/sparseml/transformers/finetune/data/gsm8k.py
- src/sparseml/transformers/finetune/data/open_platypus.py
- src/sparseml/transformers/finetune/data/ultrachat_200k.py
- src/sparseml/transformers/finetune/session_mixin.py
- tests/sparseml/transformers/finetune/data/test_dataset_loading.py
Adding a new `streaming` configuration to finetuning(defined in `data_args.py`). When set to true, we stream shards of data from Hugging Face during training rather than downloading the whole dataset upfront.
**Note:** In streaming mode, `max_steps` must be defined and `num_train_epochs` will be ignored if specified. This is because a streamed dataset has no defined length.
```
sparseml.transformers.text_generation.train --model_name "Xenova/llama2.c-stories15M" --dataset_name "open_platypus" --output_dir "test_pretrain_out" --max_steps 1000 --splits train --streaming True
```
Training will run for 1000 batches, data is not downloaded and dataset mapping is not run upfront
And running with a large dataset now doesn't take forever:
```
sparseml.transformers.text_generation.train …
```
> [Pretraining] Support for Dataset Streaming during Finetuning

- src/sparseml/pytorch/sparsification/modifier.py
- tests/sparseml/core/test_session.py
Update failing tests in the `logger-framework` branch.
```bash
$ pytest '/home/rahul/projects/sparseml/tests/sparseml/core/test_session.py::TestSparseSession::test_apply_calls_lifecycle_initialize_and_finalize' -q --log-cli-level=critical
tests/sparseml/core/test_session.py::TestSparseSession::test_apply_calls_lifecycle_initialize_and_finalize PASSED                                                              [100%]
...
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================== 1 passed, 103 warnings in 3.49s ===========================================================================
```
Similarly PyTorch tests also pass; checked with `make test targets=pytorch`
> [Test Update] Fix failing tests after adding back old logger

- src/sparseml/transformers/finetune/runner.py
- tests/sparseml/transformers/finetune/data/test_dataset_loading.py
A bug in dataset loading was causing the following error when trying to load percentages of a split:
Input:
```
sparseml.transformers.text_generation.train --model_name Xenova/llama2.c-stories15M --dataset_name open_platypus --output_dir test_split --splits "train[60%:]" --num_train_epochs 1 --overwrite_output_dir True
```
Output:
```
File "/home/sadkins/sparseml/src/sparseml/transformers/finetune/data/data_helpers.py", line 73, in make_dataset_splits
raise ValueError("--do_train requires a train dataset")
ValueError: --do_train requires a train dataset
```
With this change we parse the split name using a regex, so `train`, `train[60%:]` and `{"train": "train[60%]"}` will all be supported as inputs. Adding in a unit test to test all these cases as well
> Fix Percentage Split Loads

- src/sparseml/export/validators.py
This PR fixes a bug because of which ort was required while importing anything from `sparseml.transformers.sparsification.obcq.export`
This is not ideal as ort should not be required to let's say import the following:
`from sparseml.transformers.sparsification.obcq.export import load_task_model`
The above code fails with the following error:
```bash
$ python -c 'from sparseml.transformers.sparsification.obcq.export import load_task_model'                                                                                (main|…2⚑3)
File "<string>", line 1, in <module>
File "/home/rahul/projects/sparseml/src/sparseml/transformers/__init__.py", line 57, in <module>
from .export import *
File "/home/rahul/projects/sparseml/src/sparseml/transformers/export.py", …
```
> [BugFix] Move ort import within function

- setup.py
- src/sparseml/export/validators.py
Now that ORT is not "required" by transformers explicitly unless validate_correctness is called this PR does two things:
- Remove ort from transformers dependency
- Raise apt install message when ort is used
> [BugFix] Remove ort from transformers dependency

- src/sparseml/core/logger/logger.py
This PR adds a time context manager to LoggerManager
```python
from time import sleep
from logging import INFO
logger_manager = LoggerManager()
with logger_manager.time('test', level=INFO):
sleep(1)
```
Output:
```bash
Logging all SparseML modifier-level logs to sparse_logs/17-01-2024_08.49.07.log
2024-01-17 08:49:07 sparseml.core.logger.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/17-01-2024_08.49.07.log
manager test: 1.000s
```
> [Logger Refactor] Add timer in logger manager

- src/sparseml/core/session.py
This PR fixes a test failure caused because we were logging losses on finalization. These lines were supposed to be deleted as part of a diiferent diff but were missed.
```
$ pytest -vv tests/sparseml/transformers/obcq/test_obcq.py                                                                   (main|✚1…1⚑2)
=========================================================== test session starts ===========================================================
platform linux -- Python 3.11.5, pytest-7.4.4, pluggy-1.3.0 -- /home/rahul/venvs/.base_venv/bin/python3.11
cachedir: .pytest_cache
rootdir: /home/rahul/projects/sparseml
configfile: pyproject.toml
plugins: flaky-3.7.0, anyio-4.2.0, mock-3.12.0
collected 5 items …
```
> [bug] remove missed lines that caused failure

- setup.py
Trying to clean up some dependencies in our packages that are unused or easy to loosen restrictions on similarly to deepsparse
* Notebooks aren't used anywhere and are a heavy dependency to require, so move `["jupyter>=1.0.0", "ipywidgets>=7.0.0"]` to a `sparseml[notebook]` optional dep
* `progressbar2` wasn't used anywhere searching for `progressbar`
* `scikit-image` wasn't used anywhere searching for `skimage`
* ~~In deepsparse we lifted the restriction on protobuf to allow for ONNX>=1.14 support https://github.com/neuralmagic/deepsparse/pull/1097~~ Raising Protobuf causes tensorboard logging errors
> Prune unnecessary SparseML dependencies

- src/sparseml/core/logger/logger.py
This PR fixes a bug where an error is raised while instantiating logger manager if tensor board is not installed
The fix was to only instantiate tensorboard logger if it is installed
Test:
Apply the following patch to emulate tensor board not being installed
```
diff --git a/src/sparseml/core/logger/logger.py b/src/sparseml/core/logger/logger.py
index 26e435a06e..35ed944167 100644
--- a/src/sparseml/core/logger/logger.py
+++ b/src/sparseml/core/logger/logger.py
@@ -46,6 +46,7 @@ except Exception as tensorboard_err:
SummaryWriter = object
tensorboard_import_error = tensorboard_err
+tensorboard_import_error = object
try:
import wandb
```
Run the following code:
```python
def main():
lm = LoggerManager()
lm.system.info("info message", "Hello World!") …
```
> [Bug] Init tensorboard logger only if available

- src/sparseml/core/session.py
The loss is stored in `state.loss` and not `state.loss.loss`
> [BugFix] Fix typo

- src/sparseml/core/recipe/recipe.py
Small change to how yaml is dumped to make nested lists more readable (needed for LogarithmicEqualization and SmoothQuant). This still isn't perfect, but there are limited output formatting options provided by the yaml library. This is just a cosmetic change, I tested that both the before and after recipe formats work fine as input oneshot recipes.
```yaml
SmoothQuantModifier:
smoothing_strength: 0.5
mappings:
- - - re:.*q_proj
- re:.*k_proj
- re:.*v_proj
- re:.*input_layernorm
- - - re:.*gate_proj
- re:.*up_proj
- re:.*post_attention_layernorm
```
```yaml
SmoothQuantModifier:
smoothing_strength: 0.5
mappings:
- - ['re:.*q_proj', 're:.*k_proj', 're:.*v_proj']
- re:.*input_layernorm
- - ['re:.*gate_proj', 're:.*up_proj']
- re:.*post_attention_layernorm
```
Asana ticket: …
> Clean up One-Shot Recipe Output

- src/sparseml/modifiers/utils/pytorch_helpers.py
https://github.com/neuralmagic/sparseml/commit/2e264e04760ca66266ce7249ad4cb71c6ec41c1f introduced a bug for quantization modifiers, we need to remove the padding column if it is unused to avoid a `TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'padding_mask'`
> Fix for unexpected column

- src/sparseml/transformers/finetune/text_generation.py
The`--precision` argument was being applied to the student model but not the teacher. This caused a type mismatch error during training. The fix is to cast the teacher to dtype provided by `--precision` (auto by default)
Before:
If `--precision float16`
```
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::Half != float
```
After:
Finetuning runs as expected
> Fix Dtype Casting for Finetuning Teacher

- integrations/huggingface-transformers/finetuning/example_fsdp_config.yaml
- src/sparseml/pytorch/utils/sparsification_info/configs.py
- src/sparseml/transformers/finetune/runner.py
- src/sparseml/transformers/finetune/text_generation.py
The input model was always being loaded to `oneshot_device` (default value `cuda:0`). This should not happen in FSDP mode, where the FSDP config determines model device mapping, or when running training/finetuning only. This was causing extra upfront memory usage loading the model on a single device
Also fixing 2 other small bugs: 
* the sparsification logger had a divide by zero error for some FSDP configs (`use_orig_params=True`),
* not accounting for the `padding_mask` column when running the dummy forward pass in FSDP mode
> Fixing FSDP Memory Load Issue

- src/sparseml/transformers/sparsification/obcq/export.py
Removes `model_type` from `SparseAutoModel.text_generation_from_pretrained` call
The old export flow was broken:
```bash
python src/sparseml/transformers/sparsification/obcq/export.py --task text-generation --sequence_length 4096 --model_path llama2.c-stories15M
...
...
File "/home/rahul/projects/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 543, in <module>
main()
File "/home/rahul/projects/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 530, in main
export(
File "/home/rahul/projects/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 508, in export
export_transformer_to_onnx(
File "/home/rahul/projects/sparseml/src/sparseml/transformers/sparsification/obcq/export.py", line 290, in …
```
> [Bug] Fix TypeError with old export flow

- src/sparseml/modifiers/distillation/output/pytorch.py
- src/sparseml/modifiers/distillation/utils/pytorch/kd_wrapper.py
- src/sparseml/pytorch/utils/sparsification_info/helpers.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/utils/fsdp/context.py
Previously we would force the teacher layer onto the same device as the student layer at initialization. This worked ok when we initialized modifiers before initializing FSDP but there are two problems with this
* we are only ever running inference on the teacher model, so there is no need to make FSDP deal with its gradients. We can save a lot of memory by leaving the teacher out of FSDP
* For alternating flows, we need to initialize modifiers after FSDP is applied. In this case, if we try to force the teacher onto the student layer we are likely to run out of memory because FSDP wasn't able to account for the extra memory during initialization
* load teacher with device_map=auto to spread it across GPUs before FSDP initialization. This allows FSDP to account for the teacher when …
> Reduce Distillation Memory Overhead

- src/sparseml/evaluation/__init__.py
- src/sparseml/evaluation/integrations/__init__.py
- src/sparseml/evaluation/integrations_config.yaml
- src/sparseml/evaluation/registry.py
- tests/sparseml/evaluation/__init__.py
- tests/sparseml/evaluation/test_registry.py
This PR adds a `SparseMLEvalRegistry` for registering evaluation integrations.
Note: during collection we only use the integration name to figure out the integration
Automated Tests
Based off of #1992 
---
- https://app.asana.com/0/0/1206432804121697
> [Add] SparseMLEvalRegistry

- setup.py
- src/sparseml/__init__.py
- src/sparseml/evaluation/__init__.py
- src/sparseml/evaluation/cli.py
- src/sparseml/evaluation/evaluator.py
- src/sparseml/evaluation/integrations/__init__.py
- src/sparseml/evaluation/integrations_config.yaml
- src/sparseml/evaluation/registry.py
- tests/sparseml/evaluation/__init__.py
- tests/sparseml/evaluation/test_evaluator.py
- tests/sparseml/evaluation/test_registry.py
This PR adds a CLI for `sparseml.eval`
```
$ sparseml.eval --help                                                                                (add-eval-cli|✚1…2)
Usage: sparseml.eval [OPTIONS] [INTEGRATION_ARGS]...
Options:
--model_path PATH               A path to a local directory containing
pytorch model(including all the auxiliary
files) or a SparseZoo/HugginFace stub
[required]
-d, --dataset TEXT              The name of dataset to evaluate on. The user
may pass multiple datasets names by passing
the option multiple times.
-i, --integration TEXT          Name of the evaluation integration to use.
Must be a valid integration name that is
registered in the evaluation registry
[required]
-s, --save_path TEXT            The path to save the evaluation results. The
results will be …
```
> [Eval] Add eval cli

- src/sparseml/transformers/utils/sparse_model.py
Temporarily changing the log level to ERROR when loading the model, this avoids the really long printout of unexpected/missing keys when loading a quantized model before the structure has been applied
Asana ticket: https://app.asana.com/0/1206109050183159/1206513598188995/f
```
from sparseml.transformers.utils.sparse_model import SparseAutoModelForCausalLM
model = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-llama2_chat_llama2_pretrain-base_quantized", device_map="auto")
```
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.11s/it]
Some weights of the model checkpoint at /home/ubuntu/.cache/sparsezoo/neuralmagic/llama2-7b-open_platypus_orca_llama2_pretrain-pruned40_quantized/training were not used when initializing …
```
> Reduce Log Clutter for Quantized Models

- src/sparseml/export/export.py
When multiple exports that require recipe structure applications are performed in the same python session, the recipes get stacked in the SparseSession and are applied multiple times. 
The fix is to create a new session at the start of export, then clear it afterwards, so we aren't reusing recipes
Asana ticket: https://app.asana.com/0/1206109050183159/1206584891540686/f
This example would previously fail on the second export:
```
from sparseml import export
for i in range(3):
output_dir = "./test_export_" + str(i)
export("zoo:codellama-7b-evolcodealpaca_codellama_pretrain-pruned60_quantized", task="text-generation", integration='transformers', target_path=output_dir)
```
Now it successfully completes all the exports
> Fix Export Recipe Bug

- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/finetune/training_args.py
- tests/sparseml/transformers/finetune/test_finetune.py
When running sparseML commands such as `sparseml.transformers.apply/train/oneshot` in a Jupyter notebook, running multiple commands in a row would fail because the SparseSession object was persisting between runs.
To fix this we call `session_manager.create_session()` at the beginning of each run to clear data from the previous run. Also made this a cmd line arg in case the user wants the force the session to persist
Unit test `test_oneshot_then_finetune` previously required a session reset between sections, now that this is handled internally its no longer required.
> Reset SparseSession Between Runs

- src/sparseml/transformers/finetune/data/custom.py
Helper to get an example going on colab.
Bug on remove columns, only ran if preprocessing func existed, which remove col should not depend on.
> remove column should not depend on preprocessing func

- src/sparseml/evaluation/integrations/perplexity.py
- src/sparseml/utils/helpers.py
Before this PR evaluate perplexity functionality assumed their can only be one text column in the dataset, however this is not true for `openai_humaneval` dataset. This PR adds support for that + does some more cleanup with the perplexity eval
Test command:
```python
def perplexity_request():
from sparseml import evaluate
stub = "/home/rahul/.cache/sparsezoo/neuralmagic/llama2-7b-ultrachat200k_llama2_pretrain-pruned60_quantized/training"
datasets = "openai_humaneval"
integration = "perplexity"
result = evaluate(
stub,
datasets=datasets,
integration=integration,
text_column_name=["prompt", "canonical_solution"],
limit=10
)
print(f"{integration} result:", result, sep="\n")
```
Also added this support with the cli
```bash
sparseml.evaluate …
```
> [Support] Evaluate `openai_humaneval` support

- src/sparseml/evaluation/README.md
- src/sparseml/evaluation/integrations/lm_evaluation_harness.py
Some evaluation integrations require additional packages to be installed. The following instructions detail how to install the necessary packages for lm-eval integration
`lm-eval` is a package that provides a harness for evaluating language models. It is used by the `lm-evaluation-harness` integration.
This package has installs transformers and torch versions that are incompatible with the versions required by [SparseML] . To use this integration kindly follow the following steps to install the correct versions of the packages.
Step 1: Make a new virtual environment + activate it
```bash
python3.11 -m venv sparseml-venv
source sparseml-venv/bin/activate
```
Step 2: Install `lm-eval` package
```bash
pip install lm-eval==0.4.1
```
Step 3: Uninstall transformers package, we will install the …
> Use PyPi version to install `lm-eval`

- src/sparseml/evaluation/registry.py
Before this PR the error messages for `sparseml.evaluate` were somewhat obscure, the user had to scroll through the error message to find the missing package error.
```bash
$ sparseml.evaluate \                                                                                     (update-lm-eval-to-0.4.1↑1|…3⚑5)
"mgoin/llama2.c-stories15M-quant-pt" \
--dataset hellaswag \
--integration lm-evaluation-harness \
--limit 1 # for a quicker test
2024-02-23 15:42:47 sparseml.evaluation.cli INFO     Datasets to evaluate on: hellaswag
Batch size: 1
Additional integration arguments supplied: {}
2024-02-23 15:42:47 sparseml.evaluation.registry WARNING  Collection of lm-evaluation-harness integration for eval failed
File …
```
> [Update] better error message for sparseml evaluate

- src/sparseml/experimental/sparsegpt/examples/llama2/recipes/llama_recipe.yaml
- src/sparseml/transformers/finetune/callbacks.py
- src/sparseml/transformers/finetune/session_mixin.py
- src/sparseml/transformers/finetune/trainer.py
- src/sparseml/transformers/sparsification/obcq/README.md
- src/sparseml/transformers/sparsification/obcq/example_llama.yaml
- src/sparseml/transformers/sparsification/obcq/example_mistral.yaml
- src/sparseml/transformers/sparsification/question_answering.py
- src/sparseml/transformers/sparsification/trainer.py
- tests/sparseml/transformers/finetune/test_quantization.yaml
- tests/sparseml/transformers/obcq/test_repeats.py
- tests/sparseml/transformers/obcq/test_tiny.yaml
Accounts for the fact that:
- `SiLUActivation` is being renamed to `SiLU`
- `trainer` no longer has the attribute `use_cuda_amp`
> [Forkless SparseML Transformers] Updating SparseML to be compatible with the forkless transformers

- .gitignore
- src/sparseml/core/helpers.py
- src/sparseml/core/logger/logger.py
- src/sparseml/core/logger/utils/frequency_manager.py
- src/sparseml/core/session.py
- src/sparseml/core/state.py
- tests/sparseml/core/logger/utils/test_frequency_manager.py
- tests/sparseml/core/test_helpers.py
- tests/sparseml/core/test_session.py
- Add preliminary changes that were missed
- Propagate step while logging loss
- Fix WANDB logging
- Use LifeCycleCallbacks for logging loss and model info
- Update tests
Test Script:
```python
from sparseml.transformers import train
model = "Xenova/llama2.c-stories15M"
teacher_model = "Xenova/llama2.c-stories15M"
dataset_name = "open_platypus"
concatenate_data = False
output_dir = "./output_finetune"
recipe = "/home/ubuntu/projects/sparseml/local/recipes/llama_gmp.yaml"
num_train_epochs=2
overwrite_output_dir = True
splits = {
"train": "train[:10%]",
}
train(
model=model,
distill_teacher=teacher_model,
dataset=dataset_name,
output_dir=output_dir,
recipe=recipe,
num_train_epochs=num_train_epochs,
overwrite_output_dir=overwrite_output_dir,
concatenate_data = concatenate_data,
splits = …
```
> [Logger] Use lifecycle callbacks for logging

- src/sparseml/transformers/utils/sparse_model.py
- src/sparseml/utils/fsdp/context.py
When we download a model from the zoo for the first time, all processes are going to try and download it at once. What we want instead is for the main process to download the files and the others to just pull from the cache. This PR uses Accelerator's main_process_first() context manager to do this.
**NOTE:*** Even with this fix, if we have more than 2 processes the download still gets corrupted because all the non-main processes are calling the SparseZoo API at the same time. We have seen this same error in GHA transformers unit tests and it is caused by a concurrency issue with SparseZoo. @horheynm is working on this part of the issue
Asana ticket: https://app.asana.com/0/1206109050183159/1206698210421769/f
test.py
```
from sparseml.transformers import compress, …
```
> Fix Pt. 1 for Multi-Process Zoo Stub Downloads

- src/sparseml/evaluation/cli.py
`dataset` cli arg updated to `datasets`
```bash
(.venv) ➜  sparseml git:(main) ✗ sparseml.evaluate \
"roneneldan/TinyStories-1M" \
--datasets "openai_humaneval" \
--integration "perplexity" \
--text_column_name prompt
2024-03-01 12:54:14 sparseml.evaluation.cli INFO     Datasets to evaluate on: openai_humaneval
Batch size: 1
Additional integration arguments supplied: {'text_column_name': 'prompt'}
2024-03-01 12:54:15 sparseml.evaluation.registry INFO     Auto collected perplexity integration for eval
2024-03-01 12:54:15 sparseml.transformers.utils.helpers INFO     model_path is a huggingface model id. Attempting to download recipe from https://huggingface.co/
2024-03-01 12:54:15 sparseml.transformers.utils.helpers INFO     Found recipe: recipe.yaml for model id: roneneldan/TinyStories-1M. …
```
> [Fix] dataset arg

- src/sparseml/transformers/finetune/data/base.py
- src/sparseml/transformers/finetune/data/custom.py
- src/sparseml/transformers/finetune/data/data_helpers.py
- src/sparseml/transformers/finetune/data/evolcodealpaca.py
- src/sparseml/transformers/finetune/data/gsm8k.py
- src/sparseml/transformers/finetune/data/open_platypus.py
- src/sparseml/transformers/finetune/runner.py
There were a few issues:
* Not checking if columns exist before removing them
* Weren't handling the case of Dataset, only DatasetDict
* Don't remove prompt column from custom dataset
Asana ticket: https://app.asana.com/0/1206109050183159/1206717149982745/f
Preprocessing function now working as intended, and training starts
```
from sparseml.transformers import (
SparseAutoModelForCausalLM, SparseAutoTokenizer, load_dataset, compress
)
model = SparseAutoModelForCausalLM.from_pretrained(
"/nm/drive0/sadkins/models/llama2-7b-open_platypus_orca_llama2_pretrain-pruned40/training",
device_map="auto",
)
tokenizer = SparseAutoTokenizer.from_pretrained(
"/nm/drive0/sadkins/models/llama2-7b-open_platypus_orca_llama2_pretrain-pruned40/training"
)
dataset = …
```
> Custom Dataset Bug Fixes

- .github/workflows/test-check.yaml
- setup.py
- src/sparseml/modifiers/quantization/utils/fake_quant_wrapper.py
The FakeQuantizeWrapper had an import error in pytorch 1.9. Fixing this error, and also updating the GHA checks to check for changes in sparseml/modifiers before running the pytorch test suite.
> FakeQuant 1.9 Compatibility

- src/sparseml/modifiers/pruning/wanda/base.py
- src/sparseml/modifiers/pruning/wanda/pytorch.py
- tests/sparseml/pytorch/modifiers/obcq/test_pytorch.py
Previously we restricted the user from specifying target layers as a regex, so the mapping between sparsities and layers was explicit. This restriction doesn't make sense with OWL, where we are calculating the layer-wise sparsities from the list of layers. This PR removes the regex restriction entirely, we only check that the number of sparsities matches the number of layers
```python
from sparseml.transformers import (
SparseAutoModelForCausalLM, SparseAutoTokenizer, load_dataset, compress
)
model = SparseAutoModelForCausalLM.from_pretrained(
"zoo:llama2-7b-open_platypus_orca_llama2_pretrain-base",
device_map="auto",
)
tokenizer = SparseAutoTokenizer.from_pretrained(
"zoo:llama2-7b-open_platypus_orca_llama2_pretrain-base"
)
recipe = """
pruning_stage:
run_type: oneshot …
```
> Support for OWL Regex Layers

- src/sparseml/evaluation/integrations/lm_evaluation_harness.py
Test Code:
```python
from sparseml import evaluate
stub = "zoo:llama2-7b-llama2_pretrain-base"
dataset=["arc_challenge", "winogrande"]
integration="lm-eval-harness"
res = evaluate(stub, datasets=dataset, integration=integration, limit=10)
print(res)
```
Output:
```bash
CUDA_VISIBLE_DEVICES=6 python local/scripts/eval.py
2024-03-04 22:58:50 sparseml.evaluation.registry INFO     Auto collected lm-eval-harness integration for eval
2024-03-04:22:58:50,713 INFO     [registry.py:100] Auto collected lm-eval-harness integration for eval
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████| 414/414 [00:00<00:00, 205kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████| 776/776 [00:00<00:00, 848kB/s] …
```
> [Bug] Explicitly pass in the tokenizer for non-downloaded zoo stubs

- src/sparseml/core/logger/logger.py
- src/sparseml/utils/helpers.py
A bug was revealed where if a `wandb` directory was present (at the level of running script); `WANDBLogger.available()` would return `True` as it only relied on import; this would inturn lead to uninteded creation of this logger object that would fail down the line.
This PR fixes that.
* Utility method to check if a package is available and not just a directory
* Use that function to check for wandb availability
directory structure (Note has a `wandb` directory):
```bash
$ tree -d -L 1                            
.
├── docker
├── docs
├── integrations
├── local
├── nm_temp_test_logs
├── research
├── sparse_logs
├── src
├── status
├── tensorboard
├── tests
├── utils
└── wandb
```
plain import would still work:
`$ python -c 'import wandb'`
But `WANDBLogger` will not allow instanciation …
> [BugFix] Stronger check for wandb availability

- src/sparseml/transformers/finetune/model_args.py
- src/sparseml/transformers/finetune/text_generation.py
- src/sparseml/transformers/finetune/training_args.py
Asana ticket: https://app.asana.com/0/1206109050183159/1206788571042422/f 
We had missed support for passing in an instantiated teacher to the finetuning code, this PR adds in it 
script would fail on main, training starts as intended here:
```python
from sparseml.transformers import compress, SparseAutoModelForCausalLM, SparseAutoTokenizer, load_dataset
model = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base", device_map="auto")
teacher = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-open_platypus_orca_llama2_pretrain-base", device_map="auto")
tokenizer = SparseAutoTokenizer.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base")
recipe = "zoo:llama2-7b-ultrachat200k_llama2_pretrain-pruned40"
dataset = …
```
> Allow Passing in Instantiated Teacher

- src/sparseml/modifiers/utils/layer_compressor.py
On main we were getting a spike in GPU memory when cleaning up compression for a transformer layer. This was causing an OOM error with FSDP oneshot: https://app.asana.com/0/1206109050183159/1206698210421769/f 
This was caused because the set_layer function triggers a parameter gather. We were calling set_layer on the whole model when it should only be called on the current transformer layer. Fixing this resolved the memory spike, now the process can complete on 48GB GPUs
```
from sparseml.transformers import compress, SparseAutoModelForCausalLM, SparseAutoTokenizer, load_dataset
model = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base")
tokenizer = SparseAutoTokenizer.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base") …
```
> Fix One-Shot FSDP Memory Spike

- integrations/huggingface-transformers/finetuning/example_fsdp_config.yaml
- src/sparseml/modifiers/pruning/constant/pytorch.py
- src/sparseml/transformers/finetune/runner.py
- src/sparseml/transformers/finetune/session_mixin.py
The following SparseZoo recipes were causing OOM errors even with FSDP:
* "zoo:llama2-7b-ultrachat200k_llama2_pretrain-pruned40"
* "zoo:llama2-7b-ultrachat200k_llama2_pretrain-pruned40_quantized"
The fix was to offload weights to CPU when gathering FSDP params during modifier initialization and finalization
Tested on 6 48GB GPUs. Example only runs a few training samples for ease of testing.
```python
from sparseml.transformers import compress, SparseAutoModelForCausalLM, SparseAutoTokenizer
model = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base")
teacher = SparseAutoModelForCausalLM.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-base")
tokenizer = SparseAutoTokenizer.from_pretrained("zoo:llama2-7b-ultrachat200k_llama2_pretrain-bas …
```
> Fix for OOM Errors during Ultrachat200k Finetuning

- src/sparseml/transformers/finetune/runner.py
- src/sparseml/utils/fsdp/helpers.py
This description details a bugfix for an issue encountered when loading quantized models that were trained using Fully Sharded Data Parallel (FSDP). 
The issue originated from the process of quantization, during which we updated layer names and saved them using our custom implementation instead of `accelerate`. This approach resulted in an incorrectly saved `state_dict`, as each tensor had device information associated with it. Consequently, the model could not be loaded properly using the transformer's `AutoModel.from_pretrained(...)` method.
The modifications in this update address these complications, ensuring that quantized models trained using FSDP can now be saved and loaded correctly.
- [Asana Ticket](https://app.asana.com/0/1206109050183159/1206841566630295/f)
- Relevant code …
> [Bugfix] for saving quantized models trained using fsdp

- integrations/huggingface-transformers/finetuning/example_fsdp_config.yaml
- src/sparseml/modifiers/distillation/utils/pytorch/model_wrapper.py
- src/sparseml/transformers/finetune/session_mixin.py
We were previously having to set the teacher to eval mode on each forward pass in distillation. This ended up being caused by how we were wrapping the teacher model into the student. By overwriting the train() function in `KDModelWrapper` to only affect the student, we keep the teacher in eval_mode for the whole run.
This gives a minor speed boost but doesn't fully fix the runtime discrepancies between llama-recipes and SparseML. Running bf16 distillation on a llama1.1b model on GPU6(4 active GPUs, device batch size 8) we get:
* 1.6sec/batch on main
* 1.5sec/batch on this branch
* 1.1sec/batch on llama-recipes
> Fix Distill Teacher Eval Mode

- src/sparseml/pytorch/sparsification/pruning/modifier_pruning_rigl.py
- tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_rigl.py
Current RigL code uses the param scorer to enforce custom sparsity patterns (Erdos-Renyi, ERK) on the masks. This PR instead passes the ER/ERK sparsity targets directly to the mask creator, to ensure that the mask distribution exactly matches the targets (no rounding errors or other effects).
Tested: did a few runs with these changes and confirmed that the quality matches previous implementation. Updated tests.
> Clean up global RigL sparsities to be exact

- setup.py
future releases of nm-yolov5 are not currently planned, moving forward the version requirement will be changed to `<=` so we do not need to create empty releases for compatibility
> relax nm-yolov5 requirement

- src/sparseml/export/validators.py
- src/sparseml/transformers/compression/compressors/sparse_bitmask.py
Changing dictionary update from `|=` to `.update`
> Fix Python 3.8 Compatibility 

- src/sparseml/export/validators.py
- src/sparseml/transformers/compression/compressors/base.py
- src/sparseml/transformers/compression/utils/safetensors_load.py
- src/sparseml/transformers/sparsification/sparse_model.py
The original compression PR neglected to test loading a compressed model from the hub, and was only working with local compression loads. This PR adds support for loading a compressed model from the hub with `SparseAutoModelForCausalLM.from_pretrained`. 
Loads the compressed model from the hub, checks the decompressed weights match the original
```python
from sparseml.transformers import SparseAutoModelForCausalLM, SparseAutoTokenizer
import torch
ORIG_MODEL_PATH = "neuralmagic/TinyLlama-1.1B-Chat-v1.0-pruned2.4"
COMPRESSED_MODEL_PATH = "mgoin/TinyLlama-1.1B-Chat-v1.0-pruned2.4-compressed"
model = SparseAutoModelForCausalLM.from_pretrained(ORIG_MODEL_PATH, device_map="auto", torch_dtype="auto")
tokenizer = SparseAutoTokenizer.from_pretrained(ORIG_MODEL_PATH)
model_compressed = …
```
> Support for Decompressing Models from HF Hub

- src/sparseml/transformers/sparsification/sparse_model.py
- src/sparseml/transformers/utils/helpers.py
Identified a bug in the main branch where the model state fails to reload when using quantized stubs with `SparseAutoModelForCausalLM.from_pretrained(...)`. The issue was due to the `reload_model_state` method expecting weight files in a local directory, not accounting for remotely hosted model directories.
Propose downloading the model directory before invoking `reload_model_state` to ensure weight files are available locally for model state reload.
Tested with the following script, confirming the fix resolves the issue:
```python
from sparseml.transformers import SparseAutoModelForCausalLM
model_path = "mgoin/llama2.c-stories15M-quant-pt"
m1 = SparseAutoModelForCausalLM.from_pretrained(model_path)
```
**Before the Fix**:
Model state fails to reload due to missing local weight files, as …
> [BugFix] Model State Reload with Quantized Stubs in SparseAutoModelForCausalLM

- tests/sparseml/transformers/sparsification/modification/conftest.py
Because the original mistral models are gated now
> Use an open source copy of mistral model

- setup.py
- src/sparseml/core/modifier/modifier.py
- src/sparseml/core/recipe/base.py
- src/sparseml/core/recipe/modifier.py
- src/sparseml/core/recipe/recipe.py
- src/sparseml/core/recipe/stage.py
- src/sparseml/exporters/transforms/kv_cache/configs.py
- src/sparseml/framework/info.py
- src/sparseml/integration_helper_functions.py
- src/sparseml/modifiers/quantization/utils/quantization_scheme.py
- src/sparseml/pytorch/sparsification/quantization/quantization_scheme.py
- src/sparseml/pytorch/utils/sparsification_info/configs.py
- src/sparseml/sparsification/info.py
- src/sparseml/sparsification/model_info.py
- tests/integrations/image_classification/args.py
- tests/integrations/transformers/args.py
- tests/sparseml/core/recipe/test_recipe.py
- tests/sparseml/framework/test_info.py
This PR updates sparseml pydantic support to v2
Steps:
- use pydantic's official bump pydantic tool for pre-liminary migration
- update setup.py
- fix model configs and typing
- update recipe serialization, also fixes a bug with original serialization
Test methodology:
- make test targets=torch passes locally
- sanity check with a dummy recipe containing multiple stages and multiple groups within each stage
- test script attached with description
Sanity Script:
```python
from sparseml.core import Recipe
import pprint as pp
import yaml
pp = pp.PrettyPrinter(indent=4)
recipe = """
first_oneshot_stage:
ConstantPruningModifier:
start_epoch: 0
end_epoch: 5
targets: __ALL_PRUNABLE__
MagnitudePruningModifier:
start_epoch: 5
end_epoch: 10
init_sparsity: 0.1
final_sparsity: 0.5 …
```
> Update pydantic support to v2

- src/sparseml/core/recipe/recipe.py
The update to pydantic V2 deleted a feature of recipe export that would resolve clashing stage names. This caused `tests/sparseml/transformers/obcq/test_repeats.py:test_consecutive_runs()` to fail because we apply two recipes with stages labeled `test_stage`, and the stage name keys must be unique for serialization.
Fixed by adding the old indexing code back in to the refactored export code and the unit test now passes
> Fix Consecutive Recipe Application Test

- src/sparseml/transformers/finetune/data/gsm8k.py
There's no need of a period between the question and the line break since the question will contain its own punctuation (normally interrogation mark). The period also doesn't match the lm-evaluation-harness template and can lead to lower accuracy.
> Fix GSM template

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/pruning/wanda/base.py
- src/sparseml/modifiers/pruning/wanda/pytorch.py
This PR refactors `SparseGPT` modifier(s) to remove their inheritance from `Wanda`, making `SparseGPT` fully independent. The change improves the modularity of the SparseGPT architecture, making it more straightforward to maintain and extend/modify
Test plan: Ran all the tests, + a manual one shot script on `HuggingFaceM4/tiny-random-LlamaForCausalLM`
> Split `Wanda` and `SparseGPT`

- .github/workflows/build-wheel-and-container.yml
- .github/workflows/test-check.yaml
- .github/workflows/test-wheel-push-to-internal.yml
- Continuing issues with aws so swapping testing and build runners to use k8
- Removing the internal pypi step as will be replaced with dumbpypi
> [GHA] Swap aws runners; remove internal pypi step

- src/sparseml/modifiers/obcq/utils/sgpt_wrapper.py
scales and zero points were not accounting for correct groups when iterating over the input channel dimension
> fix group size support for sgpt_wrapper

- src/sparseml/transformers/finetune/data/base.py
- src/sparseml/transformers/utils/sparse_model.py
- src/sparseml/version.py
Enabling one-shot for non `text-generation` models in 1.7. Changes:
- user can now override the `labels`, by providing their own `labels` in the input dataset. This is crucial, since the labels must match the actual output of the model (`text-generation` models expect `(batch_size, num_tokens, vocab_size)` outputs, other `transformers` may expect for instance `(batch_size, num_classes)`.
```python
from sparseml.transformers import oneshot, SparseAutoModel
from datasets import load_dataset
from transformers import AutoConfig, AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from typing import Union
from evaluate import evaluator
from sparseml import export
import sparseml.core.session as session_manager
model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest" …
```
> [1.7] Enable one-shot flow for non-LLMs

- src/sparseml/modifiers/quantization/gptq/utils/gptq_wrapper.py
- src/sparseml/modifiers/utils/constants.py
- tests/sparseml/transformers/obcq/test_consecutive_runs.py
Recently a bug was revealed, where if GPTQ modifier was applied consecutively after SparseGPT, the weight sparsity mask was not being respected, this PR fixes that by preserving the mask, we do this automatically if the weight sparsity is greater than `SPARSITY_THRESHOLD` which has been set to `5%` for now.
Credits to @Satrat and @abhinavnmagic for proposing the fix
The unit test for consecutive application now runs w/o having to increase the relative tolerance which was done as a part of #2272
> Preserve sparsity GPTQ

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/sgpt_wrapper.py
- src/sparseml/modifiers/quantization/gptq/utils/gptq_wrapper.py
- src/sparseml/modifiers/utils/constants.py
- tests/sparseml/transformers/obcq/test_consecutive_runs.py
This PR incorporates changes from @abhinavnmagic's PR https://github.com/neuralmagic/sparseml/pull/2222 into new modifier UX
We introduce a new argument `preserve_sparsity_mask` in `SparseGPTModifier` which can be used to extend or ignore the base weight mask during SparseGPT application
Test Recipe:
```yaml
test_stage:
sparsity: 0.5
percdamp: 0.01
mask_structure: "2:4"
targets: ["re:model.layers.\\d*$"]
preserve_sparsity_mask: true
```
> Preserve sparsity SPARSEGPT

- src/sparseml/modifiers/obcq/utils/sgpt_wrapper.py
fixes the input dim value to be relative to the entire weight, not just the W1 slice which is incorrect (resets every blocksize slice)
> [GTPQ] fix slice of scale/zp for group_size

- src/sparseml/evaluation/integrations/lm_evaluation_harness.py
Imports were out of date, and we were displaying error messages from pre forkless transformers.
previously failed with an import error, now runs to completion as expected after installing lm-eval
```
sparseml.evaluate /network/sadkins/llama1.1b_W4A16_channel_compressed -d wikitext -i lm-evaluation-harness
```
> Fixes for sparseml.evaluate

- src/sparseml/pytorch/model_load/helpers.py
- src/sparseml/version.py
As confirmed by @shubhra, this commit needs to be cherry-picked into 1.7 to work with the quantized model, whenever the quantization type specified in the recipe is channel-wise.
> [Cherry-Pick] Make reloading compatible with safetensors 

- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/sgpt_wrapper.py
- src/sparseml/modifiers/quantization/gptq/__init__.py
- src/sparseml/modifiers/quantization/gptq/base.py
- src/sparseml/modifiers/quantization/gptq/pytorch.py
- src/sparseml/modifiers/quantization/gptq/utils/__init__.py
- src/sparseml/modifiers/quantization/gptq/utils/gptq_wrapper.py
- src/sparseml/modifiers/utils/contants.py
This PR introduces a structural change by separating concerns between quantization and sparsification. A new `GPTQModifier` is extracted from the existing `SparseGPTModifier`. This ensures that each class now has a focused responsibility — `GPTQModifier` manages quantization, while `SparseGPTModifier` is dedicated to sparsification.
- **Extraction of `GPTQModifier`**: Carved out from `SparseGPTModifier`, this new class handles all aspects related to quantization, including arguments specifically for quantization processes.
- **Refinement of `SparseGPTModifier` and `SparseGPTWrapper`**: These have been updated to solely focus on sparsification. All quantization-related functionalities have been removed.
- **Creation of `GPTQWrapper`**: Implemented to apply quantization using  OBQ
- …
> Split SparseGPT and GPTQ modifiers

- integrations/huggingface-transformers/tutorials/text-generation/example_alternating_recipe.yaml
- src/sparseml/modifiers/obcq/base.py
- src/sparseml/modifiers/obcq/pytorch.py
- src/sparseml/modifiers/obcq/utils/sgpt_wrapper.py
- src/sparseml/modifiers/quantization/gptq/__init__.py
- src/sparseml/modifiers/quantization/gptq/base.py
- src/sparseml/modifiers/quantization/gptq/pytorch.py
- src/sparseml/modifiers/quantization/gptq/utils/__init__.py
- src/sparseml/modifiers/quantization/gptq/utils/gptq_wrapper.py
- src/sparseml/modifiers/utils/contants.py
- src/sparseml/transformers/sparsification/obcq/README.md
- src/sparseml/transformers/sparsification/obcq/example.yaml
- src/sparseml/transformers/sparsification/obcq/example_llama.yaml
- src/sparseml/transformers/sparsification/obcq/example_mistral.yaml
- tests/sparseml/transformers/compression/recipes/new_quant_full.yaml
- tests/sparseml/transformers/compression/recipes/new_quant_weight.yaml
- tests/sparseml/transformers/compression/recipes/old_quant_full.yaml
- tests/sparseml/transformers/compression/recipes/old_quant_weight.yaml
- tests/sparseml/transformers/finetune/test_alternate_recipe.yaml
- tests/sparseml/transformers/obcq/recipes/additional_sparsity.yaml
- tests/sparseml/transformers/obcq/recipes/quant.yaml
- tests/sparseml/transformers/obcq/recipes/quant_and_sparse.yaml
- tests/sparseml/transformers/obcq/recipes/sparse.yaml
- tests/sparseml/transformers/obcq/recipes/test_tiny2.yaml
- tests/sparseml/transformers/oneshot/oneshot_configs/recipes/recipe.yaml
- tests/sparseml/transformers/oneshot/oneshot_configs/tiny_stories_conf1.yaml
- tests/sparseml/transformers/oneshot/oneshot_configs/tiny_stories_conf4.yaml
This PR updates test recipes and readme to use new GPTQ modifier for quantization
> [GPTQ Modifier UX] Update tests to use GPTQModifier for obcq style quantization

- .github/workflows/test-check.yaml
- src/sparseml/modifiers/quantization/gptq/pytorch.py
- tests/sparseml/pytorch/modifiers/pruning/sparsegpt/test_pytorch.py
- tests/sparseml/transformers/obcq/recipes/quant.yaml
- tests/sparseml/transformers/obcq/recipes/quant_and_sparse.yaml
- tests/sparseml/transformers/obcq/test_sgpt_defaults.py
This PR makes main green again by:
1) Install compressed tensors from source wherever transformers deps are needed
2) Apply a commit that was missed (for transformers tests)
> Fix errors introduced by GPTQ UX

- .github/workflows/test-nightly.yml
- .github/workflows/test-weekly.yml
- tests/sparseml/transformers/finetune/finetune_custom/config1.yaml
- tests/sparseml/transformers/finetune/finetune_custom/config2.yaml
- tests/sparseml/transformers/finetune/finetune_custom/gpu/gpu_config.yaml
- tests/sparseml/transformers/finetune/finetune_oneshot_configs/config.yaml
- tests/sparseml/transformers/finetune/finetune_oneshot_configs/gpu/gpu_config.yaml
- tests/sparseml/transformers/finetune/test_oneshot_then_finetune.py
- tests/sparseml/transformers/obcq/obcq_configs/completion/gpu/llama_7b_quant.yaml
- tests/sparseml/transformers/obcq/obcq_configs/completion/gpu/llama_7b_quant_and_sparse.yaml
- tests/sparseml/transformers/obcq/obcq_configs/completion/gpu/llama_7b_sparse.yml
- tests/sparseml/transformers/obcq/obcq_configs/sparse/gpu/llama_7b_sparse.yaml
- tests/sparseml/transformers/obcq/test_obcq_completion.py
- tests/sparseml/transformers/obcq/test_obcq_sparsity.py
- tests/testing_utils.py
- Adds workflows which run weekly and nightly tests 
- Currently set-up to run integration tests under the `transformers` folder. Specifically for oneshot and finetune
- Any test with a config file where the cadence has been set to nightly or weekly will run
- Using 2 `A6000` GPUS
- Weekly tests take about 1.5 hours
- Nightly tests take half hour to run
- Nightly test will soon be triggered by the nightly build workflow, set-up here:  https://github.com/neuralmagic/sparseml/pull/2270
- Nightly tests will run daily at 8 pm
- Weekly tests will run weekly on Sunday at 8 pm
> [GHA] Add workflow files to run weekly and nightly tests/run oneshot and finetune llama-7b model tests

- examples/llama7b_sparse_quantized/README.md
`from sparseml import SparseAutoModelForCausalLM` errors with:
```
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SparseAutoModelForCausalLM' from 'sparseml' (/home/eldar/to_delete/sparseml/src/sparseml/__init__.py)
```
I think it should be `from sparseml.transformers import SparseAutoModelForCausalLM`
> Fix import typo

- src/sparseml/pytorch/utils/helpers.py
- src/sparseml/transformers/finetune/session_mixin.py
- tests/sparseml/export/transformers/test_generative_transformers.py
The quantization percentage logging has been reporting 0.0% quantization since we switched over to the new framework. This PR updates the calculation to use the new framework. It also cleans up the string formatting and adds Embedding and a prunable/quantizable layer so the percentages are more accurate
```
2024-05-30 16:04:21 sparseml.transformers.finetune.session_mixin INFO     There are 1034420224 prunable params which have 1.2609391906088643 avg sparsity.
2024-05-30 16:04:21 sparseml.transformers.finetune.session_mixin INFO     There are 1034420224 quantizable params, with a quantization percentage of 0.0.
```
```
2024-05-30 15:57:12 sparseml.transformers.finetune.session_mixin INFO     There are 1099956224 prunable params which have 1.19% avg sparsity.
2024-05-30 15:57:12 …
```
> Update Quantization Logging to New Framework

- src/sparseml/modifiers/quantization/gptq/utils/gptq_wrapper.py
- tests/sparseml/transformers/obcq/test_mask_structure_preservation.py
When debugging the Marlin24 kernels I found that the sparsity structure was not being correctly maintained. The vLLM check for sparsity structure was failing. After this GPTQ fix the problem went away, I pulled this code from the nm-AutoGPTQ codebase
> Fix for Sparsity Persist

- src/sparseml/modifiers/quantization/gptq/base.py
- tests/sparseml/pytorch/modifiers/pruning/sparsegpt/test_pytorch.py
- tests/sparseml/transformers/gptq/test_oneshot.py
https://github.com/neuralmagic/compressed-tensors/pull/81 must be merged first
When specifying a scheme preset, the quantization modifier for GPTQ was not being properly initialized. In the example code below, despite specifying a W4A16 scheme the quantization config was always empty: `Building quantization modifier with args: {'config_groups': {'config_group_0': QuantizationScheme(targets=['Linear'], weights=None, input_activations=None, output_activations=None)}}`
The fix was to update the GPTQ modifier initialization to correctly apply the preset scheme. I've also added unit tests to confirm all variants of the GPTQ recipe are functioning as intended
```
import torch
from datasets import load_dataset
from sparseml.transformers import SparseAutoModelForCausalLM, oneshot
from …
```
> Fix GPTQ Aliases

- setup.py
no near term releases are planned for these dependencies so we won't require a hard sync on minor version. minimum supported will remain frozen at 1.7.0
> limit sparsezoo and deepsparse deps to 1.7

- setup.py
NumPy 2.0 released on June 16th, it broke some dependencies in SparseML. For the 1.8 release, I think its best we just restrict the version to < 2.0 since the error is in tensorboard rather than our code
This error was being hit in multiple test suites, restricting the numpy version fixes the problem.
```
tests/sparseml/core/logger/test_logger.py:40: in <module>
TensorBoardLogger(),
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sparseml/core/logger/logger.py:505: in __init__
raise tensorboard_import_error
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sparseml/core/logger/logger.py:42: in <module>
from torch.utils.tensorboard import SummaryWriter
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/torch/utils/tensorboard/__init__.p …
```
> Restrict NumPy Version <2.0

- examples/llama7b_sparse_quantized/README.md
In `examples/llama7b_sparse_quantized/README.md` we apply a staged recipe then reload the model to save a compressed version. However the path was not accounting for the nested save structure used for staged recipes.
Updating the load path fixed the issue. Asana ticket: https://app.asana.com/0/1207587658110568/1207604393141284/f
> Fix Example Uncompressed Path
