docs/source/index.rst
correcting double slash at the end of URLs
=> rst url syntax correction

README.md, docs/source/index.rst, examples/pytorch_sparse_quantized_transfer_learning/README.md
Temporarily removing references to 7x and blog. Will return after it's live.
=> Rm: blog link, 7x

src/sparseml/pytorch/optim/mask_creator_pruning.py
lambda functions are not picklable in PyTorch.  This causes issues when trying to pickle an intermediate PyTorch graph that uses a `GroupedPruningMaskCreator`.  
Specifically. this caused an issue with block pruning a yolo model using `ultralytics/yolov5` which frequently pickles the entire torch graph.
Re-ran pytorch-optim tests. The following block now works:
```
import torch
from sparseml.pytorch.optim import BlockPruningMaskCreator
b = BlockPruningMaskCreator([1,4])
torch.save(b, "blocked-creator.pt")
```
=> make pytorch GroupedPruningMaskCreator picklable

src/sparseml/pytorch/optim/modifier_pruning.py, src/sparseml/utils/helpers.py
This PR addresses https://github.com/neuralmagic/sparseml/issues/139
=> Add support for ALL_PRUNABLE token

integrations/ultralytics/README.md, integrations/ultralytics/deepsparse/annotate.py, integrations/ultralytics/deepsparse/deepsparse_utils.py
Annotate folders of images, video files, and web-cam streams using YOLOv3 models with DeepSparse, ORT, or torch
=> YOLO example - annotation application

src/sparseml/pytorch/datasets/classification/cifar.py
Fix number of classes for CIFAR-10/CIFAR-100 datasets and update to use the community-standard data augmentations for CIFAR-10.
=> Update CIFAR data augmentations

README.md
- Update [README.md](../blob/main/README.md) to reflect latest Pytorch version support
=> Update README.md to reflect latest Pytorch version support

src/sparseml/pytorch/optim/analyzer_module.py, src/sparseml/pytorch/optim/mask_pruning.py
Seems like `param_grad` attribute doesn't exist. I think it's supposed to be `params_grad`.
=> Fix non existing param_grad attribute

integrations/dbolya-yolact/recipes/yolact.pruned.md, integrations/dbolya-yolact/recipes/yolact.pruned_quant.md, integrations/dbolya-yolact/recipes/yolact.quantized.md
=> Fixes: Typo

integrations/dbolya-yolact/README.md, integrations/dbolya-yolact/recipes/yolact.pruned_quant.md, integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md
- Suggestions from review
- Add example commands
- remove `--recipe`  from export commands
- Add instructions to skip training a baseline model and getting weights from SparseZoo
=> Bugfixes yolact

integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md
=> Yolact Doc Updates

integrations/dbolya-yolact/recipes/yolact.pruned.md, integrations/dbolya-yolact/recipes/yolact.pruned_quant.md, integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md
Remove duplicate modules from pruning modifiers
=> Yolact Recipes cleanup

CONTRIBUTING.md, README.md, integrations/dbolya-yolact/tutorials/sparsifying_yolact_using_recipes.md, integrations/huggingface-transformers/tutorials/bert_sparse_transfer_learning.md, integrations/huggingface-transformers/tutorials/sparsifying_bert_using_recipes.md, integrations/pytorch/tutorials/classification_sparse_transfer_learning_tutorial.md, integrations/pytorch/tutorials/sparsifying_pytorch_models_using_recipes.md, integrations/ultralytics-yolov3/tutorials/sparsifying_yolov3_using_recipes.md, integrations/ultralytics-yolov3/tutorials/yolov3_sparse_transfer_learning.md, integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md, integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md, research/mfac/README.md, research/mfac/tutorials/gradual_pruning_with_mfac.md, research/mfac/tutorials/one_shot_pruning_with_mfac.md
=> Jfinks discourse eol

src/sparseml/transformers/__init__.py
init file logic was commented out during development of #576
=> transformers init file fix

src/sparseml/transformers/masked_language_modeling.py, src/sparseml/transformers/question_answering.py, src/sparseml/transformers/text_classification.py, src/sparseml/transformers/token_classification.py
Before: `WARNING  Process rank: -1, device: cuda:0, n_gpu: 4distributed training: False, 16-bits training: True`
Now `WARNING  Process rank: -1, device: cuda:0, n_gpu: 4, distributed training: False, 16-bits training: True`
=> Nit: fixing logging printing in transformers qa script

src/sparseml/optim/helpers.py
The original function was super messy so I took Ben's advice and refactored it a bit.
=> Refactor `update_recipe_variables`

src/sparseml/transformers/text_classification.py
Fixes https://github.com/neuralmagic/sparseml/issues/653 by applying the same changes as here: https://github.com/huggingface/transformers/pull/16475
=> Fix overwriting of MNLI metrics

src/sparseml/pytorch/optim/modifier_distillation.py
...unless this was an intended name mangling?
=> Replace double underscore with single underscore

src/sparseml/pytorch/optim/modifier_distillation.py
Fixes https://github.com/neuralmagic/sparseml/issues/674
=> Fix KL-div calculation when inputs are multidim

src/sparseml/transformers/sparsification/trainer.py
Similar fix Tuan implemented for DistilBERT training, now applied to model evaluation.
=> Fix transformer prediction step

src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
Fixes https://github.com/neuralmagic/sparseml/issues/754
=> Add missing f-strings

src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
Fixes https://github.com/neuralmagic/sparseml/issues/756
=> Set model in the eval mode for pruning

src/sparseml/pytorch/sparsification/pruning/mask_params.py, src/sparseml/pytorch/utils/helpers.py
Should fix https://github.com/neuralmagic/sparseml/issues/750 by calculating sparsity from newly created masks.
=> Fix sparsity calculation via masks-sparsity

src/sparseml/transformers/masked_language_modeling.py, src/sparseml/transformers/question_answering.py, src/sparseml/transformers/sparsification/trainer.py, src/sparseml/transformers/text_classification.py, src/sparseml/transformers/token_classification.py
This reverts commit eeddc5184b2d1bc356900049c3181d02095db555.
=> Revert "initial commit (#745)"

src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
activation QAT of `FloatFunctional` leads to unnecessary repeated Q/DQ blocks in the rn50 graph where `FloatFunctional` is used for `add_relu` leading to post processing accuracy issues. This PR adds `FloatFunctional` as default to the list of layer types to skip the activation QAT of
=> disable activation QAT of add_relu op

src/sparseml/pytorch/object_detection/export.py, src/sparseml/pytorch/object_detection/train.py, src/sparseml/pytorch/object_detection/val.py
The goal of this PR is to add `max_train_steps` support to our yolov5 integration. 
This will allow shorter test runs for validation
=> `max-train-steps` support for `YOLO` integration

src/sparseml/onnx/utils/helpers.py, src/sparseml/transformers/sparsification/trainer.py, src/sparseml/yolov5/scripts.py
Cherry pick newly added commits from main on 6/1/22 at 11:20 AM Eastern Time
=> [cherry-picks] Add 3 new commits from `main`

src/sparseml/optim/manager.py
Reaction to user's feedback: https://github.com/neuralmagic/sparseml/issues/846
=> Set the verbosity of metadata logs from INFO to DEBUG

src/sparseml/pytorch/image_classification/utils/helpers.py
zoo stub is incorrectly matched, manually tested. 
Was previously checking if the stub == "zoo". Needs to instead check startswith
=> image classification - fix bug in zoo stub load

src/sparseml/optim/manager.py
Fixes https://github.com/neuralmagic/sparseml/issues/972
=> Increment epoch-dependent attributes when composing

src/sparseml/optim/manager.py
Fixes https://github.com/neuralmagic/sparseml/issues/970
=> Set start_epoch to zero when -1.0 before composing

.github/workflows/Integrations-post-merge-check.yaml, .github/workflows/assign-review.yaml, .github/workflows/integrations-check.yaml, .github/workflows/quality-check.yaml, .github/workflows/test-check.yaml
This is necessary for upgrading to torch 1.12. Originally done in #964 , but moving these changes to a separate PR to make reviewing easier
=> Upgrading ubuntu in workflows and setting python to 3.9

setup.py
To address issue discussed in https://github.com/pytorch/pytorch/issues/69894#issuecomment-1080635462
=> Freeze setuptools at 59.5.0

integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md, integrations/ultralytics-yolov5/tutorials/yolov5_sparse_transfer_learning.md
coco data automatically downloaded now
=> delete setting up data section in yolov5 tutorials

src/sparseml/pytorch/datasets/classification/imagenet.py
Add resize_scale and resize_mode arguments to allow for pre-processig flow of EfficientNets. Verified accuracy of EfficientNet and ResNet models w/ change.
=> Extend arguments of ImageNet

src/sparseml/pytorch/utils/helpers.py
Fixes https://github.com/neuralmagic/sparseml/issues/676
=> Fix missed mapping of UserDicts

tests/sparseml/pytorch/optim/test_manager.py
test updates reflect changes introduced in #1033
=> fix expected recipes in torch manager tests

integrations/pytorch/export.py, src/sparseml/pytorch/__init__.py, src/sparseml/pytorch/image_classification/export.py, src/sparseml/pytorch/opset.py, src/sparseml/pytorch/utils/exporter.py, tests/integrations/image_classification/args.py, tests/integrations/yolov5/args.py
=> Setting opset based on torch version for `sparseml/pytorch`

src/sparseml/pytorch/torchvision/train.py
=> Adding checkpoint_manager to torchvision

src/sparseml/transformers/export.py, src/sparseml/transformers/text_classification.py
propagate export dataloader changes for `text_classification.py`
=> [Refactor] export dataloader for text classification

src/sparseml/transformers/export.py
key issue here was the previous code was attempting to add a string to a set with `update` instead of `add` which will lead to issues where each character of the onnx model string will be treated as expected files leading to an error.
additionally fixes issues around using an object as a default, user interface of requiring a set
**test_plan:**
bug reproduced locally, confirmed fix locally
=> transformers onnx export - fix bug in model name override

src/sparseml/pytorch/torchvision/train.py
This is to mirror the existing image_classification behavior
=> Saving metrics as .txt file along with checkpoints

src/sparseml/pytorch/recipe_template/main.py, src/sparseml/recipe_template/__init__.py, src/sparseml/recipe_template/utils.py
The following PR adds 4 convenience functions to recipe_template module, the goal being that they can be used directly and have good defaults, the function could in turn be also used as an alternative to passing a recipe to ScheduleModifierManager.from_yaml(...) and instead do something like ScheduledModifierManager.from_yaml(create_recipe())
Testing: All functions invoked manually
```python
>>> from sparseml.recipe_template import (
... create_recipe,
... create_sparse_transfer_recipe,
... create_pruning_recipe,
... create_quantization_recipe,
... )
>>> recipe = create_recipe()
>>> print(recipe)
lr_func: linear
init_lr: 0.001
final_lr: 0.0
num_epochs: 20.0
num_qat_epochs: 5.0
num_qat_finetuning_epochs: 2.5
quantization_submodules: null
num_pruning_active_epochs: 7.5 …
```
=> Convenience functions for `recipe_template`

src/sparseml/pytorch/torchvision/export_onnx.py
Tested with command:
```
python src/sparseml/pytorch/torchvision/export_onnx.py --arch-key resnet50 --checkpoint-path training-runs/torchvision-pretrained-quant/resnet50-imagenette-pruned-conservative/checkpoint-best.pth --dataset-path ~/.cache/nm_datasets/imagenette/imagenette-320 --num-samples 20
```
Resulting outputs:
```bash
$ ll -h torchvision/
total 91M
drwxrwsr-x  6 corey corey 4.0K Nov 15 17:01 ./
drwxrwsr-x 22 corey corey 4.0K Nov 15 17:02 ../
drwxrwsr-x  2 corey corey 4.0K Nov 15 17:01 deployment/
-rw-rw-r--  1 corey corey  90M Nov 15 17:01 model.onnx
drwxrwsr-x  2 corey corey 4.0K Nov 15 17:01 sample_inputs/
drwxrwsr-x  2 corey corey 4.0K Nov 15 17:01 sample_labels/
drwxrwsr-x  2 corey corey 4.0K Nov 15 17:01 sample_outputs/
$ ll -h torchvision/deployment/
total 90M
drwxrwsr-x …
```
=> Adding export script

src/sparseml/transformers/export.py, src/sparseml/transformers/question_answering.py
Propagate changes needed for export dataloader in question_answering script
=> [Refactor] QA export dataloader

src/sparseml/transformers/export.py, src/sparseml/transformers/text_classification.py, src/sparseml/transformers/token_classification.py
propagate changes for token classification
=> [Refactor] export dataloader for token-classification

src/sparseml/pytorch/torchvision/export_onnx.py, src/sparseml/pytorch/torchvision/train.py
Fixes issue brought up https://github.com/neuralmagic/sparseml/pull/1157#discussion_r1024157893
Tested with exporting a checkpoint and also passing a zoo stub for export
=> Moving export to use load_model

src/sparseml/pytorch/torchvision/__init__.py, src/sparseml/pytorch/torchvision/export_onnx.py, src/sparseml/pytorch/torchvision/presets.py, src/sparseml/pytorch/torchvision/sampler.py, src/sparseml/pytorch/torchvision/train.py, src/sparseml/pytorch/torchvision/transforms.py, src/sparseml/pytorch/torchvision/utils.py, src/sparseml/pytorch/utils/helpers.py
This contains all the torchvision code from https://github.com/pytorch/vision/tree/v0.12.0/references/classification, in addition to the code merged in from https://github.com/neuralmagic/sparseml/pull/1104.
See https://github.com/neuralmagic/sparseml/pull/1104 for testing plan
=> Adding torchvision training scripts

src/sparseml/transformers/export.py, src/sparseml/transformers/masked_language_modeling.py, src/sparseml/transformers/question_answering.py, src/sparseml/transformers/text_classification.py, src/sparseml/transformers/token_classification.py
This PR represents the main feature branch for the upcoming export script refactors.
The high level goal for this push are:
- To allow users to export sample/inputs outputs using `sparseml.transformers.export_onnx` utility
- To use the same dataloaders as training script for exporting sample inputs/outputs
To this end the PRs have been broken out in the following manner to allow easier reviews
Note: All PRs must be first merged into this feature branch and the tests should be run, after which this feature branch can be landed on main 
Tests:
```bash
sparseml.transformers.export_onnx --task qa --model_path '/home/XXXX/.cache/sparsezoo/15a1359c-6389-4ffd-ab06-d44a945159c2/training' \
--num_export_samples 10 \
--data_args '{"dataset_name": "squad"}'
```
Output:
```bash
2022-11-16 14:03:41 …
```
=> [Tansformers] Export script refactor

src/sparseml/pytorch/torchvision/train.py
This ONLY converts stuff from argparse to click. This does not change any argument names or handle invalid arugments yet
Test plan: tested locally with previous training commands
=> Using click for torchvision

src/sparseml/pytorch/torchvision/README.md
Basically copied from image_classification and updated commands based on the ones i used for training/export
=> Adding readme to torchvision

src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py
if for some reason the qconfig property is already set to None during qconfig propagation, the desired qconfig will not be propagated. this leads to inconsistent behavior based on targets from a quantization modifier definition. this PR introduces a pass to clear these properties so the appropriate qconfig will be propagated.
relevant torch source code line: https://github.com/pytorch/pytorch/blob/880c811aeb6937a44d5cc700ab3d802f95538aa9/torch/quantization/quantize.py#L51
**test_plan:**
manually verifies this fixes a minimally reproducible example of an issue this bug caused in the yolov5 upgrade
=> [Quantization] clear qconfigs set to None before propagating target qconfig

src/sparseml/transformers/sparsification/trainer.py
Should fix https://github.com/neuralmagic/sparseml/issues/1146
=> Pass empty dict if data_args not given

NOTICE
=> [cherry-pick] Update NOTICE (#1168)

src/sparseml/pytorch/openpifpaf/README.md, src/sparseml/pytorch/openpifpaf/train.py, src/sparseml/pytorch/openpifpaf/trainer.py, src/sparseml/pytorch/openpifpaf/utils.py
Testing plan: Training command runs, and verified sparsity levels change in output from loggers
=> Basic sparseml integration for openpifpaf

src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
Co-authored-by: Benjamin Fineran <bfineran@users.noreply.github.com>
=> [Cherry-Pick] remove model as arg for _replace_initializer() (#1184)

src/sparseml/openpifpaf/train.py, src/sparseml/openpifpaf/trainer.py
Adds ability to load recipes from checkpoints similar to torchvision
=> Adding checkpoint manager functionality to openpifpaf

src/sparseml/transformers/sparsification/trainer.py
Cherrypick for: https://github.com/neuralmagic/sparseml/pull/1204
=> [Cherrypick] Remove `typing.Final`

setup.py
we want to align with the installed torch patch version
=> [cherry-pick] unrestrict torchvision patch version match requirement

src/sparseml/pytorch/torchvision/train.py
* Changing checkpoint_recipe to recipe, and --recipe no longer required
* Changing recipe order for checkpoint path
* Fixing model loading
* Styling
=> Cherry pick Torchvision eval fixes (#1212)

src/sparseml/exporters/transforms/constants_to_initializers.py, tests/sparseml/exporters/transforms/test_constants_to_initializers.py
Part of this pass:
https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L225
=> [Export Refactor] Constants to initializers

src/sparseml/exporters/transforms/unwrap_batchnorms.py, tests/sparseml/exporters/transforms/test_unwrap_batchnorms.py
This pass https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/utils/exporter.py#L806
=> [Export Refactor] Unwrap batchnorms transform

src/sparseml/exporters/transforms/conv_to_qlinearconv.py, src/sparseml/exporters/transforms/utils/helpers.py, src/sparseml/onnx/utils/graph_editor.py, tests/sparseml/exporters/transforms/test_conv_to_qlinearconv.py
Original pass is here https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L357
Which is called from _convert_quantizable_ops
Test plan:
unit tests included
=> [Export Refactor] Adding ConvToQLinearConv transform

src/sparseml/exporters/transforms/flatten_qparams.py, tests/sparseml/exporters/transforms/test_flatten_qparams.py
Pass from https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/utils/exporter.py#L666
=> [Export Refactor] Adding FlattenQParams transform

src/sparseml/exporters/transforms/gemm_to_matmulinteger_add_cast_mul.py, tests/sparseml/exporters/transforms/test_gemm_to_matmulinteger_add_cast_mul.py
Pass from https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L884
=> [Exporter Refactor] Adding GemmToMatMulIntegerAddCastMul transform

src/sparseml/exporters/transforms/matmul_to_matmulinteger_add_cast_mul.py, src/sparseml/exporters/transforms/utils/matching.py, tests/sparseml/exporters/transforms/test_matmul_to_matmulinteger_add_cast_mul.py
This pass https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L1007
=> [Exporter Refactor] Adding MatMulToMatMulIntegerAddCastMul transform

src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py, src/sparseml/pytorch/sparsification/quantization/quantize.py, tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
`submodule_schemes` replaces the `submodules` functionality of the existing quantization modifier while enabling the user to specify different schemes for different submodules. through this functionality, users may build configs that control exactly what to quantize through the entire model
if `submodule_schemes` is specified, then the default behavior of quantizing "everything" will be scoped down to just the targeted submodules
the `_QuantizationSchemesDict` was necessary to add for yaml serialization - open to suggestions for cleaner ways of getting the property properly serialized
**test_plan:**
unit tests updated for:
* yaml serialization
* testing that only submodule schemes are quantized if specified
* cases added for each
=> [QuantizationModifier] submodule_schemes property impl - target specific submodules by scheme

src/sparseml/exporters/transforms/fold_relu_quants.py, tests/sparseml/exporters/transforms/test_fold_relu_quants.py
Pass from https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L201
=> [Exporter Refactor] Adding FoldReLUQuants transform

src/sparseml/exporters/transforms/propagate_embedding_quantization.py, src/sparseml/exporters/transforms/utils/matching.py, tests/sparseml/exporters/transforms/test_propagate_embedding_quantization.py
This pass https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L1719
=> [Exporter Refactor] Adding PropagateEmbeddingQuantization transform

src/sparseml/exporters/transforms/remove_duplicate_quantize_ops.py, tests/sparseml/exporters/transforms/test_remove_duplicate_quantize_ops.py
This pass 
https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L1471
=> [Exporter Refactor] Adding RemoveDuplicateQuantizeOps transform

src/sparseml/pytorch/sparsification/quantization/modifier_quantization.py, tests/sparseml/pytorch/sparsification/quantization/test_modifier_quantization.py
ported from the legacy modifier - functionality unchanged
**test_plan:**
yaml tests added for serialization - further testing manual for now
=> [QuantizationModifier] num_calibration_steps support (PTQ)

src/sparseml/exporters/transforms/remove_duplicate_qconv_weights.py, tests/sparseml/exporters/transforms/test_remove_duplicate_qconv_weights.py
This pass 
https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L1273
=> [Exporter Refactor] Adding RemoveDuplicateQConvWeights transform

src/sparseml/exporters/transforms/delete_trivial_onnx_adds.py, src/sparseml/exporters/transforms/utils/__init__.py, src/sparseml/exporters/transforms/utils/helpers.py, tests/sparseml/exporters/transforms/test_delete_trivial_onnx_adds.py
Original implementation:
https://github.com/neuralmagic/sparseml/blob/bbc61bec8fd250b0e94a89cbbb129b52da0eb542/src/sparseml/pytorch/utils/exporter.py#L780
=> [Export Refactor] Delete Trivial Onnx Adds

src/sparseml/exporters/transforms/quantize_residuals.py, tests/sparseml/exporters/transforms/test_quantize_residuals.py
This pass https://github.com/neuralmagic/sparseml/blob/9778cec8684d3fcb683504eef88655d9a4607fd6/src/sparseml/onnx/utils/graph_optimizer.py#L133
Testing plan: no tests yet because i'm tired 🤣 , it's identical to the old version
=> [Exporter Refactor] Adding QuantizeResiduals transform

src/sparseml/exporters/transforms/convert_quantizable_conv_integer.py, src/sparseml/exporters/transforms/convert_quantizable_matmul.py, src/sparseml/exporters/transforms/gemm_to_matmulinteger_add_cast_mul.py, src/sparseml/exporters/transforms/matmul_to_matmulinteger_add_cast_mul.py
Title - matches old behavior now
=> [Exporter Refactor] Fixing conv integer node deletion & sorting in core ops

src/sparseml/exporters/transforms/fold_relu_quants.py
Matches old behavior now - the port didn't capture the logic of checking ALL the children of relu
=> [Exporter Refactor] Fix fold relu quants

src/sparseml/exporters/transforms/delete_repeated_qdq.py, tests/sparseml/exporters/transforms/test_delete_repeated_qdq.py
Adds pass from https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L265
=> [Exporter Refactor] Adding DeleteRepeatedQdq transform

src/sparseml/exporters/transforms/skip_input_quantize.py, tests/sparseml/exporters/transforms/test_skip_input_quantize.py
Adds pass from https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py#L1624
Testing needed
=> [Exporter Refactor] Adding SkipInputQuantize transform

src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
This fixes a bug where the bias of conv nodes was not being properly folded.
There are two causes:
1. The `_convert_single_constants_to_initializers` was run after `_fold_qat_conv_bns`
2. The bias is only folded if it is an initializer
This means if the bias was a Constant node, it wasn't being properly folded.
=> Properly folding conv div bns

src/sparseml/exporters/transforms/onnx_transform.py
Also adds
- delete unused_initializers
- graph sorting
to base class so subclasses don't have to call
Testing plan: existing unit tests
=> [Exporter Refactor] Adding add/delete methods to OnnxTransform

src/sparseml/exporters/transforms/flatten_qparams.py, src/sparseml/exporters/transforms/initializers_to_uint8.py, src/sparseml/exporters/transforms/onnx_transform.py, src/sparseml/exporters/transforms/propagate_embedding_quantization.py, src/sparseml/exporters/transforms/remove_duplicate_qconv_weights.py, src/sparseml/exporters/transforms/skip_input_quantize.py, src/sparseml/exporters/transforms/utils/helpers.py, tests/sparseml/exporters/transforms/test_remove_duplicate_qconv_weights.py
First pass at standardization. These passes don't delete nodes or do anything complicated.
=> [Exporter Refactor] Standardize trivial transforms

src/sparseml/exporters/onnx_to_deepsparse.py, src/sparseml/exporters/transforms/__init__.py
=> [ExporterRefactor] Fix imports

src/sparseml/transformers/sparsification/trainer.py
Fixes https://github.com/neuralmagic/sparseml/issues/1285
=> Fix bad import

src/sparseml/pytorch/sparsification/pruning/modifier_pruning_obs.py
Makes OBSPruningModifier more DDP friendly by collecting gradients in all processes. This prevents NCCL timeout error when other processes are waiting for too long on the main process to collect gradients.
=> DDP: Collect gradients in all processes

src/sparseml/pytorch/torchvision/train.py, tests/integrations/yolov5/configs/commit/recipe_short_prune_quant.md, tests/integrations/yolov5/configs/commit/test_ended_to_end_pruned_quantized.yaml, tests/integrations/yolov5/configs/pre-commit/test_cli.yaml
* Some fixes for torchvision training flow
* Update YOLOv5s model for testing
* Update YOLOv5s model for testing
* Update recipe to make quantization mode general
Co-authored-by: Alexandre Marques <alexandre@neuralmagic.com>
=> [Cherry Pick] Some fixes for torchvision training flow (#1281)

tests/integrations/yolov5/configs/commit/recipe_short_prune_quant.md
Test model: yolov5-s/pruned65_quant-none
=> Update quantization recipe to match test model

tests/integrations/yolov5/configs/commit/recipe_short_prune_quant.md, tests/integrations/yolov5/configs/pre-commit/test_cli.yaml
=> Cherry pick #1295 #1309

src/sparseml/pytorch/torchvision/train.py
* Changing log_scalar step unit to batch # instead of epoch
* Fixing log_metrics interaction with gradient-accum-steps
* Respond to review
* Fixing log frequency for wandb
=> [Cherry pick] Changing log_scalar step unit to batch # instead of epoch (#1307)

src/sparseml/pytorch/torchvision/train.py
Co-authored-by: Benjamin Fineran <bfineran@users.noreply.github.com>
=> [Cherry pick] Adding --recipe-args to torchvision train script (#1298)

src/sparseml/pytorch/torchvision/train.py
Properly passes scaler to wrap_optim.
Ran
- without `--amp`
- with `--amp`
**Have not tested amp with quantization**
=> Torchvision scaler

src/sparseml/pytorch/models/classification/efficientnet.py
=> Remove duplicate Q/DQ

tests/sparseml/onnx/optim/test_sensitivity_ks.py
Generated by running `NM_ML_GENERATE_ONNX_TEST_DATA=1 pytest -s tests/sparseml/onnx/optim/test_sensitivity_ks.py`
=> Handling nulls in test_sensisity_ks.py sorting

src/sparseml/pytorch/yolov8/train.py
This PR adds a training script around our yolov8 classes. It overrides the relevant classes with our own sparse trainer classes. All the options & help strings were pulled directly from yolov8's default.yaml file.
Tested along with #1330
=> Adding train cli script to yolov8

src/sparseml/pytorch/torchvision/train.py
This PR adds support to save the arch_key along with the checkpoint for sparseml's torchvision integration:
The fix involved two steps:
1)  Save: the `arch_key` in the checkpoint dict, 
2) Update: Model creation code, to try `ModelRegistry.create` even when `arch_key` is `None`; This tries to read the `arch_key` from the model checkpoint, if key is not present the relevant functions still raise the respective errors, else it is read from the checkpoint and returned, this was done to avoid re-loading the checkpoint
After this PR the checkpoint looks like the following (checked after 1 epoch from a training run):
```python
In [1]: import torch
In [2]: checkpoint = torch.load("./checkpoint.pth")
In [3]: checkpoint.keys()
Out[3]: dict_keys(['state_dict', 'optimizer', 'args', 'arch_key', …
```
=> Update: Torchvision checkpoint saving to include arch_key

src/sparseml/transformers/sparsification/trainer.py
Fixes https://github.com/neuralmagic/sparseml/issues/1355
=> Enable one-shot with grad-based pruners

src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
Enforces uint8 weights for quantized convs (fixes previous code that was updating list inside loop)
=> Cherry-pick PR #1339 into 1.4

src/sparseml/pytorch/torchvision/export_onnx.py, src/sparseml/pytorch/torchvision/train.py, src/sparseml/pytorch/torchvision/utils.py
cherry picking all commits to torchvision training since 1/25/23 onto the release/1.4 branch in order to get latest fixes without diverging during merge conflicts
confirmed running help commands are working 
@rahul-tuli to do a sanity check run
=> [cherry-pick] torchvision training updates 1/25/23-2/2/23

setup.py, src/sparseml/pytorch/yolov8/default.yaml, src/sparseml/pytorch/yolov8/train.py, src/sparseml/pytorch/yolov8/trainers.py
Improved loading logic. Will test completely with test plan in feature branch PR before merging.
New logic is:
1. Create model
2. Create managers
3. Apply structure from checkpoint
4. Load state dict
Additionally, this handles the finetuning over quantized model case, where checkpoint_manager is not None and manager is None
=> Yolov8 checkpoints v2

setup.py, src/sparseml/pytorch/yolov8/README.md
See README 😁 
Test plan: pip installed and verified that `sparseml.ultralytics.train --help` command works
=> Adding README to yolov8 and console script to setup.py

setup.py
=> [cherry-pick] install extra option for torch_all (#1368)

setup.py, src/sparseml/pytorch/models/detection/yolo_v3.py, src/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py, src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py, src/sparseml/pytorch/sparsification/quantization/quantization_scheme.py, tests/sparseml/tensorflow_v1/optim/test_modifier_lr.py, tests/sparseml/tensorflow_v1/optim/test_schedule_lr.py
This diff fixes failing quality tests on main
=> Updating black==22.12.0

src/sparseml/pytorch/yolov8/trainers.py
Ran train command with sparse & quant recipe with multiple gpus.
=> Fixing multi-gpu yolov8 training 

setup.py, src/sparseml/pytorch/utils/logger.py
=> [Cherry Pick] [Fix] Add more verbose`wandb` import error

tests/integrations/config.py, tests/integrations/yolov5/args.py
Becuase of https://github.com/neuralmagic/yolov5/commit/1d0bc241aacabb4f782113560cdf305206781910
=> Revert sparsification_recipe to recipe

setup.py, src/sparseml/yolov8/default.yaml, src/sparseml/yolov8/trainers.py, src/sparseml/yolov8/validators.py
All testing from the following PRs was re-run and verified:
1. https://github.com/neuralmagic/sparseml/pull/1336
2. https://github.com/neuralmagic/sparseml/pull/1378
3. https://github.com/neuralmagic/sparseml/pull/1373
=> Upgrade Yolov8 to 8.0.30

Makefile, src/sparseml/openpifpaf/openpifpaf.status.yaml, src/sparseml/pytorch/image_classification/nm_image_classification.status.yaml, src/sparseml/pytorch/torchvision/torchvision.status.yaml, src/sparseml/transformers/transformers.status.yaml, src/sparseml/yolov5/yolov5.status.yaml, status/integration_status.py, status/status_template.status.yaml
YAML configs manually created from results compiled in #1290 with some fields updated based on progress since that PR was opened
**test_plan:**
pending auto creation of MD files in follow up PR
=> [integration-standardization] YAML configs for existing integrations

src/sparseml/yolov8/trainers.py
Adds missing image configuration to validation
both yolo and sparseml commands output exact same score for yolov8x.pt:
```bash
> sparseml.ultralytics.val --model https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x.pt
Found https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x.pt locally at yolov8x.pt
Ultralytics YOLOv8.0.30 🚀 Python-3.9.5 torch-1.13.1+cpu CPU
Dataset 'coco128.yaml' not found ⚠️, missing paths ['/home/corey/sparseml/datasets/coco128/images/train2017']
Dataset download success ✅ (1.5s), saved to /home/corey/sparseml/datasets
val: Scanning /home/corey/sparseml/datasets/coco128/labels/train2017... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<00:00, 1369.43it/s]
val: New cache created: …
```
=> Fixing SparseYOLO.val to use image size and rect like normal yolo does

src/sparseml/exporters/onnx_to_deepsparse.py, src/sparseml/exporters/transforms/__init__.py, src/sparseml/exporters/transforms/matmul_add_to_matmulinteger_add_cast_mul.py, src/sparseml/exporters/transforms/matmul_to_matmulinteger_cast_mul.py, src/sparseml/exporters/transforms/utils/matching.py, tests/sparseml/exporters/transforms/test_matmul_add_to_matmulinteger_add_cast_mul.py
Also enables optional nodes in parent_ops
Tested with sparsifyml & unit tests
=> Adding MatMulToMatMulIntegerCastMul

src/sparseml/transformers/token_classification.py
=> [Cherry Pick] Fix divergence between student and teacher label mapping

MANIFEST.in
=> Fixing old path of yolov8 (#1419)

src/sparseml/yolov8/trainers.py
Fixes https://app.asana.com/0/1203126676641557/1204130698270567
Fixes https://app.asana.com/0/1203126676641557/1204141253385896/f
=> Saving pytorch model identical to loaded checkpoint with one shot

src/sparseml/onnx/utils/model.py
Update current usage of analyze_model function to new api
=> Update usage of analyze_model to model_debug_analysis

src/sparseml/yolov8/export.py, src/sparseml/yolov8/trainers.py
=> [cherry pick] Collection of 4 yolov8 commits

src/sparseml/pytorch/torchvision/train.py
missing, tested addition to #1455 lost in rebase
=> [torchvision] add ignore error tensors back to optional checkpoint load

src/sparseml/pytorch/torchvision/train.py
=> [cherry-pick-1.4][torchvision][Bug-fix] ignore state dict error on transfer learning tasks + use PythonLogger default logger #1455

src/sparseml/onnx/utils/helpers.py
minor uncommitted change on top of #1471  - force landing due to testing against yolov5 to unblock
=> [ONNX] patch previous commit to accept path-like objects

src/sparseml/onnx/utils/helpers.py
* [ONNX] support for setting/getting string onnx tensor shapes
* Apply suggestions from code review
=> [cherry-pick-1.5][ONNX] support for setting/getting string onnx tensor shapes (#1478)

tests/sparseml/pytorch/utils/test_sparsification_info/__init__.py, tests/sparseml/pytorch/utils/test_sparsification_info/test_configs.py
=> [ModuleSparsificationInfo][Tests] Proposal of the main logic

tests/sparseml/pytorch/sparsification/training/test_modifier_logging.py
Tests for `SparsificationLoggingModifier` object
=> [ModuleSparsificationInfo][Tests] SparsificationLoggingModifier

src/sparseml/__init__.py
replaced by google analytics, version check util to be removed in future release
=> remove sparsezoo package version check

src/sparseml/yolov8/trainers.py
* Style and quality fixes
* Revert "Style and quality fixes"
This reverts commit e5e8af409cbe607d720f57567a99567ed0ea6d76.
* Replaces ".pt" for "pt" in suffix
=> Cherry-pick #1526 into release/1.5

src/sparseml/pytorch/utils/helpers.py, src/sparseml/yolov8/trainers.py, src/sparseml/yolov8/validators.py
Updates needed for release 1.5 branch YOLOv8 integration to match main. Fixes validation of zoo stubs.
=> Release 1.5 updates for YOLOv8

setup.py
as written, only 0.14.0 would be allowed
=> allow patch versions of torchvision 0.14 beyond .0

src/sparseml/yolov8/trainers.py, src/sparseml/yolov8/val.py
Cherrypicking [PR #1561 ](https://github.com/neuralmagic/sparseml/pull/1561) into 1.5 release.
* Fix loading Yolov8 sparsezoo models
=> [Cherry Pick] Fix loading Yolov8 sparsezoo models (#1561)

setup.py, src/sparseml/openpifpaf/__init__.py, src/sparseml/pytorch/torchvision/__init__.py, src/sparseml/transformers/__init__.py, src/sparseml/yolov5/__init__.py, src/sparseml/yolov8/__init__.py
=> [Cherry-Pick] Cherry pick autoinstall upgrade

setup.py
=> [Cherry-Pick] #1580

README.md, docs/source/installation.md
This PR updates docs to reflect latest supported torch versions
---
- https://app.asana.com/0/0/1204714588243824
=> Update docs with latest supported torch versions

README.md, docs/source/installation.md
=> [Cherry-Pick] Update docs with latest supported torch versions

.MAINTAINERS
- Update `.MAINTAINERS` with `dsikka` as part of my first commit.
=> Add name to maintainers list as part of first commit

src/sparseml/version.py, src/sparseml/yolov8/default.yaml
This PR fixes a training error in yolov8 where an argumrnt datasets_dir was missing from default.yaml + updates hotfix version
=> [cherry-pick 1.5.1] Fix yolov8 training error

integrations/ultralytics-yolov5/tutorials/sparse-transfer-learning.md
Updates old install instruction for yolov5 tutorial
=> Update install instruction

.github/workflows/build-and-publish-release-images.yaml
Rework if statements to target tag created with a `v` in front representing a version
=> [BugFix] rework if statement to push on tag with v

setup.py
=> update max datasets version

.github/workflows/Integrations-post-merge-check.yaml, .github/workflows/integrations-check.yaml, .github/workflows/test-check.yaml, setup.py
- Fix protobuf ranges to account for updates in other packages and get our pytorch tests working
=> Fix broken `protobuf` ranges

src/sparseml/transformers/question_answering.py
follow up to #1667 - catches additional exception that may be raised
=> [QuestionAnswering] catch extra exception for retry in custom file loading

src/sparseml/yolov8/utils/export_samples.py
Remove batch dimension from samples
=> Fix dimension of sample inputs/outputs for YOLOv8

setup.py, src/sparseml/yolov8/__init__.py, src/sparseml/yolov8/default.yaml, src/sparseml/yolov8/train.py, src/sparseml/yolov8/trainers.py, src/sparseml/yolov8/utils/export_samples.py, src/sparseml/yolov8/validators.py
This reverts commit a4cb0c35a70fc18d871219d2cf517b80773be983.
The reversion is needed because deepsparse is not ready for the changes; the changes will be added back in again once deepsparse is ready
The code-owner for this reversion is @dsikka
=> Revert "[YOLOV8] `ultralytics` Update (#1652)"

.github/workflows/build-nightly.yml, .github/workflows/build-release.yml, .github/workflows/util.yml
Add GHA workflows to build nightly and release.
Report status to testmo: https://neuralmagic.testmo.net/automation/sources/view/5
=> Add GHA build workflows and report to Testmo

tests/integrations/helpers.py, tests/sparseml/onnx/utils/test_graph_optimizer.py, tests/sparseml/pytorch/test_torch_to_onnx_exporter.py
This PR is a cherry pick for #1729 and also updates the patch version
=> [Cherry-pick] #1729 explicity set providers for ORT sessions

src/sparseml/core/state.py
Run `make style && make quality` on current state of main
=> Fix Style and Quality

src/sparseml/core/recipe/modifier.py, src/sparseml/core/recipe/recipe.py, tests/sparseml/core/recipe/test_recipe.py
This PR adds serialization support + tests for Recipe class
=> [modifier refactor] Add serialization tests

src/sparseml/yolov8/trainers.py
on default export, some YOLOv8 models through the sparseml flows aren't able to be properly overwritten for different input shapes. This patch adds in extra output dyanmic dimensions by default to match the upstream export (see
https://github.com/ultralytics/ultralytics/blob/92753ebd84027172e572e2ce450c1395b08a38af/ultralytics/engine/exporter.py#L325)
**test_plan:**
manual by @rsnm2
=> [YOLOv8 export] set correct output dimensions to dynamic

.gitignore, src/sparseml/core/lifecycle/event.py, tests/sparseml/core/lifecycle/__init__.py, tests/sparseml/core/lifecycle/test_event.py, tests/sparseml/core/lifecycle/test_session.py, tests/sparseml/core/recipe/test_recipe.py, tests/sparseml/core/test_session.py, tests/sparseml/core/test_state.py, tests/sparseml/helpers.py
This PR adds minor unit tests for the new Modifier Refactor framework;
Current Coverage:
`$ pytest --cov-report term-missing --cov=sparseml tests/sparseml/core`
`coverage html`
=> [Unit Tests][Modifier Refactor]

src/sparseml/pytorch/opset.py
engine support confirmed by @tlrmchlsmth
=> [pytorch-onnx] update default ONNX export opset to 14

Makefile, src/sparseml/modifiers/obcq/utils/sparsegpt.py, tests/sparseml/core/test_session.py, tests/sparseml/core/test_state.py, tests/sparseml/helpers.py, tests/sparseml/modifiers/helpers.py, tests/sparseml/modifiers/pruning/constant/test_pytorch.py
Addresses review comments from @satrat on #1752
=> Address review comments on 1752

src/sparseml/modifiers/obcq/pytorch.py
Removing `finalization_kwargs_` from the OBCQ script which is no longer used, and removing the return of `extras` from `apply_obcq` so we don't keep the input sequences in memory beyond where necessarily
=> Cleaning up kwargs and returns

tests/sparseml/pytorch/sparsification/pruning/test_modifier_pruning_topkast.py
One TopKast test is still flaky. Will fix this week, but commmenting out for now.
=> comment out flaky test  test_modifier_pruning_topkast.py

src/sparseml/pytorch/utils/exporter.py, src/sparseml/transformers/export.py
=> [Cherry-Pick][Fix] Inferring a default sequence length during transformers export

src/sparseml/pytorch/utils/exporter.py, tests/sparseml/pytorch/image_classification/utils/test_helpers.py
=> [Cherry-Pick] [BugFix] Call model.deployment_directory_path explicitly in failing test

src/sparseml/transformers/sparsification/obcq/export.py
Check for input recipe before applying structure, throw a warning if none found
=> Re-Enable Dense ONNX Export

src/sparseml/transformers/sparsification/obcq/export.py, src/sparseml/transformers/utils/model.py
Adding back in removed config flags, moving `use_cache` to only apply on export
=> Disable Cache on Export

src/sparseml/transformers/finetune/README.md
Adding the simple README from internal-docs
=> Adding Finetuning README

src/sparseml/core/logger/utils/__init__.py, src/sparseml/core/logger/utils/frequency_manager.py, tests/sparseml/core/logger/utils/test_frequency_manager.py
This PR adds a `FrequencyManager` class
Responsibilities of this class:
- Ascertain if we should log at the current step or not
Based off of #1924
Testing: Added automated tests
=> [Add] frequency_manager to check log "readiness"

src/sparseml/core/logger/logger.py, src/sparseml/core/session.py
Use Sparsification Group logger under the hood, to allow tensorboard/wandb support
=> [Logger Refactor] Use Sparsification Group logger

.github/workflows/test-check.yaml, tests/sparseml/transformers/finetune/data/test_dataset_loading.py, tests/sparseml/transformers/obcq/test_obcq.py
Updating the GHA script to correctly check for changes in `src/sparseml/transformers` and `tests/sparseml/transformers`. Also updated a slow transformers unit test to speed it up and confirm the GHA test does trigger
=> Fix Transformers GHA Check

src/sparseml/export/__init__.py, src/sparseml/export/helpers.py, src/sparseml/integration_helper_functions.py, src/sparseml/transformers/sparsification/trainer.py
fixes from testing LLMs export from a fresh python 3.8 environment with minimal extras installed (just nm-transformers and torch)
=> [Export refactor] final manual testing fixes

setup.py, src/sparseml/export/__init__.py, src/sparseml/export/export.py, src/sparseml/pytorch/image_classification/integration_helper_functions.py, src/sparseml/transformers/integration_helper_functions.py, src/sparseml/transformers/sparsification/trainer.py, tests/sparseml/export/test_helpers.py, tests/sparseml/pytorch/conftest.py, tests/sparseml/transformers/test_integration_helper_functions.py, tests/sparseml/transformers/utils/test_initializers.py
includes a few bug fixes. 
see docstring for full arg specs. quick example
```bash
sparseml.export PATH/TO/SPARSIFIED/LLM \
--task text-generation
```
=> Export refactor CLI

src/sparseml/core/logger/logger.py, src/sparseml/core/logger/utils/frequency_manager.py, src/sparseml/core/session.py, src/sparseml/pytorch/utils/logger.py, tests/sparseml/core/test_session.py, tests/sparseml/pytorch/utils/test_logger.py
This PR adds support to log losses in the new sparsification framework;
Based off of #1920 
Example log file has been attached for GMP with `mobilenet_v2`
[latest-log-gmp-mobilenet-12-01-2024_07.58.30.log](https://github.com/neuralmagic/sparseml/files/13919345/latest-log-gmp-mobilenet-12-01-2024_07.58.30.log)
=> [Logger Framework] Log Losses

src/sparseml/yolov8/trainers.py
fixes issue at api level due to args not being set properly see #1516 for fix at CLI level
=> [yolov8][fix] 'DetectionModel' object has no attribute 'args'

src/sparseml/export/export.py, src/sparseml/export/helpers.py, src/sparseml/pytorch/image_classification/utils/helpers.py, src/sparseml/pytorch/torch_to_onnx_exporter.py, src/sparseml/transformers/integration_helper_functions.py, src/sparseml/transformers/utils/helpers.py, tests/sparseml/transformers/test_integration_helper_functions.py
=> [Cherry-Pick][Export Refactor] Fixing UI issues 

src/sparseml/transformers/sparsification/obcq/obcq.py
In this PR: https://github.com/neuralmagic/sparsezoo/pull/404 I added minor improvements to the `RegistryMixin` that we need to account for (they are breaking some of the tests in the GHA).
To be cherry-picked to 1.7 once it lands to main
=> [Fix] Small fixes to account for changes to `RegistryMixin`

setup.py, src/sparseml/core/recipe/recipe.py, src/sparseml/modifiers/pruning/wanda/pytorch.py, src/sparseml/modifiers/utils/pytorch_helpers.py, src/sparseml/pytorch/utils/sparsification_info/configs.py, src/sparseml/transformers/finetune/README.md, src/sparseml/transformers/finetune/data/base.py, src/sparseml/transformers/finetune/data/data_args.py, src/sparseml/transformers/finetune/data/data_helpers.py, src/sparseml/transformers/finetune/data/evolcodealpaca.py, src/sparseml/transformers/finetune/data/gsm8k.py, src/sparseml/transformers/finetune/data/open_platypus.py, src/sparseml/transformers/finetune/data/ultrachat_200k.py, src/sparseml/transformers/finetune/example_alternating_recipe.yaml, src/sparseml/transformers/finetune/runner.py, src/sparseml/transformers/finetune/session_mixin.py, src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/sparsification/obcq/obcq.py, tests/sparseml/transformers/finetune/data/test_dataset_loading.py
~#2014~ Not needed for release
=> 1.7 Cherry Picks

src/sparseml/export/export.py, src/sparseml/export/export_data.py, src/sparseml/export/helpers.py, src/sparseml/export/validators.py, src/sparseml/transformers/finetune/data/data_helpers.py, src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/integration_helper_functions.py, src/sparseml/transformers/sparsification/obcq/obcq.py, src/sparseml/transformers/utils/helpers.py, src/sparseml/transformers/utils/load_task_model.py, src/sparseml/transformers/utils/optimizations.py, src/sparseml/transformers/utils/sparse_model.py, src/sparseml/utils/helpers.py, tests/sparseml/export/image_classification/test_image_classification.py, tests/sparseml/export/transformers/test_generative_transformers.py, tests/sparseml/export/transformers/test_transformers.py, tests/sparseml/transformers/obcq/test_obcq.py, tests/sparseml/transformers/test_integration_helper_functions.py, tests/sparseml/transformers/utils/test_helpers.py, tests/sparseml/transformers/utils/test_initializers.py, tests/sparseml/utils/test_helpers.py
=> [Cherry-Pick] Patching the new exporters module

src/sparseml/transformers/finetune/data/custom.py, src/sparseml/transformers/finetune/data/data_args.py
Needed 2 changes to get this running in an E2E test:
* defaulting text_column to "text" instead of None
* adding remove_columns as a CLI arg, before there was no way for the user to set this
=> Custom Dataset Fixes

src/sparseml/__init__.py, src/sparseml/evaluation/__init__.py, src/sparseml/evaluation/evaluator.py, src/sparseml/evaluation/integrations/__init__.py, src/sparseml/evaluation/integrations_config.yaml, src/sparseml/evaluation/registry.py, tests/sparseml/evaluation/__init__.py, tests/sparseml/evaluation/test_evaluator.py, tests/sparseml/evaluation/test_registry.py
This PR adds a top level evaluation convenience function in evaluator.py
Based off of #1999 
---
- https://app.asana.com/0/0/1206433403697353
=> [Add] Convenience Evaluation Function

src/sparseml/transformers/utils/sparse_config.py, src/sparseml/utils/helpers.py, tests/sparseml/transformers/utils/test_sparse_config.py
As requested by @rahul-tuli. Will be in general useful for different applications.
=> Support for `SparseAutoConfig`

src/sparseml/transformers/finetune/data/base.py, src/sparseml/transformers/finetune/runner.py, src/sparseml/transformers/finetune/session_mixin.py, src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/utils/sparse_model.py
Various bugfixes for matching up sparseML and llama-recipes finetuning
* removing dummy learning rate scheduler
* fixing data collator
* adding step-wise loss and perplexity logs to mimic llama-recipes
* support for FSDP teacher, and keep teacher in eval mode
* llama-recipes runs: https://docs.google.com/spreadsheets/d/1qeEi9ICbu9hkwpnFReOh1jbXShj0dOGYbaFb3M2AVi4/edit#gid=0 
* sparseML runs: https://docs.google.com/spreadsheets/d/1-AMyNT8oY1bDmtkRm3llnhNmK6FMIX7mxYlgcWC4O6c/edit#gid=0
=> Finetuning Bug Fixes

src/sparseml/evaluation/evaluator.py, src/sparseml/evaluation/registry.py, tests/sparseml/evaluation/dummy_config.yaml, tests/sparseml/evaluation/dummy_integration.py, tests/sparseml/evaluation/test_registry.py
Based off of #1992 
This PR accomplishes the following:
- Add test for collection and resolution 
- Update functions to be more testable
- Let integration infer dataset if None
=> [Eval Refactor] Some Fixes + test

setup.py, src/sparseml/__init__.py, src/sparseml/evaluation/__init__.py, src/sparseml/evaluation/cli.py, src/sparseml/evaluation/evaluator.py, src/sparseml/evaluation/integrations/__init__.py, src/sparseml/evaluation/integrations/lm_eval_harness.py, src/sparseml/evaluation/integrations/perplexity.py, src/sparseml/evaluation/integrations_config.yaml, src/sparseml/evaluation/registry.py, src/sparseml/transformers/utils/helpers.py, tests/sparseml/evaluation/__init__.py, tests/sparseml/evaluation/dummy_config.yaml, tests/sparseml/evaluation/dummy_integration.py, tests/sparseml/evaluation/integrations/__init__.py, tests/sparseml/evaluation/integrations/test_perplexity.py, tests/sparseml/evaluation/test_evaluator.py, tests/sparseml/evaluation/test_registry.py
The base feature branch for Sparseml Eval Refactors
```bash
pytest tests/sparseml/evaluation                                                     (evaluation-feature-branch|✚1…2⚑2)
================================================== test session starts ===================================================
platform linux -- Python 3.11.7, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/rahul/projects/sparseml
configfile: pyproject.toml
plugins: flaky-3.7.0, mock-3.12.0, hydra-core-1.3.2
collected 5 items                                                                                                        
tests/sparseml/evaluation/integrations/test_perplexity.py .                                                        [ 20%]
tests/sparseml/evaluation/test_evaluator.py . …
```
=> [Feature Branch] SparseML Evaluation Framework

src/sparseml/__init__.py, src/sparseml/export/__init__.py, src/sparseml/export/export.py, src/sparseml/export/helpers.py, tests/sparseml/export/image_classification/test_image_classification.py, tests/sparseml/export/transformers/test_generative_transformers.py, tests/sparseml/export/transformers/test_transformers.py
=> [Cherry-Pick][[Exporter Module] UI improvements

src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/text_generation.py
adds support for: `from sparseml.transformers.text_generation import train, one_shot, eval, apply`
=> Text gen imports

src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/text_generation.py
* import pathway for sparseml.transformers.text_generation
* add one_shot alias
=> [cherry-pick] Text gen imports (#2066)

src/sparseml/modifiers/obcq/base.py, src/sparseml/modifiers/obcq/pytorch.py, src/sparseml/modifiers/pruning/wanda/base.py, tests/sparseml/transformers/obcq/test_obcq.py
https://github.com/neuralmagic/sparseml/pull/2068
=> Update SparseGPT Modifier Defaults CherryPick

src/sparseml/export/export.py, tests/sparseml/transformers/conftest.py, tests/sparseml/transformers/obcq/test_obcq.py, tests/sparseml/transformers/utils/test_helpers.py
=> Cherry Picks from 2/14/24

src/sparseml/evaluation/integrations/perplexity.py
- Use train split if test not available
- Allow passing in a split
- Add support for passing in a text_column_name for datasets where the column name might be different
```python
from sparseml import evaluate
stub = "zoo:llama2-7b-ultrachat200k_llama2_pretrain-pruned60_quantized"
dataset = "tatsu-lab/alpaca"
integration = "perplexity"
res = evaluate(stub, datasets=dataset, integration=integration, limit=10)
print(res)
```
Output:
```bash
formatted=[Evaluation(task='text-generation', dataset=Dataset(type='text-generation', name='tatsu-lab/alpaca', config=None, split=None), metrics=[Metric(name='perplexity', value=9.295503091812133)], samples=None)] raw={'mean_perplexity': 9.295503091812133}
```
---
- …
=> [bugfix] make split inference more robust

src/sparseml/evaluation/integrations/perplexity.py
=> [Cherry Pick] Perplexity Eval dataset split support

src/sparseml/transformers/finetune/data/data_helpers.py
If the calibration dataset is smaller than the requested `num_calibration_samples` running oneshot would fail. With this PR, we instead throw a warning and proceed to calibrate with the full small dataset
This would previously fail, now throws a warning and runs with a truncated number of calibration samples
```
from sparseml.transformers import oneshot 
recipe_str = "tests/sparseml/transformers/obcq/test_tiny2.yaml"
model = "Xenova/llama2.c-stories15M"
device = "cuda:0"
dataset_name = "open_platypus"
concatenate_data = False
num_calibration_samples = 500
output_dir = "oneshot_out"
splits = {"calibration": "train[:1%]"}
oneshot(
model_name_or_path=model,
dataset_name=dataset_name,
output_dir=output_dir,
num_calibration_samples=num_calibration_samples,
recipe=recipe_str, …
```
=> Allow datasets smaller than calibration default

LICENSE-ULTRALYTICS
* Update LICENSE-ULTRALYTICS
Executed December 2023 amendment added
* Update LICENSE-ULTRALYTICS
=> [Cherrypick] Update LICENSE-ULTRALYTICS (#2090)

src/sparseml/transformers/finetune/data/custom.py
Follow up to https://github.com/neuralmagic/sparseml/pull/2093
Automatically get rid of unwanted columns if no `remove_columns` were given
=> Goin custom bug

src/sparseml/export/export.py
Asana Ticket: https://app.asana.com/0/1206109050183159/1206634299539480/f 
Sequence length was being passed as a kwarg twice, fix is to merge the kwargs and model_load_kwargs dicts
=> Fix Export Bugs

src/sparseml/export/export.py, src/sparseml/transformers/integration_helper_functions.py, src/sparseml/transformers/utils/load_task_dataset.py, tests/sparseml/transformers/utils/test_initializers.py
=> Export Cherry Picks

tests/sparseml/pytorch/image_classification/test_export.py
=> [Cherry pick] Update analyze references

src/sparseml/evaluation/integrations/perplexity.py, src/sparseml/utils/helpers.py
=> [Cherry Pick] Evaluate `openai_humaneval` support (#2100)

src/sparseml/transformers/finetune/data/custom.py
Recent change would remove dataset columns before running the custom preprocessing function, this should happen in the opposite direction
=> Fix Custom Dataset Bug

setup.py
adds out of the box support for some llama tokenizers
=> [cherry-pick] add `sentencepiece` to llm_deps (#2124)

src/sparseml/transformers/finetune/data/data_args.py, src/sparseml/transformers/finetune/model_args.py
https://app.asana.com/0/1206109050183159/1206650556968837/f
Dataclass has issues with non default types. Revert
=> [apply UX] change typing to primative

.gitignore, src/sparseml/core/helpers.py, src/sparseml/core/logger/logger.py, src/sparseml/core/logger/utils/frequency_manager.py, src/sparseml/core/session.py, src/sparseml/core/state.py, tests/sparseml/core/logger/utils/test_frequency_manager.py, tests/sparseml/core/test_helpers.py, tests/sparseml/core/test_session.py
Cherry Pick for #2129 
* Preliminary changes that were missed Update Tests
Fix step with loss
WANDB logging fix
Always log loss
Use lifecycle callbacks for logging
Update tests
* update gitignore
* nit
---------
=> [Logger] Use lifecycle callbacks for logging (#2129)

src/sparseml/evaluation/integrations/lm_evaluation_harness.py, src/sparseml/evaluation/integrations/perplexity.py
This PR allows accepting multiple datasets with lm-eval harness, these can be supplied as a comma separated string using the cli or as a list when using the python API
```bash
sparseml.evaluate "mgoin/llama2.c-stories15M-quant-pt" -d "hellaswag,arc_challenge" --limit 10 --integration lm-eval-harness
2024-02-27 17:32:08 sparseml.evaluation.cli INFO     Datasets to evaluate on: hellaswag,arc_challenge
Batch size: 1
Additional integration arguments supplied: {}
Downloading builder script: 100%|█████████████████████████████████████████████████████████████████████████| 5.67k/5.67k [00:00<00:00, 38.4MB/s]
2024-02-27 17:32:10 sparseml.evaluation.registry INFO     Auto collected lm-eval-harness integration for eval
2024-02-27:17:32:10,062 INFO     [registry.py:100] Auto collected lm-eval-harness …
```
=> Accept multiple datasets lm-eval

src/sparseml/evaluation/integrations/lm_evaluation_harness.py, src/sparseml/evaluation/integrations/perplexity.py
=> [Cherry pick] multi dataset lm eval

src/sparseml/transformers/integration_helper_functions.py, tests/sparseml/export/transformers/test_generative_transformers.py
=> [Cherry-Pick][Export API Refactor][Fix] Varying sample and model input names on correctness validation

src/sparseml/core/session.py
i.e event lifecycle is not setup
Cherry Pick for #2137
=> [Cherry Pick]Fix cases when recipe is not given

src/sparseml/evaluation/cli.py
=> [Cherry Pick]Cherry-pick-evaluate-cli-arg

setup.py, src/sparseml/modifiers/distillation/output/base.py, src/sparseml/modifiers/distillation/output/pytorch.py, src/sparseml/modifiers/distillation/utils/pytorch/kd_wrapper.py, src/sparseml/modifiers/distillation/utils/pytorch/model_wrapper.py, src/sparseml/modifiers/quantization/utils/fake_quant_wrapper.py, src/sparseml/modifiers/quantization/utils/quantization_scheme.py, src/sparseml/modifiers/quantization/utils/quantize.py, src/sparseml/modifiers/utils/pytorch_helpers.py, src/sparseml/transformers/finetune/README.md, src/sparseml/transformers/finetune/data/base.py, src/sparseml/transformers/finetune/data/custom.py, src/sparseml/transformers/finetune/data/data_helpers.py, src/sparseml/transformers/finetune/data/evolcodealpaca.py, src/sparseml/transformers/finetune/data/gsm8k.py, src/sparseml/transformers/finetune/data/open_platypus.py, src/sparseml/transformers/finetune/runner.py, src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/utils/sparse_model.py, src/sparseml/utils/fsdp/context.py, src/sparseml/utils/fsdp/helpers.py, src/sparseml/utils/pytorch/module.py, tests/sparseml/transformers/finetune/data/test_dataset_loading.py, tests/sparseml/transformers/obcq/test_obcq.py
=> [Cherry Pick] Finetuning and FakeQuantize Fixes

setup.py, src/sparseml/transformers/finetune/session_mixin.py, src/sparseml/transformers/finetune/text_generation.py, src/sparseml/transformers/finetune/training_args.py, src/sparseml/utils/fsdp/helpers.py, tests/sparseml/transformers/finetune/test_finetune.py
`save_safetensors` already existed as a Trainer argument, we just needed to override it to default it to True and propogate it to the FSDP saver function
* Added unit test for saving/loading
* Manually tested FSDP saving and loading
=> Basic SafeTensors load/save

src/sparseml/core/recipe/container.py, src/sparseml/core/recipe/modifier.py, src/sparseml/core/recipe/recipe.py, tests/sparseml/core/recipe/test_recipe.py, tests/sparseml/transformers/finetune/test_finetune.py
This diff adds support to accept, a Modifier/list of Modifier instance(s) in our train/oneshot flows
Testing:
Automated
Example script:
```python
from sparseml.transformers import (
SparseAutoModelForCausalLM, SparseAutoTokenizer, load_dataset, oneshot
)
from sparseml.modifiers import SparseGPTModifier
model = SparseAutoModelForCausalLM.from_pretrained("facebook/opt-125m")
tokenizer = SparseAutoTokenizer.from_pretrained("facebook/opt-125m")
dataset = "open_platypus"
modifier = SparseGPTModifier(
sparsity=0.5,
)
oneshot(
model=model,
tokenizer=tokenizer,
dataset=dataset,
recipe=modifier,
output_dir="output",
)
```
Output from script:
```bash
2024-03-04 18:23:22 sparseml.transformers.utils.helpers INFO     model_path is a huggingface model id. Attempting to download recipe from …
```
=> [Update]: Add preliminary modifier support

src/sparseml/evaluation/integrations/lm_evaluation_harness.py
=> [Cherry Pick] Explicitly pass in the tokenizer for non-downloaded zoo stubs

src/sparseml/core/logger/logger.py, src/sparseml/utils/helpers.py
* Utility method to check if a package is available and not just a directory
* Use that function to check for wandb availability
Cherry-Pick for #2161
=> [Cherry-pick] WANDB availability bugfix

src/sparseml/core/recipe/recipe.py, src/sparseml/transformers/finetune/session_mixin.py, src/sparseml/transformers/finetune/text_generation.py, tests/sparseml/core/lifecycle/test_session.py
* initial commit
* pass overrides
* remove outdated unit test
* quality
* fix sparsity arg too
=> Sa/fix recipe args (#2160)

src/sparseml/transformers/finetune/runner.py
I was finally able to reproduce the `RuntimeError: CUDA error: unspecified launch failure` issue in this ticket: https://app.asana.com/0/1206109050183159/1206754046199279/f.
Oddly this error only triggers when launching from the CLI. I also noticed it occured when other processes were running on the GPU
```bash
sparseml.transformers.text_generation.oneshot \
--dataset "open_platypus" \
--output_dir "./oneshot_output" \
--num_calibration_samples 1024 \
--recipe  "test_simple_sgpt.yaml" \
--model "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T" \
--pad_to_max_length false \
--oneshot_device "auto"
```
Removing the device map auto fixed the issue, but it was also revealed that setting `--oneshot_device` to anything except "cuda:0" would cause an error as well. This PR fixes both issues …
=> Fix for CUDA launch failure

src/sparseml/core/utils/__init__.py, src/sparseml/core/utils/session_helpers.py, src/sparseml/evaluation/evaluator.py
* Add a context manager to setup fresh session within, and refresh on context exit
* Refresh session b/w evaluate calls using the context manager
=> [Potential Bug] Refresh session b/w evaluate calls

src/sparseml/modifiers/pruning/constant/pytorch.py, src/sparseml/transformers/finetune/runner.py, src/sparseml/transformers/finetune/session_mixin.py
* testing fix
* get rid of repeated log
* revert yaml
=> [Cherry Pick] Fix for OOM Errors during Ultrachat200k Finetuning (#2180)

.github/workflows/build-wheel.yml, setup.py, src/sparseml/version.py
- This PR is identical to the sparsezoo PR: https://github.com/neuralmagic/sparsezoo/pull/473
- Makes use of the same nm-actions
=> Add build workflows for dev, nightly, and release wheels

src/sparseml/transformers/finetune/runner.py, src/sparseml/utils/fsdp/helpers.py, src/sparseml/version.py
Cherry Pick for #2183 
---
- https://app.asana.com/0/0/1206841566630295
=> [Cherry pick] quantized fsdp model loading

src/sparseml/pytorch/model_load/helpers.py
Bugfix for the following ticket: https://app.asana.com/0/1205229323407165/1206936014133703/f
The failing commands in the test ticket now work!
We did not incorporate a check for the safetensors file(s) during the state dictionary reload process. This was due to the early return within the function reload_model_state, which resulted in the initialize_channel_wise_scale_zp function not being invoked on the model. Consequently, this mismatched the shapes of zero points and scales, leading to the following error during inference: `RuntimeError: dimensions of scale and zero-point are not consistent with input tensor`
=> [BugFix] Loading channelwise quantized models

setup.py
Hopefully this isn't an issue anymore https://github.com/neuralmagic/sparseml/pull/982
=> Remove setuptools restriction from setup.py

setup.py, src/sparseml/pytorch/base.py
This PR upgrades torch support to 2.2.xx
Test plan, ran `make test` all tests pass
`=============================== 494 passed, 4 skipped, 5 warnings in 14.85s ===============================`
=> upgrade torch support to 2.2

tests/sparseml/transformers/test_clear_ml.py
Updated to also fix the failing transformers test
=> Fix failing quality check 

src/sparseml/modifiers/quantization/gptq/pytorch.py
Fixes transformers tests by applying a commit that was missed
=> Fix transformers tests

tests/sparseml/export/transformers/test_generative_transformers.py
Missing change from the QuantizationModifier update, fixes the failing export test
=> Fix Export Test w/Quantization

tests/sparseml/transformers/sparsification/test_compress_tensor_utils.py
Relevant once https://github.com/neuralmagic/compressed-tensors/pull/73 lands
=> Update Tests for Compression Config Change
